-- Category
INSERT INTO learn_categories (id, name, description, order_index)
VALUES ('number_systems_and_properties', 'Number Systems and Properties', 'Properties of real numbers, number set classification, arithmetic, and structure.', 1)
ON CONFLICT (id) DO NOTHING;

-- ─── Umbrella keywords ────────────────────────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('real_number_classification', 'Real Number Classification', 'Real Number Classification', 'Number-set membership and relationships among natural numbers, whole numbers, integers, rational numbers, irrational numbers, and real numbers.', 'number_systems_and_properties', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('number_representations', 'Number Representations', 'Number Representations', 'Equivalent ways to represent numeric quantities, including fractions, decimals, percents, place value, expanded form, and scientific notation.', 'number_systems_and_properties', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('integer_divisibility_and_factor_structure', 'Integer Divisibility and Factor Structure', 'Integer Divisibility and Factor Structure', 'Properties of integers involving divisibility, factors, multiples, primes, parity, remainders, greatest common factors, and least common multiples.', 'number_systems_and_properties', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('signed_number_structure', 'Signed Number Structure', 'Signed Number Structure', 'Positive and negative number behavior, including opposites, signs, magnitude, absolute value, and number-line distance.', 'number_systems_and_properties', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('rational_number_arithmetic', 'Rational Number Arithmetic', 'Rational Number Arithmetic', 'Arithmetic with numeric fractions and decimals, including common denominators, reciprocal relationships, decimal operations, and complex numeric fractions.', 'number_systems_and_properties', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('percent_and_proportional_number_structure', 'Percent and Proportional Number Structure', 'Percent and Proportional Number Structure', 'Numeric percent relationships, percent factors, percent change, ratio structure, and proportional comparisons without algebraic equation solving.', 'number_systems_and_properties', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('real_number_order_and_comparison', 'Real Number Order and Comparison', 'Real Number Order and Comparison', 'Ordering, comparing, locating, and bounding real numbers on the number line, including fractions, decimals, signed numbers, and irrational approximations.', 'number_systems_and_properties', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('real_number_operation_properties', 'Real Number Operation Properties', 'Real Number Operation Properties', 'Structural properties of real-number arithmetic, including commutativity, associativity, distributivity, identities, inverses, zero behavior, and division restrictions.', 'number_systems_and_properties', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('numeric_expression_structure', 'Numeric Expression Structure', 'Numeric Expression Structure', 'Order, grouping, and interpretation of numeric expressions without variables, including operation precedence, parentheses, fraction bars, absolute value bars, and negative signs.', 'number_systems_and_properties', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('approximation_estimation_and_bounds', 'Approximation, Estimation, and Bounds', 'Approximation, Estimation, and Bounds', 'Reasonable numeric approximations, rounding behavior, compatible numbers, bounds from rounded values, and magnitude checks.', 'number_systems_and_properties', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL)
ON CONFLICT (id) DO NOTHING;

-- ─── real_number_classification topics ───────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('natural_numbers', 'Natural numbers', 'Natural numbers', 'The counting numbers used for positive whole-number quantities: 1, 2, 3, and so on. This excludes 0, negative numbers, fractions, decimals, and irrationals.', 'number_systems_and_properties', '["Classify 17 using the most specific real-number set.", "Identify whether 0 belongs to the natural numbers.", "Select all natural numbers from the list -3, 0, 4, 7.5, 9."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_classification'),
('whole_numbers', 'Whole numbers', 'Whole numbers', 'The nonnegative integers 0, 1, 2, 3, and so on. This differs from natural numbers by explicitly including 0.', 'number_systems_and_properties', '["Classify 0 using the real-number subsets.", "Identify which numbers in the set {-2, 0, 5, 6.2} are whole numbers.", "Determine whether every natural number is also a whole number."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_classification'),
('integers', 'Integers', 'Integers', 'Positive whole numbers, negative whole numbers, and 0. This excludes non-integer fractions, decimals, and irrational numbers.', 'number_systems_and_properties', '["Classify -12 using the real-number subsets.", "Identify the integers in the list -5, -1.2, 0, 8, 9.5.", "Determine whether -7 belongs to the whole numbers or only the integers."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_classification'),
('rational_numbers', 'Rational numbers', 'Rational numbers', 'Numbers expressible as a ratio of two integers with a nonzero denominator. This includes integers, fractions, terminating decimals, and repeating decimals.', 'number_systems_and_properties', '["Classify 0.75 as rational or irrational.", "Identify which numbers in the list 3, -2/5, 0.333..., and sqrt(5) are rational.", "Determine whether -8 can be written as a ratio of integers."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_classification'),
('irrational_numbers', 'Irrational numbers', 'Irrational numbers', 'Real numbers that cannot be written as a ratio of two integers. These have decimal expansions that do not terminate or repeat.', 'number_systems_and_properties', '["Classify sqrt(7) as rational or irrational.", "Identify the irrational numbers in the list pi, 0.25, sqrt(16), and sqrt(2).", "Determine whether 0.101001000100001... is rational or irrational."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_classification'),
('real_numbers', 'Real numbers', 'Real numbers', 'All rational and irrational numbers that can be placed on the number line. This category excludes non-real complex numbers.', 'number_systems_and_properties', '["Classify -4.6 as a real number.", "Identify whether sqrt(11) belongs to the real numbers.", "Determine which listed numbers can be placed on the real number line."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_classification'),
('number_set_containment_chain', 'Containment of real-number sets', 'Containment of real-number sets', 'The nested relationship natural ⊂ whole ⊂ integers ⊂ rational ⊂ real, with irrational numbers also contained in the real numbers but separate from rational numbers.', 'number_systems_and_properties', '["Identify the smallest set that contains all integers.", "Determine whether every whole number is also rational.", "Place natural numbers, integers, rationals, irrationals, and reals in a containment diagram."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_classification'),
('multiple_number_set_membership', 'Multiple membership in number sets', 'Multiple membership in number sets', 'A single number can belong to several real-number subsets at once. This focuses on listing all valid memberships rather than only the smallest set.', 'number_systems_and_properties', '["List all real-number subsets that contain 6.", "Identify every set that contains 0 from natural, whole, integer, rational, irrational, and real.", "Determine all number-set memberships for -3."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_classification'),
('least_restrictive_number_set_classification', 'Most specific number-set classification', 'Most specific number-set classification', 'The smallest standard real-number subset that describes a number. This distinguishes classifying 5 as natural rather than only rational or real.', 'number_systems_and_properties', '["Classify 12 using the most specific real-number subset.", "Identify the most specific set containing -9.", "Determine the narrowest real-number classification for 3/4."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_classification'),
('rational_decimal_forms', 'Rational decimal forms', 'Rational decimal forms', 'Rational numbers have decimal expansions that either terminate or repeat. This separates rational decimals from nonterminating, nonrepeating irrational decimals.', 'number_systems_and_properties', '["Classify 0.444... as rational or irrational.", "Identify whether 0.125 has a rational decimal form.", "Determine whether 2.363636... can be written as a fraction."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_classification'),
('irrational_decimal_forms', 'Irrational decimal forms', 'Irrational decimal forms', 'Irrational numbers have decimal expansions that continue forever without a repeating block. This focuses on recognizing irrationality from decimal behavior.', 'number_systems_and_properties', '["Classify 0.101001000100001... as rational or irrational.", "Identify whether a nonterminating decimal with no repeating pattern is rational.", "Determine which decimal form represents an irrational number."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_classification'),
('perfect_square_integer_roots', 'Perfect-square integer roots', 'Perfect-square integer roots', 'Square roots of perfect-square nonnegative integers are integers. This belongs here only as number classification, not radical simplification.', 'number_systems_and_properties', '["Classify sqrt(49) using the most specific real-number set.", "Identify whether sqrt(81) is rational.", "Determine which square roots in the list sqrt(9), sqrt(10), and sqrt(16) are integers."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_classification'),
('nonperfect_square_irrational_roots', 'Non-perfect-square irrational roots', 'Non-perfect-square irrational roots', 'Square roots of positive integers that are not perfect squares are irrational. This focuses on classification, not rewriting radical expressions.', 'number_systems_and_properties', '["Classify sqrt(13) as rational or irrational.", "Identify which numbers in the list sqrt(2), sqrt(4), sqrt(18), and sqrt(25) are irrational.", "Determine whether sqrt(50) is rational without rewriting it."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_classification')
ON CONFLICT (id) DO NOTHING;

-- ─── number_representations topics ───────────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('decimal_place_value', 'Decimal place value', 'Decimal place value', 'The value of digits based on their position relative to the decimal point. This includes tenths, hundredths, thousandths, and larger whole-number places.', 'number_systems_and_properties', '["Identify the value of 7 in 42.375.", "Write 508.064 in expanded place-value form.", "Determine which digit is in the hundredths place in 19.482."]'::jsonb, 'approved', 'in_depth', 'topic', 'number_representations'),
('expanded_notation_for_numbers', 'Expanded notation for numbers', 'Expanded notation for numbers', 'A number written as the sum of its place-value parts. This covers numeric place-value decomposition without variables.', 'number_systems_and_properties', '["Write 4,305 as 4,000 + 300 + 5.", "Write 62.48 in expanded notation.", "Identify the expanded form that matches 7.209."]'::jsonb, 'approved', 'in_depth', 'topic', 'number_representations'),
('equivalent_fraction_forms', 'Equivalent fraction forms', 'Equivalent fraction forms', 'Fractions that represent the same rational number because numerator and denominator are scaled by the same nonzero factor.', 'number_systems_and_properties', '["Identify a fraction equivalent to 3/5.", "Determine whether 8/12 and 2/3 are equivalent.", "Write three fractions equivalent to 4/7."]'::jsonb, 'approved', 'in_depth', 'topic', 'number_representations'),
('fractions_lowest_terms_by_gcf', 'Fractions in lowest terms', 'Fractions in lowest terms', 'A fraction is in lowest terms when numerator and denominator share no common factor greater than 1. This depends on the greatest common factor of two integers.', 'number_systems_and_properties', '["Write 18/24 in lowest terms.", "Identify whether 14/21 is in lowest terms.", "Determine the lowest-term form of 45/60."]'::jsonb, 'approved', 'in_depth', 'topic', 'number_representations'),
('improper_fractions_and_mixed_numbers', 'Improper fractions and mixed numbers', 'Improper fractions and mixed numbers', 'Equivalent representations of rational numbers greater than or equal to 1 using either a numerator at least as large as the denominator or a whole-number-plus-fraction form.', 'number_systems_and_properties', '["Write 17/5 as a mixed number.", "Write 3 2/7 as an improper fraction.", "Identify which mixed number is equivalent to 23/4."]'::jsonb, 'approved', 'in_depth', 'topic', 'number_representations'),
('terminating_decimal_to_fraction', 'Terminating decimal fraction forms', 'Terminating decimal fraction forms', 'Terminating decimals can be written as fractions with denominators based on powers of 10, then reduced if needed.', 'number_systems_and_properties', '["Write 0.36 as a fraction.", "Write 2.125 as a mixed number.", "Identify the fraction equivalent to 0.004."]'::jsonb, 'approved', 'in_depth', 'topic', 'number_representations'),
('repeating_decimal_to_fraction', 'Repeating decimal fraction forms', 'Repeating decimal fraction forms', 'Repeating decimals can be written as fractions by using the repeating block. This is distinct from terminating decimal conversion.', 'number_systems_and_properties', '["Write 0.777... as a fraction.", "Write 0.232323... as a fraction.", "Identify the fraction equivalent to 1.666..."]'::jsonb, 'approved', 'in_depth', 'topic', 'number_representations'),
('fraction_to_decimal_forms', 'Fraction-to-decimal forms', 'Fraction-to-decimal forms', 'Fractions can be represented as terminating or repeating decimals depending on the denominator structure after reduction.', 'number_systems_and_properties', '["Write 3/8 as a decimal.", "Write 2/3 as a decimal.", "Determine whether 7/20 has a terminating decimal form."]'::jsonb, 'approved', 'in_depth', 'topic', 'number_representations'),
('fraction_decimal_percent_equivalence', 'Fraction-decimal-percent equivalence', 'Fraction-decimal-percent equivalence', 'The same rational quantity can be represented as a fraction, decimal, or percent. This focuses on representation, not percent word-problem modeling.', 'number_systems_and_properties', '["Write 0.45 as a percent and a fraction.", "Write 3/5 as a decimal and a percent.", "Identify the decimal equivalent to 12.5%."]'::jsonb, 'approved', 'in_depth', 'topic', 'number_representations'),
('scientific_notation_form', 'Scientific notation form', 'Scientific notation form', 'A number in scientific notation has the form a × 10^n where 1 ≤ |a| < 10 and n is an integer. This covers representation only, not exponent-law arithmetic.', 'number_systems_and_properties', '["Identify whether 4.2 × 10^5 is written in scientific notation.", "Write 680,000 in scientific notation.", "Write 0.00091 in scientific notation."]'::jsonb, 'approved', 'in_depth', 'topic', 'number_representations'),
('standard_form_from_scientific_notation', 'Standard form from scientific notation', 'Standard form from scientific notation', 'Scientific notation can be converted back to ordinary decimal notation by using the sign and size of the power of 10.', 'number_systems_and_properties', '["Write 3.4 × 10^6 in standard form.", "Write 7.81 × 10^-4 in standard form.", "Identify the standard decimal form of 5.02 × 10^3."]'::jsonb, 'approved', 'in_depth', 'topic', 'number_representations'),
('exact_and_approximate_number_forms', 'Exact and approximate number forms', 'Exact and approximate number forms', 'Exact values represent quantities without rounding, while approximate values are rounded or estimated. This matters for distinguishing fractions, decimals, radicals, and rounded decimals.', 'number_systems_and_properties', '["Identify whether 1/3 or 0.333 is the exact value.", "Determine whether 3.14 is an exact representation of pi.", "Classify sqrt(2) and 1.414 as exact or approximate forms."]'::jsonb, 'approved', 'in_depth', 'topic', 'number_representations')
ON CONFLICT (id) DO NOTHING;

-- ─── integer_divisibility_and_factor_structure topics ────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('even_and_odd_integers', 'Even and odd integers', 'Even and odd integers', 'Even integers are divisible by 2, while odd integers are not. This covers parity as a property of integers.', 'number_systems_and_properties', '["Classify -14 as even or odd.", "Identify the odd integers in the list -3, 0, 8, 11.", "Determine whether the product of two odd integers is odd."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_divisibility_and_factor_structure'),
('parity_of_sums_and_products', 'Parity of sums and products', 'Parity of sums and products', 'The even or odd status of sums and products follows predictable patterns. This focuses on parity reasoning without variables.', 'number_systems_and_properties', '["Determine whether the sum of two odd numbers is even or odd.", "Identify the parity of an even number times an odd number.", "Classify the result of odd + even as even or odd."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_divisibility_and_factor_structure'),
('factors_and_multiples', 'Factors and multiples', 'Factors and multiples', 'A factor divides a number evenly, while a multiple is the result of multiplying by an integer. This is the base idea behind divisibility.', 'number_systems_and_properties', '["List the positive factors of 24.", "Identify whether 7 is a factor of 56.", "List the first five positive multiples of 9."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_divisibility_and_factor_structure'),
('divisibility_by_2_5_10', 'Divisibility by 2, 5, and 10', 'Divisibility by 2, 5, and 10', 'Divisibility rules based on the final digit of an integer. This covers quick recognition for divisors 2, 5, and 10.', 'number_systems_and_properties', '["Identify whether 3,840 is divisible by 10.", "Determine which numbers in the list 125, 342, 760, and 891 are divisible by 5.", "Classify 4,218 as divisible or not divisible by 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_divisibility_and_factor_structure'),
('divisibility_by_3_and_9', 'Divisibility by 3 and 9', 'Divisibility by 3 and 9', 'Divisibility rules based on the sum of digits. This separates divisibility by 3 and 9 from final-digit tests.', 'number_systems_and_properties', '["Determine whether 621 is divisible by 3.", "Identify whether 7,452 is divisible by 9.", "Classify the numbers 234, 729, and 1,001 by divisibility by 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_divisibility_and_factor_structure'),
('divisibility_by_4_and_8', 'Divisibility by 4 and 8', 'Divisibility by 4 and 8', 'Divisibility rules based on the last two or last three digits of an integer. This is distinct from single-digit ending rules.', 'number_systems_and_properties', '["Determine whether 3,216 is divisible by 4.", "Identify whether 5,128 is divisible by 8.", "Classify 1,404 by divisibility by 4."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_divisibility_and_factor_structure'),
('divisibility_by_6_and_12', 'Divisibility by 6 and 12', 'Divisibility by 6 and 12', 'Composite divisibility rules based on satisfying multiple simpler divisibility conditions. This focuses on combined divisibility logic.', 'number_systems_and_properties', '["Determine whether 726 is divisible by 6.", "Identify whether 1,248 is divisible by 12.", "Classify which numbers in a list are divisible by both 3 and 4."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_divisibility_and_factor_structure'),
('prime_and_composite_numbers', 'Prime and composite numbers', 'Prime and composite numbers', 'Prime numbers have exactly two positive factors, while composite numbers have more than two. This applies to positive integers greater than 1.', 'number_systems_and_properties', '["Classify 29 as prime or composite.", "Identify the prime numbers in the list 1, 2, 9, 17, 21.", "Determine whether 1 is prime, composite, or neither."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_divisibility_and_factor_structure'),
('prime_factorization', 'Prime factorization', 'Prime factorization', 'A positive integer greater than 1 written as a product of prime factors. This is numeric factor structure, not polynomial factoring.', 'number_systems_and_properties', '["Write 84 as a product of prime factors.", "Identify the prime factorization of 150.", "Determine which prime factors appear in 72."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_divisibility_and_factor_structure'),
('greatest_common_factor_integers', 'Greatest common factor of integers', 'Greatest common factor of integers', 'The largest positive integer that divides two or more integers evenly. This is numeric GCF only, not algebraic GCF with variables.', 'number_systems_and_properties', '["Find the greatest common factor of 18 and 30.", "Identify the GCF of 24, 36, and 60.", "Determine the largest common factor of 45 and 75."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_divisibility_and_factor_structure'),
('least_common_multiple_integers', 'Least common multiple of integers', 'Least common multiple of integers', 'The smallest positive integer that is a multiple of two or more integers. This supports common denominators but is a separate integer-structure topic.', 'number_systems_and_properties', '["Find the least common multiple of 6 and 8.", "Identify the LCM of 9, 12, and 18.", "Determine the smallest positive common multiple of 14 and 21."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_divisibility_and_factor_structure'),
('relatively_prime_integers', 'Relatively prime integers', 'Relatively prime integers', 'Two integers are relatively prime when their greatest common factor is 1. This does not require either number itself to be prime.', 'number_systems_and_properties', '["Determine whether 8 and 15 are relatively prime.", "Identify which pair is relatively prime: 12 and 18, 14 and 25, or 21 and 28.", "Classify 35 and 64 as relatively prime or not relatively prime."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_divisibility_and_factor_structure'),
('remainders_after_integer_division', 'Remainders after integer division', 'Remainders after integer division', 'Integer division can be expressed using a quotient and remainder, where the remainder is nonnegative and smaller than the divisor.', 'number_systems_and_properties', '["Find the remainder when 47 is divided by 5.", "Identify the quotient and remainder for 83 divided by 9.", "Determine which number leaves a remainder of 2 when divided by 4."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_divisibility_and_factor_structure')
ON CONFLICT (id) DO NOTHING;

-- ─── signed_number_structure topics (additive_inverse_pairs removed) ──────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('positive_negative_and_zero', 'Positive numbers, negative numbers, and zero', 'Positive numbers, negative numbers, and zero', 'The sign of a number indicates whether it is greater than, less than, or equal to zero. Zero is neither positive nor negative.', 'number_systems_and_properties', '["Classify -0.6 as positive, negative, or zero.", "Identify whether 0 is positive, negative, or neither.", "Determine which numbers in a list are negative."]'::jsonb, 'approved', 'in_depth', 'topic', 'signed_number_structure'),
('opposite_numbers', 'Opposite numbers', 'Opposite numbers', 'Opposite numbers are the same distance from zero on opposite sides of the number line. They have equal magnitudes and opposite signs.', 'number_systems_and_properties', '["Identify the opposite of -11.", "Determine which number is opposite 4.8.", "Locate 6 and its opposite on a number line."]'::jsonb, 'approved', 'in_depth', 'topic', 'signed_number_structure'),
('absolute_value_as_magnitude', 'Absolute value as magnitude', 'Absolute value as magnitude', 'Absolute value represents a number''s distance from 0 and is always nonnegative. This is numeric absolute value, not absolute value equations or functions.', 'number_systems_and_properties', '["Find the absolute value of -18.", "Identify the value of |0|.", "Compare |-6| and |4|."]'::jsonb, 'approved', 'in_depth', 'topic', 'signed_number_structure'),
('distance_between_numbers_on_number_line', 'Distance between numbers on the number line', 'Distance between numbers on the number line', 'The distance between two real numbers is the absolute value of their difference. This is numeric distance, not coordinate-plane distance.', 'number_systems_and_properties', '["Find the distance between -3 and 8 on the number line.", "Determine how far 2.5 is from -1.5.", "Identify the distance between -7 and -2."]'::jsonb, 'approved', 'in_depth', 'topic', 'signed_number_structure'),
('midpoint_between_two_real_numbers', 'Midpoint between two real numbers', 'Midpoint between two real numbers', 'The midpoint of two numbers on a number line is their average. This is one-dimensional numeric midpoint, not coordinate geometry.', 'number_systems_and_properties', '["Find the midpoint between -4 and 10.", "Determine the number halfway between 3.5 and 8.5.", "Identify the midpoint of -7 and -1 on a number line."]'::jsonb, 'approved', 'in_depth', 'topic', 'signed_number_structure'),
('sign_of_products', 'Sign of products', 'Sign of products', 'The sign of a product depends on the number of negative factors. An even number of negative factors gives a positive product; an odd number gives a negative product.', 'number_systems_and_properties', '["Determine the sign of (-3)(5)(-2).", "Identify whether the product of three negative numbers is positive or negative.", "Classify the sign of (-1)(-4)(-6)(2)."]'::jsonb, 'approved', 'in_depth', 'topic', 'signed_number_structure'),
('sign_of_quotients', 'Sign of quotients', 'Sign of quotients', 'The sign of a quotient depends on whether the dividend and divisor have the same or opposite signs. Division by zero is treated separately.', 'number_systems_and_properties', '["Determine the sign of -24 divided by 6.", "Identify whether (-15)/(-3) is positive or negative.", "Classify the sign of 18/(-2)."]'::jsonb, 'approved', 'in_depth', 'topic', 'signed_number_structure'),
('signed_number_addition_same_signs', 'Signed-number addition with same signs', 'Signed-number addition with same signs', 'When adding numbers with the same sign, magnitudes combine and the common sign remains. This focuses on sign behavior in numeric addition.', 'number_systems_and_properties', '["Find the value of -8 + -5.", "Determine the sum of 4.2 + 1.6.", "Identify the sign of -12 + -9."]'::jsonb, 'approved', 'in_depth', 'topic', 'signed_number_structure'),
('signed_number_addition_opposite_signs', 'Signed-number addition with opposite signs', 'Signed-number addition with opposite signs', 'When adding numbers with opposite signs, magnitudes are compared and the sign of the larger magnitude remains.', 'number_systems_and_properties', '["Find the value of -9 + 4.", "Determine the sum of 12 + -17.", "Identify the sign of -3.5 + 8.1."]'::jsonb, 'approved', 'in_depth', 'topic', 'signed_number_structure'),
('signed_number_subtraction_as_adding_opposite', 'Signed-number subtraction as adding the opposite', 'Signed-number subtraction as adding the opposite', 'Subtracting a signed number is equivalent to adding its opposite. This distinguishes subtraction from simply combining signs.', 'number_systems_and_properties', '["Rewrite 7 - (-3) as addition.", "Find the value of -5 - 8.", "Determine the equivalent addition expression for -2 - (-11)."]'::jsonb, 'approved', 'in_depth', 'topic', 'signed_number_structure'),
('negative_signs_and_grouping', 'Negative signs and grouping', 'Negative signs and grouping', 'A negative sign outside grouping symbols changes the sign of the entire grouped quantity. This is numeric grouping, not algebraic distribution with variables.', 'number_systems_and_properties', '["Find the value of -(6 - 10).", "Determine the value of -(-4 + 9).", "Identify the result of applying a negative sign to the quantity 3 - 8."]'::jsonb, 'approved', 'in_depth', 'topic', 'signed_number_structure')
ON CONFLICT (id) DO NOTHING;

-- ─── rational_number_arithmetic topics (reciprocal_relationships removed) ─────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('fraction_addition_common_denominators', 'Fraction addition with common denominators', 'Fraction addition with common denominators', 'Fractions with the same denominator can be added by combining numerators while keeping the denominator unchanged.', 'number_systems_and_properties', '["Find the sum 3/11 + 5/11.", "Determine the value of -2/7 + 6/7.", "Identify the numerator of the sum 4/9 + 1/9."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_number_arithmetic'),
('fraction_subtraction_common_denominators', 'Fraction subtraction with common denominators', 'Fraction subtraction with common denominators', 'Fractions with the same denominator can be subtracted by subtracting numerators while keeping the denominator unchanged.', 'number_systems_and_properties', '["Find the difference 8/13 - 5/13.", "Determine the value of 1/6 - 5/6.", "Identify the result of 7/10 - 3/10."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_number_arithmetic'),
('least_common_denominator', 'Least common denominator', 'Least common denominator', 'The least common denominator is the least common multiple of fraction denominators. This is the denominator-selection skill behind unlike-denominator fraction arithmetic.', 'number_systems_and_properties', '["Find the least common denominator of 1/6 and 1/8.", "Identify the LCD for fractions with denominators 9 and 12.", "Determine the least common denominator of 5/14 and 3/21."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_number_arithmetic'),
('fraction_addition_unlike_denominators', 'Fraction addition with unlike denominators', 'Fraction addition with unlike denominators', 'Fractions with different denominators must be rewritten using a common denominator before their numerators can be combined.', 'number_systems_and_properties', '["Find the sum 2/3 + 1/4.", "Determine the value of 5/6 + 7/9.", "Identify the correct common-denominator form for 3/5 + 1/2."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_number_arithmetic'),
('fraction_subtraction_unlike_denominators', 'Fraction subtraction with unlike denominators', 'Fraction subtraction with unlike denominators', 'Fractions with different denominators must be rewritten using a common denominator before subtraction. This is separate from addition because sign and order errors are common.', 'number_systems_and_properties', '["Find the difference 5/6 - 1/4.", "Determine the value of 7/10 - 2/15.", "Identify the correct common-denominator form for 3/8 - 1/6."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_number_arithmetic'),
('fraction_multiplication', 'Fraction multiplication', 'Fraction multiplication', 'Numeric fractions are multiplied by multiplying numerators and denominators. This includes proper fractions, improper fractions, and signed fractions.', 'number_systems_and_properties', '["Find the product 3/5 × 10/9.", "Determine the value of -2/7 × 14/3.", "Identify the product of 4/11 and 5/6."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_number_arithmetic'),
('fraction_division_by_reciprocal', 'Fraction division by reciprocals', 'Fraction division by reciprocals', 'Dividing by a nonzero fraction is equivalent to multiplying by its reciprocal. This focuses on numeric fraction division only.', 'number_systems_and_properties', '["Find the quotient 3/4 ÷ 2/5.", "Determine the value of -5/6 ÷ 10/9.", "Identify the reciprocal used when dividing by 7/8."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_number_arithmetic'),
('numeric_complex_fractions', 'Numeric complex fractions', 'Numeric complex fractions', 'A complex fraction has a fraction in its numerator, denominator, or both. This topic is numeric only and does not include rational expressions with variables.', 'number_systems_and_properties', '["Find the value of (3/4)/(5/6).", "Determine the equivalent simple fraction for (1/2)/(3).", "Identify the result of (7)/(2/5)."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_number_arithmetic'),
('decimal_addition_and_subtraction_alignment', 'Decimal addition and subtraction alignment', 'Decimal addition and subtraction alignment', 'Decimal addition and subtraction require aligning place values by decimal point. This distinguishes decimal place-value structure from fraction methods.', 'number_systems_and_properties', '["Find the value of 4.8 + 0.37.", "Determine the difference 12.05 - 3.9.", "Identify the correctly aligned setup for 6.2 - 0.48."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_number_arithmetic'),
('decimal_multiplication_place_value', 'Decimal multiplication place value', 'Decimal multiplication place value', 'Decimal multiplication uses whole-number multiplication together with decimal-place counting. This focuses on placement of the decimal point in products.', 'number_systems_and_properties', '["Find the product 0.6 × 0.04.", "Determine the value of 3.25 × 1.2.", "Identify the correct decimal placement for 48 × 0.07."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_number_arithmetic'),
('decimal_division_place_value', 'Decimal division place value', 'Decimal division place value', 'Decimal division uses place-value shifts to divide by whole numbers or decimals. This focuses on decimal placement in quotients.', 'number_systems_and_properties', '["Find the quotient 4.8 ÷ 0.6.", "Determine the value of 0.035 ÷ 0.5.", "Identify the equivalent whole-number division for 7.2 ÷ 0.03."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_number_arithmetic')
ON CONFLICT (id) DO NOTHING;

-- ─── percent_and_proportional_number_structure topics ─────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('percent_as_rate_per_hundred', 'Percent as a rate per hundred', 'Percent as a rate per hundred', 'A percent represents a quantity out of 100. This focuses on the meaning and representation of percent, not applied percent equations.', 'number_systems_and_properties', '["Write 37% as a fraction out of 100.", "Identify the decimal form of 8%.", "Determine the percent equivalent of 0.62."]'::jsonb, 'approved', 'in_depth', 'topic', 'percent_and_proportional_number_structure'),
('percent_of_a_number', 'Percent of a number', 'Percent of a number', 'A percent of a number is found by treating the percent as a decimal or fraction multiplier. This is numeric percent arithmetic without unknown variables.', 'number_systems_and_properties', '["Find 20% of 45.", "Determine 12.5% of 80.", "Identify the value of 150% of 30."]'::jsonb, 'approved', 'in_depth', 'topic', 'percent_and_proportional_number_structure'),
('percent_increase_factors', 'Percent increase factors', 'Percent increase factors', 'A percent increase corresponds to multiplying by 1 plus the percent written as a decimal. This emphasizes the multiplier structure behind increases.', 'number_systems_and_properties', '["Identify the multiplier for a 15% increase.", "Determine the result of increasing 60 by 25%.", "Write the growth factor for a 4% increase."]'::jsonb, 'approved', 'in_depth', 'topic', 'percent_and_proportional_number_structure'),
('percent_decrease_factors', 'Percent decrease factors', 'Percent decrease factors', 'A percent decrease corresponds to multiplying by 1 minus the percent written as a decimal. This emphasizes the multiplier structure behind decreases.', 'number_systems_and_properties', '["Identify the multiplier for a 30% decrease.", "Determine the result of decreasing 90 by 10%.", "Write the decay factor for a 7% decrease."]'::jsonb, 'approved', 'in_depth', 'topic', 'percent_and_proportional_number_structure'),
('percent_change', 'Percent change', 'Percent change', 'Percent change compares the amount of change to the original value. This is numeric change structure, not exponential growth modeling.', 'number_systems_and_properties', '["Find the percent change from 40 to 50.", "Determine the percent decrease from 80 to 68.", "Identify whether a change from 25 to 30 is a 20% increase or a 5% increase."]'::jsonb, 'approved', 'in_depth', 'topic', 'percent_and_proportional_number_structure'),
('successive_percent_changes', 'Successive percent changes', 'Successive percent changes', 'Multiple percent changes apply multiplicatively rather than additively. This distinguishes sequential percent structure from single percent change.', 'number_systems_and_properties', '["Determine the final value after increasing 100 by 10% and then decreasing by 10%.", "Identify the combined multiplier for a 20% increase followed by a 5% increase.", "Find the result of two successive 50% decreases starting from 80."]'::jsonb, 'approved', 'in_depth', 'topic', 'percent_and_proportional_number_structure'),
('percentage_points_vs_percent_change', 'Percentage points versus percent change', 'Percentage points versus percent change', 'Percentage points measure the arithmetic difference between percents, while percent change measures relative change compared to an original percent.', 'number_systems_and_properties', '["Distinguish a change from 20% to 25% as percentage points and percent change.", "Identify the percentage-point increase from 7% to 12%.", "Determine whether moving from 40% to 60% is a 20% increase or a 20 percentage-point increase."]'::jsonb, 'approved', 'in_depth', 'topic', 'percent_and_proportional_number_structure'),
('ratio_part_to_part_structure', 'Part-to-part ratios', 'Part-to-part ratios', 'A part-to-part ratio compares two components of a whole. This is numeric ratio structure without solving proportion equations.', 'number_systems_and_properties', '["Identify the ratio of red marbles to blue marbles if there are 6 red and 9 blue.", "Write the ratio 12 boys to 15 girls in lowest terms.", "Determine the part-to-part ratio from a group with 8 cats and 5 dogs."]'::jsonb, 'approved', 'in_depth', 'topic', 'percent_and_proportional_number_structure'),
('ratio_part_to_whole_structure', 'Part-to-whole ratios', 'Part-to-whole ratios', 'A part-to-whole ratio compares one component to the total amount. This differs from part-to-part ratio comparisons.', 'number_systems_and_properties', '["Identify the ratio of red marbles to total marbles if there are 6 red and 9 blue.", "Write the part-to-whole ratio for 4 wins in 10 games.", "Determine the fraction of the group that is 7 out of 20."]'::jsonb, 'approved', 'in_depth', 'topic', 'percent_and_proportional_number_structure'),
('unit_rates', 'Unit rates', 'Unit rates', 'A unit rate compares a quantity to one unit of another quantity. This is numeric rate structure, not linear function slope.', 'number_systems_and_properties', '["Find the unit rate for 180 miles in 3 hours.", "Determine the price per ounce for 12 ounces costing $3.", "Identify the unit rate represented by 45 pages in 5 minutes."]'::jsonb, 'approved', 'in_depth', 'topic', 'percent_and_proportional_number_structure')
ON CONFLICT (id) DO NOTHING;

-- ─── real_number_order_and_comparison topics ──────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('number_line_location', 'Number-line location', 'Number-line location', 'Real numbers can be represented as positions on a number line. This includes placing integers, fractions, decimals, and approximate irrational values.', 'number_systems_and_properties', '["Locate -3.5 on a number line.", "Identify the point that represents 7/4.", "Place sqrt(5) between two consecutive integers."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_order_and_comparison'),
('ordering_positive_rational_numbers', 'Ordering positive rational numbers', 'Ordering positive rational numbers', 'Positive fractions, decimals, and percents can be compared by converting to a common representation or using common denominators.', 'number_systems_and_properties', '["Order 2/3, 0.7, and 65% from least to greatest.", "Compare 5/8 and 0.62.", "Identify the largest number among 0.4, 3/7, and 45%."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_order_and_comparison'),
('ordering_negative_numbers', 'Ordering negative numbers', 'Ordering negative numbers', 'Negative numbers farther left on the number line are smaller, even if their absolute values are larger. This addresses common sign-order misconceptions.', 'number_systems_and_properties', '["Order -2, -7, and -4 from least to greatest.", "Compare -0.3 and -1/4.", "Identify the greatest number among -8, -5.6, and -6."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_order_and_comparison'),
('ordering_mixed_real_numbers', 'Ordering mixed real-number forms', 'Ordering mixed real-number forms', 'Real numbers in different forms can be ordered by using decimal approximations, benchmarks, or exact comparisons.', 'number_systems_and_properties', '["Order -1/2, 0.4, sqrt(2), and -0.75 from least to greatest.", "Compare sqrt(10) and 3.2.", "Identify the smallest number among 5/3, 1.6, and sqrt(3)."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_order_and_comparison'),
('benchmark_fraction_comparisons', 'Benchmark fraction comparisons', 'Benchmark fraction comparisons', 'Fractions can be compared using benchmarks such as 0, 1/2, and 1. This is distinct from common-denominator computation.', 'number_systems_and_properties', '["Determine whether 5/9 is greater than or less than 1/2.", "Identify which fraction is closest to 1: 7/8, 4/5, or 9/10.", "Compare 3/11 and 6/13 using benchmark values."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_order_and_comparison'),
('integer_bounds_for_irrational_numbers', 'Integer bounds for irrational numbers', 'Integer bounds for irrational numbers', 'Irrational values such as square roots can be bounded between consecutive integers using nearby perfect squares.', 'number_systems_and_properties', '["Place sqrt(30) between two consecutive integers.", "Identify the integer bounds for sqrt(70).", "Determine whether sqrt(15) is between 3 and 4 or between 4 and 5."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_order_and_comparison'),
('inequality_symbols_numeric_comparisons', 'Inequality symbols in numeric comparisons', 'Inequality symbols in numeric comparisons', 'The symbols <, >, ≤, and ≥ describe order relationships between numbers. This topic is numeric comparison only, not solving inequalities.', 'number_systems_and_properties', '["Insert the correct inequality symbol between -4 and -1.", "Compare 3/5 and 0.62 using <, >, or =.", "Identify which inequality correctly compares sqrt(8) and 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_order_and_comparison'),
('trichotomy_property_real_numbers', 'Trichotomy property of real numbers', 'Trichotomy property of real numbers', 'For any two real numbers, exactly one of three relationships is true: less than, equal to, or greater than. This is a foundational order property.', 'number_systems_and_properties', '["Identify the true relationship between 7/8 and 0.875.", "Determine which one of <, =, or > applies to -3 and -5.", "Classify the comparison between sqrt(16) and 4."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_order_and_comparison'),
('transitive_property_of_order', 'Transitive property of order', 'Transitive property of order', 'If one number is less than a second and the second is less than a third, then the first is less than the third. This supports chained numeric comparisons.', 'number_systems_and_properties', '["Use 2 < 5 and 5 < 9 to identify the relationship between 2 and 9.", "Determine the conclusion from -6 < -2 and -2 < 4.", "Identify the missing comparison in a valid chain of inequalities."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_order_and_comparison')
ON CONFLICT (id) DO NOTHING;

-- ─── real_number_operation_properties topics ──────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('commutative_property_addition', 'Commutative property of addition', 'Commutative property of addition', 'Changing the order of addends does not change a sum. This property applies to addition, not subtraction.', 'number_systems_and_properties', '["Identify the property shown by 4 + 9 = 9 + 4.", "Determine whether -3 + 8 = 8 + -3 uses commutativity.", "Select the expression equivalent to 12 + 5 by the commutative property of addition."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('commutative_property_multiplication', 'Commutative property of multiplication', 'Commutative property of multiplication', 'Changing the order of factors does not change a product. This property applies to multiplication, not division.', 'number_systems_and_properties', '["Identify the property shown by 6 × 11 = 11 × 6.", "Determine whether -2 × 9 = 9 × -2 uses commutativity.", "Select the expression equivalent to 3 × 14 by the commutative property of multiplication."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('noncommutativity_subtraction_division', 'Noncommutativity of subtraction and division', 'Noncommutativity of subtraction and division', 'Changing the order in subtraction or division usually changes the result. This prevents overgeneralizing commutativity.', 'number_systems_and_properties', '["Determine whether 9 - 4 equals 4 - 9.", "Compare 12 ÷ 3 and 3 ÷ 12.", "Identify which operation is not commutative: addition, multiplication, or subtraction."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('associative_property_addition', 'Associative property of addition', 'Associative property of addition', 'Changing the grouping of addends does not change a sum. This property applies when the operation remains addition throughout.', 'number_systems_and_properties', '["Identify the property shown by (2 + 5) + 8 = 2 + (5 + 8).", "Determine whether (-3 + 7) + 4 = -3 + (7 + 4) uses associativity.", "Select the equivalent regrouping of (10 + 6) + 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('associative_property_multiplication', 'Associative property of multiplication', 'Associative property of multiplication', 'Changing the grouping of factors does not change a product. This property applies when the operation remains multiplication throughout.', 'number_systems_and_properties', '["Identify the property shown by (3 × 4) × 5 = 3 × (4 × 5).", "Determine whether (-2 × 6) × 7 = -2 × (6 × 7) uses associativity.", "Select the equivalent regrouping of (8 × 9) × 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('nonassociativity_subtraction_division', 'Nonassociativity of subtraction and division', 'Nonassociativity of subtraction and division', 'Changing grouping in subtraction or division usually changes the result. This prevents overgeneralizing associativity.', 'number_systems_and_properties', '["Compare (10 - 4) - 2 and 10 - (4 - 2).", "Determine whether (24 ÷ 6) ÷ 2 equals 24 ÷ (6 ÷ 2).", "Identify which operations are not associative."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('distributive_property_numeric', 'Distributive property with numbers', 'Distributive property with numbers', 'Multiplication distributes over addition or subtraction, connecting a product outside parentheses to each term inside. This is numeric only, not algebraic distribution with variables.', 'number_systems_and_properties', '["Identify the property shown by 3(4 + 5) = 3 × 4 + 3 × 5.", "Rewrite 7(10 - 2) using the distributive property.", "Determine which expression is equivalent to 5(8 + 6)."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('additive_identity', 'Additive identity', 'Additive identity', 'Adding 0 to a number leaves the number unchanged. The additive identity is 0.', 'number_systems_and_properties', '["Identify the additive identity in 14 + 0 = 14.", "Determine the missing number in -8 + __ = -8.", "Select the value that leaves any number unchanged under addition."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('multiplicative_identity', 'Multiplicative identity', 'Multiplicative identity', 'Multiplying by 1 leaves a number unchanged. The multiplicative identity is 1.', 'number_systems_and_properties', '["Identify the multiplicative identity in 23 × 1 = 23.", "Determine the missing number in -5 × __ = -5.", "Select the value that leaves any number unchanged under multiplication."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('additive_inverse_property', 'Additive inverse property', 'Additive inverse property', 'A number plus its additive inverse equals 0. Additive inverses are opposite numbers.', 'number_systems_and_properties', '["Identify the property shown by 12 + (-12) = 0.", "Determine the missing number in -9 + __ = 0.", "Select the additive inverse of 4/5."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('multiplicative_inverse_property', 'Multiplicative inverse property', 'Multiplicative inverse property', 'A nonzero number times its reciprocal equals 1. This is the property form of reciprocal relationships.', 'number_systems_and_properties', '["Identify the property shown by 5 × 1/5 = 1.", "Determine the missing number in -3/7 × __ = 1.", "Find the reciprocal of -0.25."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('zero_multiplication_property', 'Zero multiplication property', 'Zero multiplication property', 'Any real number multiplied by 0 equals 0. This is numeric zero behavior, not the zero product property for solving equations.', 'number_systems_and_properties', '["Find the value of 0 × -37.", "Identify the property shown by 81 × 0 = 0.", "Determine the result of multiplying any real number by 0."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('division_by_zero_undefined', 'Division by zero is undefined', 'Division by zero is undefined', 'A number divided by 0 is undefined because no real number multiplied by 0 can produce a nonzero dividend.', 'number_systems_and_properties', '["Identify why 5/0 is undefined.", "Determine whether -12 ÷ 0 has a real-number value.", "Classify 0/0 as a valid real-number quotient or undefined."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('zero_divided_by_nonzero_number', 'Zero divided by a nonzero number', 'Zero divided by a nonzero number', 'Zero divided by any nonzero number equals 0. This is distinct from division by zero.', 'number_systems_and_properties', '["Find the value of 0/9.", "Determine whether 0/(-4) equals 0 or is undefined.", "Identify the quotient of 0 divided by 3.7."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('closure_properties_real_numbers', 'Closure properties of real numbers', 'Closure properties of real numbers', 'The real numbers are closed under addition, subtraction, and multiplication, and under division by nonzero real numbers. This focuses on whether operations stay inside the real numbers.', 'number_systems_and_properties', '["Determine whether the sum of two real numbers is always real.", "Identify whether dividing a real number by a nonzero real number gives a real number.", "Classify which basic operations keep results within the real numbers."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('closure_properties_integers', 'Closure properties of integers', 'Closure properties of integers', 'Integers are closed under addition, subtraction, and multiplication, but not division. This separates integer structure from rational-number closure.', 'number_systems_and_properties', '["Determine whether the difference of two integers is always an integer.", "Identify why 3 ÷ 2 shows integers are not closed under division.", "Classify which operations keep integer results guaranteed."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('closure_properties_rational_numbers', 'Closure properties of rational numbers', 'Closure properties of rational numbers', 'Rational numbers are closed under addition, subtraction, multiplication, and division by nonzero rational numbers. This excludes division by 0.', 'number_systems_and_properties', '["Determine whether the product of two rational numbers is always rational.", "Identify whether 2/3 ÷ 5/7 must be rational.", "Classify which operations preserve rational-number membership."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties'),
('irrational_number_nonclosure', 'Nonclosure patterns of irrational numbers', 'Nonclosure patterns of irrational numbers', 'Irrational numbers are not closed under addition, subtraction, multiplication, or division because results can be rational or irrational depending on the numbers.', 'number_systems_and_properties', '["Identify why sqrt(2) + (-sqrt(2)) shows irrational numbers are not closed under addition.", "Determine whether sqrt(2) × sqrt(2) is rational or irrational.", "Classify whether the sum of two irrational numbers is always irrational."]'::jsonb, 'approved', 'in_depth', 'topic', 'real_number_operation_properties')
ON CONFLICT (id) DO NOTHING;

-- ─── numeric_expression_structure topics ──────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('operation_precedence_multiplication_division', 'Precedence of multiplication and division', 'Precedence of multiplication and division', 'Multiplication and division are performed before addition and subtraction unless grouping symbols indicate otherwise. This is numeric order of operations.', 'number_systems_and_properties', '["Find the value of 7 + 3 × 4.", "Determine the value of 18 - 12 ÷ 3.", "Identify which operation happens first in 5 + 6 × 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'numeric_expression_structure'),
('left_to_right_same_precedence_operations', 'Left-to-right order for same-precedence operations', 'Left-to-right order for same-precedence operations', 'Operations with the same precedence, such as multiplication/division or addition/subtraction, are evaluated from left to right.', 'number_systems_and_properties', '["Find the value of 24 ÷ 6 × 2.", "Determine the value of 10 - 3 + 5.", "Identify the first operation in 18 ÷ 3 × 4."]'::jsonb, 'approved', 'in_depth', 'topic', 'numeric_expression_structure'),
('parentheses_and_grouping_symbols', 'Parentheses and grouping symbols', 'Parentheses and grouping symbols', 'Grouping symbols indicate which part of a numeric expression is handled as a unit before interacting with the rest of the expression.', 'number_systems_and_properties', '["Find the value of 4(3 + 7).", "Determine the value of (18 - 6) ÷ 3.", "Identify the grouped quantity in 5[2 + (9 - 4)]."]'::jsonb, 'approved', 'in_depth', 'topic', 'numeric_expression_structure'),
('nested_grouping_symbols', 'Nested grouping symbols', 'Nested grouping symbols', 'Nested grouping symbols require working from the innermost group outward. This focuses on numeric expressions with multiple levels of grouping.', 'number_systems_and_properties', '["Find the value of 2[5 + (9 - 3)].", "Determine the value of 30 ÷ [2(4 + 1)].", "Identify the innermost operation in 7 - [3 + (8 - 5)]."]'::jsonb, 'approved', 'in_depth', 'topic', 'numeric_expression_structure'),
('fraction_bar_as_grouping', 'Fraction bar as grouping', 'Fraction bar as grouping', 'A fraction bar groups the entire numerator and denominator. This is a structural interpretation issue in numeric expressions.', 'number_systems_and_properties', '["Find the value of (8 + 4)/(3 + 1).", "Determine which expression matches a fraction with numerator 10 - 6 and denominator 2.", "Identify the grouped numerator in (5 + 7)/4."]'::jsonb, 'approved', 'in_depth', 'topic', 'numeric_expression_structure'),
('absolute_value_bars_as_grouping', 'Absolute value bars as grouping', 'Absolute value bars as grouping', 'Absolute value bars group the expression inside them before taking distance from zero. This is numeric absolute value structure, not absolute value equations.', 'number_systems_and_properties', '["Find the value of |3 - 9|.", "Determine the value of |-4 + 10|.", "Identify the expression grouped inside |8 - 11|."]'::jsonb, 'approved', 'in_depth', 'topic', 'numeric_expression_structure'),
('numeric_exponent_precedence', 'Numeric exponent precedence', 'Numeric exponent precedence', 'Exponents are evaluated before multiplication, division, addition, and subtraction unless grouping changes the structure. This covers order of operations only, not exponent laws.', 'number_systems_and_properties', '["Find the value of 2 + 3^2.", "Determine the value of 4 × 2^3.", "Identify which operation happens first in 7 - 2^2."]'::jsonb, 'approved', 'in_depth', 'topic', 'numeric_expression_structure'),
('negative_base_parentheses', 'Negative bases and parentheses', 'Negative bases and parentheses', 'Parentheses determine whether a negative sign is part of an exponent''s base. This is numeric expression structure, not general exponent rules.', 'number_systems_and_properties', '["Compare -3^2 and (-3)^2.", "Determine the value of (-2)^4.", "Identify whether the base is negative in -5^2."]'::jsonb, 'approved', 'in_depth', 'topic', 'numeric_expression_structure')
ON CONFLICT (id) DO NOTHING;

-- ─── approximation_estimation_and_bounds topics ───────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('rounding_to_place_value', 'Rounding to place value', 'Rounding to place value', 'A number can be approximated to a specified place value using the digit to the right of that place. This covers decimal and whole-number rounding.', 'number_systems_and_properties', '["Round 48.267 to the nearest tenth.", "Round 6,849 to the nearest hundred.", "Identify 0.0396 rounded to the nearest thousandth."]'::jsonb, 'approved', 'in_depth', 'topic', 'approximation_estimation_and_bounds'),
('truncation_vs_rounding', 'Truncation versus rounding', 'Truncation versus rounding', 'Truncation cuts off digits after a specified place, while rounding may increase the final kept digit. This distinction affects approximate numeric values.', 'number_systems_and_properties', '["Distinguish 3.146 truncated to two decimals from 3.146 rounded to two decimals.", "Identify whether 7.89 to 7.8 is truncation or rounding.", "Determine the truncated value of 0.4567 to the hundredths place."]'::jsonb, 'approved', 'in_depth', 'topic', 'approximation_estimation_and_bounds'),
('compatible_number_estimation', 'Compatible-number estimation', 'Compatible-number estimation', 'Compatible numbers are nearby values chosen to make mental arithmetic easier. This focuses on estimation rather than exact calculation.', 'number_systems_and_properties', '["Estimate 198 + 403 using compatible numbers.", "Estimate 51 × 19 using nearby easy numbers.", "Identify a compatible-number estimate for 602 ÷ 29."]'::jsonb, 'approved', 'in_depth', 'topic', 'approximation_estimation_and_bounds'),
('bounds_from_rounded_numbers', 'Bounds from rounded numbers', 'Bounds from rounded numbers', 'A rounded value represents an interval of possible original values. This topic focuses on lower and upper bounds created by rounding.', 'number_systems_and_properties', '["Determine the possible original values for a number rounded to 8.4.", "Identify the lower and upper bounds for 120 rounded to the nearest ten.", "Find the interval of values that round to 3.75 to the nearest hundredth."]'::jsonb, 'approved', 'in_depth', 'topic', 'approximation_estimation_and_bounds'),
('order_of_magnitude_estimation', 'Order-of-magnitude estimation', 'Order-of-magnitude estimation', 'Order of magnitude describes the approximate size of a number by powers of 10. This is estimation-scale reasoning, not exponent-law manipulation.', 'number_systems_and_properties', '["Identify the order of magnitude of 48,000.", "Determine whether 0.006 is closer to 10^-2 or 10^-3.", "Classify 7.2 × 10^5 by order of magnitude."]'::jsonb, 'approved', 'in_depth', 'topic', 'approximation_estimation_and_bounds'),
('reasonableness_checks_numeric_results', 'Reasonableness checks for numeric results', 'Reasonableness checks for numeric results', 'A numeric result can be checked by estimating size, sign, and magnitude. This helps detect arithmetic results that are impossible or unlikely.', 'number_systems_and_properties', '["Identify whether 49 × 21 = 10,029 is reasonable.", "Determine whether -8 + 3 should be positive or negative.", "Estimate whether 19.8% of 50 should be close to 1, 10, or 100."]'::jsonb, 'approved', 'in_depth', 'topic', 'approximation_estimation_and_bounds')
ON CONFLICT (id) DO NOTHING;
