-- Category
INSERT INTO learn_categories (id, name, description, order_index)
VALUES ('algebraic_expressions', 'Algebraic Expressions', 'Structure, evaluation, simplification, and translation of algebraic expressions.', 2)
ON CONFLICT (id) DO NOTHING;

-- ─── Umbrella keywords ────────────────────────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('algebraic_expression_structure', 'Algebraic Expression Structure', 'Algebraic Expression Structure', 'Recognizing the parts, notation, and structure of algebraic expressions without solving equations or analyzing functions.', 'algebraic_expressions', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('substitution_into_expressions', 'Substitution into Expressions', 'Substitution into Expressions', 'Replacing variables with given values or expressions and interpreting the resulting algebraic structure without solving for unknowns.', 'algebraic_expressions', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('like_terms_and_term_collection', 'Like Terms and Term Collection', 'Like Terms and Term Collection', 'Recognizing and combining terms with matching variable parts while preserving unlike terms.', 'algebraic_expressions', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('distribution_and_expansion', 'Distribution and Expansion', 'Distribution and Expansion', 'Using multiplication over addition or subtraction to rewrite grouped algebraic expressions without polynomial factoring or advanced polynomial products.', 'algebraic_expressions', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('equivalent_expression_properties', 'Equivalent Expression Properties', 'Equivalent Expression Properties', 'Recognizing and justifying when algebraic expressions have the same value for all allowed inputs using arithmetic properties and structural transformations.', 'algebraic_expressions', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('verbal_to_symbolic_expression_structure', 'Verbal-to-Symbolic Expression Structure', 'Verbal-to-Symbolic Expression Structure', 'Translating mathematical phrases into algebraic expressions while preserving operation order, grouping, and quantity relationships.', 'algebraic_expressions', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('algebraic_expression_order_and_grouping', 'Algebraic Expression Order and Grouping', 'Algebraic Expression Order and Grouping', 'Interpreting operation order, grouping, negative signs, and powers in algebraic expressions without solving equations or applying advanced exponent rules.', 'algebraic_expressions', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL)
ON CONFLICT (id) DO NOTHING;

-- ─── algebraic_expression_structure topics ────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('variables_as_quantities', 'Variables as quantities', 'Variables as quantities', 'A variable represents an unknown, changing, or unspecified quantity inside an expression. This focuses on interpreting the role of a symbol before manipulating it.', 'algebraic_expressions', '["Identify the variable in the expression 4x + 7.", "Determine what symbol represents the unknown quantity in 12 - n.", "Classify x as a variable in the expression 3x - 5."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure'),
('constants_in_expressions', 'Constants in expressions', 'Constants in expressions', 'A constant is a fixed numerical value in an expression. This distinguishes standalone numbers from variable terms.', 'algebraic_expressions', '["Identify the constant term in 5x + 9.", "Determine which part of 3a - 11 does not change with a.", "Select the constants in the expression 4x + 2y - 8."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure'),
('coefficients_of_variable_terms', 'Coefficients of variable terms', 'Coefficients of variable terms', 'A coefficient is the numerical factor multiplying a variable term. This includes positive, negative, fractional, decimal, and implied coefficients.', 'algebraic_expressions', '["Identify the coefficient of x in -7x.", "Determine the coefficient of y in y + 4.", "Find the coefficient of a in -a - 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure'),
('implied_coefficient_one', 'Implied coefficient of 1', 'Implied coefficient of 1', 'A variable written without a visible coefficient has coefficient 1. This targets expressions like x, y, and ab.', 'algebraic_expressions', '["Identify the coefficient of x in x + 3.", "Determine the coefficient of ab in ab - 5.", "Rewrite m with its implied numerical coefficient."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure'),
('implied_coefficient_negative_one', 'Implied coefficient of -1', 'Implied coefficient of -1', 'A variable term with only a negative sign has coefficient -1. This targets expressions like -x and -ab.', 'algebraic_expressions', '["Identify the coefficient of x in -x + 4.", "Determine the coefficient of mn in -mn.", "Rewrite -a with its implied numerical coefficient."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure'),
('terms_in_algebraic_expressions', 'Terms in algebraic expressions', 'Terms in algebraic expressions', 'Terms are parts of an expression separated by addition or subtraction at the top level. This focuses on parsing expression structure correctly.', 'algebraic_expressions', '["Identify the terms in 3x + 5y - 8.", "Determine how many terms are in 7a - 4b + 2.", "List the terms of -x + 6 - 2y."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure'),
('term_signs_in_expressions', 'Term signs in expressions', 'Term signs in expressions', 'A term includes the sign directly before it. This helps distinguish 4x - 7y as the terms 4x and -7y.', 'algebraic_expressions', '["Identify the signed terms in 8x - 3y + 4.", "Determine whether 5 is positive or negative in x - 5.", "List the terms of -2a + b - 9 with their signs."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure'),
('factors_in_algebraic_terms', 'Factors in algebraic terms', 'Factors in algebraic terms', 'Factors are quantities multiplied together inside a term. This focuses on recognizing multiplicative structure within one term.', 'algebraic_expressions', '["Identify the factors in 6xy.", "Determine the numerical and variable factors in -4ab.", "List the factors of 3mn in the expression 3mn + 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure'),
('single_variable_terms', 'Single-variable terms', 'Single-variable terms', 'A single-variable term contains one variable type, possibly with a coefficient or power. This distinguishes terms like 5x from terms involving multiple variables.', 'algebraic_expressions', '["Identify the single-variable terms in 4x + 3xy - 2y.", "Classify 7a as a single-variable term.", "Determine whether -5m is a single-variable term."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure'),
('multi_variable_terms', 'Multi-variable terms', 'Multi-variable terms', 'A multi-variable term contains more than one variable factor in the same term. This targets structures like xy, 3ab, and -5mn.', 'algebraic_expressions', '["Identify the multi-variable term in 4x + 3xy - 2.", "Classify -6ab as a term with multiple variables.", "Determine whether 9mn and 9m are the same type of term."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure'),
('monomial_term_structure', 'Monomial term structure', 'Monomial term structure', 'A monomial term is one algebraic term made from a coefficient and variable factors. This is structural recognition only, not polynomial operations.', 'algebraic_expressions', '["Classify 8x as a monomial term.", "Identify which expression is a single monomial term: 3a, 3a + 1, or a - b.", "Determine whether -5xy is one term or multiple terms."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure'),
('expression_vs_equation_boundary', 'Expression versus equation', 'Expression versus equation', 'An expression has no equals sign, while an equation states that two expressions are equal. This separates expression structure from later equation solving.', 'algebraic_expressions', '["Classify 3x + 7 as an expression or an equation.", "Identify whether 2a - 5 = 9 is an expression or an equation.", "Determine which item has no equals sign: x + 4 or x + 4 = 10."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure'),
('expression_vs_term_boundary', 'Expression versus term', 'Expression versus term', 'A term is one additive part of an expression, while an expression may contain one or many terms. This helps distinguish local term structure from the whole expression.', 'algebraic_expressions', '["Classify 4x as a term or a multi-term expression.", "Determine whether 3a - 2 contains one term or two terms.", "Identify the expression that consists of exactly one term."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure'),
('algebraic_operation_symbols', 'Operation symbols in expressions', 'Operation symbols in expressions', 'Algebraic expressions use symbols for addition, subtraction, multiplication, division, powers, and grouping. This focuses on reading the operation structure of an expression.', 'algebraic_expressions', '["Identify the operation between 4 and x in 4x.", "Determine which operation is shown in x/5.", "Classify the main operation in a + 7."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure'),
('implied_multiplication_notation', 'Implied multiplication notation', 'Implied multiplication notation', 'Multiplication can be shown without a multiplication symbol, such as 5x, 3(a + b), or ab. This focuses on reading compact algebraic notation.', 'algebraic_expressions', '["Rewrite 7x using an explicit multiplication symbol.", "Identify the multiplication in 4(a + 2).", "Determine whether ab means a + b or a times b."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure'),
('algebraic_grouping_symbols', 'Grouping symbols in algebraic expressions', 'Grouping symbols in algebraic expressions', 'Parentheses, brackets, and braces group parts of an algebraic expression so they act as a unit. This is expression structure, not equation solving.', 'algebraic_expressions', '["Identify the grouped quantity in 3(x + 5).", "Determine which part of 4[a - 2] is inside the brackets.", "Classify the grouping symbols used in 2{m + 7}."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure'),
('fraction_bar_grouping_with_variables', 'Fraction bar grouping with variables', 'Fraction bar grouping with variables', 'A fraction bar groups the entire numerator and denominator of an algebraic expression. This targets parsing, not rational-expression simplification.', 'algebraic_expressions', '["Identify the numerator in (x + 3)/5.", "Determine whether x + 1/2 means (x + 1)/2 or x + (1/2).", "Rewrite a fraction with numerator 2x - 7 and denominator 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_structure')
ON CONFLICT (id) DO NOTHING;

-- ─── substitution_into_expressions topics ────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('single_variable_numeric_substitution', 'Single-variable numeric substitution', 'Single-variable numeric substitution', 'A given numeric value replaces one variable throughout an expression. This is the basic structure behind evaluating an expression at a value.', 'algebraic_expressions', '["Evaluate 3x + 5 when x = 4.", "Find the value of 10 - 2a when a = 3.", "Determine the result of 7m when m = 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_into_expressions'),
('multiple_occurrences_same_variable_substitution', 'Multiple occurrences of the same variable', 'Multiple occurrences of the same variable', 'When a variable appears more than once, the same replacement value must be used every time. This targets consistency across repeated variables.', 'algebraic_expressions', '["Evaluate x + 3x when x = 5.", "Find the value of 2a - a + 7 when a = -4.", "Determine the result of b + b + 10 when b = 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_into_expressions'),
('multi_variable_numeric_substitution', 'Multi-variable numeric substitution', 'Multi-variable numeric substitution', 'Different variables in the same expression are replaced by their corresponding given values. This focuses on matching each value to the correct variable.', 'algebraic_expressions', '["Evaluate 3x + 2y when x = 4 and y = 5.", "Find the value of ab - c when a = 2, b = 7, and c = 3.", "Determine the result of 5m - n when m = -1 and n = 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_into_expressions'),
('substitution_of_negative_values', 'Substitution of negative values', 'Substitution of negative values', 'Negative replacement values must be inserted carefully, often using parentheses to preserve signs. This targets sign errors during substitution.', 'algebraic_expressions', '["Evaluate 4x + 1 when x = -3.", "Find the value of 2a - 5 when a = -6.", "Determine the result of -x + 8 when x = -2."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_into_expressions'),
('substitution_of_zero', 'Substitution of zero', 'Substitution of zero', 'A zero replacement value can eliminate variable terms by multiplication but does not eliminate constants. This targets common zero-substitution mistakes.', 'algebraic_expressions', '["Evaluate 7x + 4 when x = 0.", "Find the value of 3a - 9 when a = 0.", "Determine which terms remain in 5m + 2n - 1 when m = 0 and n = 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_into_expressions'),
('substitution_of_fraction_values', 'Substitution of fraction values', 'Substitution of fraction values', 'Fraction values can replace variables, requiring careful multiplication and operation order. This is substitution into expressions, not fraction arithmetic as a standalone topic.', 'algebraic_expressions', '["Evaluate 6x + 1 when x = 1/3.", "Find the value of 4a - 2 when a = 5/2.", "Determine the result of 3m + 7 when m = -2/3."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_into_expressions'),
('substitution_of_decimal_values', 'Substitution of decimal values', 'Substitution of decimal values', 'Decimal values can replace variables, requiring place-value arithmetic within an algebraic expression. This is distinct from decimal arithmetic alone.', 'algebraic_expressions', '["Evaluate 10x - 4 when x = 0.6.", "Find the value of 3a + 2.5 when a = 1.2.", "Determine the result of 8m when m = 0.125."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_into_expressions'),
('parentheses_for_substitution', 'Parentheses during substitution', 'Parentheses during substitution', 'Replacement values should be inserted with parentheses when signs, products, or powers could otherwise be misread. This focuses on preserving expression structure.', 'algebraic_expressions', '["Rewrite 3x + 2 after substituting x = -5 using parentheses.", "Insert x = -2 into 4x - 1 with correct grouping.", "Show the substitution step for 6 - x when x = -7."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_into_expressions'),
('order_of_operations_after_substitution', 'Order of operations after substitution', 'Order of operations after substitution', 'After variables are replaced, the resulting numeric expression must be evaluated using the correct operation order. This connects substitution to expression structure.', 'algebraic_expressions', '["Evaluate 2x + 3y when x = 4 and y = 5.", "Find the value of 5(a - 2) when a = 9.", "Determine the result of 12 - 3b when b = 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_into_expressions'),
('substitution_into_power_terms', 'Substitution into power terms', 'Substitution into power terms', 'When substituting into a term with a power, the replacement value becomes the base of that power if grouped correctly. This is expression substitution, not exponent-law manipulation.', 'algebraic_expressions', '["Evaluate x^2 when x = -4.", "Find the value of 2a^2 when a = 3.", "Determine the result of -m^2 when m = -5."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_into_expressions'),
('substitution_into_grouped_expressions', 'Substitution into grouped expressions', 'Substitution into grouped expressions', 'Substitution inside expressions with parentheses requires preserving the grouped quantity before applying outside operations.', 'algebraic_expressions', '["Evaluate 3(x + 4) when x = 2.", "Find the value of 5(a - 1) when a = -3.", "Determine the result of 2(7 - m) when m = 9."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_into_expressions'),
('substitution_of_expression_for_variable', 'Substituting an expression for a variable', 'Substituting an expression for a variable', 'A variable can be replaced by an entire expression rather than a single number. This focuses on expression replacement, not function composition.', 'algebraic_expressions', '["Replace x with a + 2 in 3x - 5.", "Rewrite 4y + 1 after substituting y = m - 6.", "Substitute 2n + 3 for a in 5a."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_into_expressions'),
('formula_substitution', 'Formula substitution', 'Formula substitution', 'Given values can be inserted into a formula containing several variables. This focuses on using a formula as an algebraic expression, not rearranging it.', 'algebraic_expressions', '["Evaluate P = 2l + 2w when l = 8 and w = 5.", "Find the value of A = bh/2 when b = 10 and h = 6.", "Determine C = 2πr when r = 4."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_into_expressions')
ON CONFLICT (id) DO NOTHING;

-- ─── like_terms_and_term_collection topics (zero_coefficient_variable_terms removed) ──
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('like_terms_same_variable_part', 'Like terms with the same variable part', 'Like terms with the same variable part', 'Like terms have exactly the same variable part, including the same variables and powers. Only their coefficients may differ.', 'algebraic_expressions', '["Identify the like terms in 4x + 7x - 3.", "Determine whether 5a and -2a are like terms.", "Select the terms like 3mn from 7mn, 3m, and -mn."]'::jsonb, 'approved', 'in_depth', 'topic', 'like_terms_and_term_collection'),
('unlike_terms_different_variables', 'Unlike terms with different variables', 'Unlike terms with different variables', 'Terms with different variables are unlike terms and cannot be combined by addition or subtraction. This targets errors like combining x and y terms.', 'algebraic_expressions', '["Determine whether 4x and 4y are like terms.", "Identify the unlike terms in 6a + 2b + 9a.", "Classify 3m and 3n as like or unlike terms."]'::jsonb, 'approved', 'in_depth', 'topic', 'like_terms_and_term_collection'),
('unlike_terms_different_powers', 'Unlike terms with different powers', 'Unlike terms with different powers', 'Terms with the same variable but different powers are unlike terms. This prevents combining terms such as x and x^2.', 'algebraic_expressions', '["Determine whether 7x and 7x^2 are like terms.", "Identify why 3a^2 and 5a cannot be combined.", "Classify 4m^3 and -2m^2 as like or unlike terms."]'::jsonb, 'approved', 'in_depth', 'topic', 'like_terms_and_term_collection'),
('unlike_terms_different_variable_combinations', 'Unlike terms with different variable combinations', 'Unlike terms with different variable combinations', 'Terms with different combinations of variables are unlike even if they share some variables. This targets distinctions like xy versus x or ab versus ac.', 'algebraic_expressions', '["Determine whether 5xy and 5x are like terms.", "Identify which term is like 3ab: 7ab, 7a, or 7ac.", "Classify -2mn and 4m as like or unlike terms."]'::jsonb, 'approved', 'in_depth', 'topic', 'like_terms_and_term_collection'),
('coefficient_combination_integer_coefficients', 'Integer coefficient combination', 'Integer coefficient combination', 'Like terms with integer coefficients are combined by adding or subtracting their coefficients while keeping the variable part unchanged.', 'algebraic_expressions', '["Combine 6x - 2x.", "Rewrite 9a + 4a - 7a as one like term.", "Determine the coefficient of x in 5x + 8x."]'::jsonb, 'approved', 'in_depth', 'topic', 'like_terms_and_term_collection'),
('coefficient_combination_negative_coefficients', 'Negative coefficient combination', 'Negative coefficient combination', 'Like terms with negative coefficients require signed-number addition of coefficients. This targets sign errors when collecting terms.', 'algebraic_expressions', '["Combine -4x - 9x.", "Rewrite -7a + 2a as one like term.", "Determine the coefficient of m in -3m + 8m - 10m."]'::jsonb, 'approved', 'in_depth', 'topic', 'like_terms_and_term_collection'),
('coefficient_combination_fraction_coefficients', 'Fraction coefficient combination', 'Fraction coefficient combination', 'Like terms with fraction coefficients are combined by adding or subtracting the fractional coefficients. The variable part stays unchanged.', 'algebraic_expressions', '["Combine 1/2 x + 3/2 x.", "Rewrite 5/6 a - 1/3 a as one like term.", "Determine the coefficient of y in 3/4 y + 1/8 y."]'::jsonb, 'approved', 'in_depth', 'topic', 'like_terms_and_term_collection'),
('coefficient_combination_decimal_coefficients', 'Decimal coefficient combination', 'Decimal coefficient combination', 'Like terms with decimal coefficients are combined by decimal addition or subtraction of coefficients. This is term collection, not decimal arithmetic alone.', 'algebraic_expressions', '["Combine 2.5x + 1.8x.", "Rewrite 7.2a - 3.9a as one like term.", "Determine the coefficient of m in 0.6m + 4.1m."]'::jsonb, 'approved', 'in_depth', 'topic', 'like_terms_and_term_collection'),
('constant_term_collection', 'Constant term collection', 'Constant term collection', 'Constant terms are like terms with no variable part and can be combined with each other. They cannot be combined with variable terms.', 'algebraic_expressions', '["Combine the constants in 4x + 7 - 2.", "Rewrite 9 + 3a - 11 by collecting constants.", "Identify the constant terms in 5m - 6 + 8m + 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'like_terms_and_term_collection'),
('multi_variable_like_term_collection', 'Multi-variable like term collection', 'Multi-variable like term collection', 'Terms with the same multi-variable part can be combined by their coefficients. This targets terms like xy, ab, and mn.', 'algebraic_expressions', '["Combine 4xy + 9xy.", "Rewrite -3ab + 7ab - 2ab as one like term.", "Determine the coefficient of mn in 8mn - 5mn."]'::jsonb, 'approved', 'in_depth', 'topic', 'like_terms_and_term_collection'),
('preserving_unlike_terms', 'Preserving unlike terms', 'Preserving unlike terms', 'Unlike terms remain separate when an expression is rewritten. This targets the misconception that all visible terms should combine.', 'algebraic_expressions', '["Rewrite 3x + 4y without incorrectly combining unlike terms.", "Identify why 5a + 2b cannot become 7ab.", "Determine which terms remain separate in 6m + 4n - 2m."]'::jsonb, 'approved', 'in_depth', 'topic', 'like_terms_and_term_collection'),
('term_reordering_for_collection', 'Term reordering for collection', 'Term reordering for collection', 'Terms can be rearranged using addition properties so like terms are easier to collect. The sign of each term must move with the term.', 'algebraic_expressions', '["Reorder 4x + 3 - 2x + 9 to group like terms.", "Rewrite 7a - 5 + 2a by placing like terms together.", "Identify the correct reordering of -3m + 8 - 4m."]'::jsonb, 'approved', 'in_depth', 'topic', 'like_terms_and_term_collection'),
('additive_inverse_like_terms', 'Additive inverse like terms', 'Additive inverse like terms', 'Like terms with opposite coefficients combine to zero, eliminating the variable term entirely. This targets cancellation of terms such as 5x and -5x.', 'algebraic_expressions', '["Combine 8x - 8x.", "Determine which terms cancel in 4a + 7 - 4a.", "Rewrite 6m - 6m + 3 as a constant."]'::jsonb, 'approved', 'in_depth', 'topic', 'like_terms_and_term_collection'),
('like_terms_across_parentheses_after_group_removal', 'Like terms across removed grouping', 'Like terms across removed grouping', 'After grouping symbols are removed correctly, like terms from inside and outside the group may be collected. This is term collection after structural rewriting.', 'algebraic_expressions', '["Combine like terms in x + (3x + 5).", "Rewrite 4a + (2a - 7) by collecting like terms.", "Determine the result of m - ( -3m ) after removing the grouping correctly."]'::jsonb, 'approved', 'in_depth', 'topic', 'like_terms_and_term_collection')
ON CONFLICT (id) DO NOTHING;

-- ─── distribution_and_expansion topics ───────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('positive_integer_distribution', 'Distribution by a positive integer', 'Distribution by a positive integer', 'A positive integer outside parentheses multiplies each term inside the group. This is the basic algebraic distributive structure.', 'algebraic_expressions', '["Expand 3(x + 5).", "Rewrite 4(a - 2) without parentheses.", "Distribute 7 over m + 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'distribution_and_expansion'),
('negative_integer_distribution', 'Distribution by a negative integer', 'Distribution by a negative integer', 'A negative integer outside parentheses multiplies each inside term, changing signs according to signed multiplication. This targets common negative distribution errors.', 'algebraic_expressions', '["Expand -3(x + 4).", "Rewrite -5(a - 2) without parentheses.", "Distribute -2 over m - 7."]'::jsonb, 'approved', 'in_depth', 'topic', 'distribution_and_expansion'),
('fraction_coefficient_distribution', 'Distribution by a fraction coefficient', 'Distribution by a fraction coefficient', 'A fractional coefficient outside parentheses multiplies every term inside. This targets distribution when coefficients are not whole numbers.', 'algebraic_expressions', '["Expand 1/2(6x + 10).", "Rewrite 3/4(8a - 12) without parentheses.", "Distribute -2/3 over 9m + 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'distribution_and_expansion'),
('decimal_coefficient_distribution', 'Distribution by a decimal coefficient', 'Distribution by a decimal coefficient', 'A decimal coefficient outside parentheses multiplies each term inside the group. This combines algebraic distribution with decimal coefficient handling.', 'algebraic_expressions', '["Expand 0.5(8x + 6).", "Rewrite 1.2(a - 5) without parentheses.", "Distribute -0.4 over 10m - 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'distribution_and_expansion'),
('variable_factor_distribution', 'Distribution by a variable factor', 'Distribution by a variable factor', 'A variable factor outside parentheses multiplies each inside term. This is limited to basic monomial distribution, not full polynomial multiplication.', 'algebraic_expressions', '["Expand x(a + 3).", "Rewrite m(5 + n) without parentheses.", "Distribute y over 2x - 7."]'::jsonb, 'approved', 'in_depth', 'topic', 'distribution_and_expansion'),
('monomial_distribution_over_binomial', 'Monomial distribution over a binomial', 'Monomial distribution over a binomial', 'A single term outside parentheses multiplies both terms of a two-term expression. This includes numeric and variable monomial factors.', 'algebraic_expressions', '["Expand 4x(x + 2).", "Rewrite -3a(2a - 5) without parentheses.", "Distribute 5m over m + 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'distribution_and_expansion'),
('monomial_distribution_over_trinomial', 'Monomial distribution over a trinomial', 'Monomial distribution over a trinomial', 'A single term outside parentheses multiplies each of three terms inside the group. This is basic expansion, not polynomial factoring.', 'algebraic_expressions', '["Expand 2(x + y + 4).", "Rewrite -3(a - b + 5) without parentheses.", "Distribute 4m over 2m + n - 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'distribution_and_expansion'),
('distribution_over_subtraction', 'Distribution over subtraction', 'Distribution over subtraction', 'Distribution over subtraction requires multiplying the term after the minus sign with its sign included. This targets sign preservation inside parentheses.', 'algebraic_expressions', '["Expand 5(x - 8).", "Rewrite 2(a - b) without parentheses.", "Distribute -4 over m - 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'distribution_and_expansion'),
('negative_one_distribution', 'Distribution by -1', 'Distribution by -1', 'A negative sign outside parentheses is equivalent to multiplying every term inside by -1. This targets sign changes from group negation.', 'algebraic_expressions', '["Rewrite -(x + 7) without parentheses.", "Expand -(a - 4).", "Determine the result of applying a negative sign to m - n + 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'distribution_and_expansion'),
('subtraction_of_parenthesized_expression', 'Subtraction of a parenthesized expression', 'Subtraction of a parenthesized expression', 'Subtracting a parenthesized expression changes the sign of every term inside. This is a common source of errors in expression rewriting.', 'algebraic_expressions', '["Rewrite x - (3x + 5) without parentheses.", "Expand 7a - (2a - 9).", "Determine the signs after removing parentheses in m - (n - 4)."]'::jsonb, 'approved', 'in_depth', 'topic', 'distribution_and_expansion'),
('multiple_distribution_terms', 'Multiple separate distribution terms', 'Multiple separate distribution terms', 'An expression may require distributing across more than one grouped part before collecting terms. Each distribution is handled separately.', 'algebraic_expressions', '["Expand 2(x + 3) + 5(x - 1).", "Rewrite 4(a - 2) - 3(a + 6) without parentheses.", "Distribute both terms in 7(m + 1) + 2(m - 5)."]'::jsonb, 'approved', 'in_depth', 'topic', 'distribution_and_expansion'),
('nested_distribution', 'Nested distribution', 'Nested distribution', 'Nested grouped expressions require distributing through one grouping level at a time. This focuses on layered distribution, not solving.', 'algebraic_expressions', '["Expand 2(3x + (x - 4)).", "Rewrite 5(a + 2(b - 1)) without nested parentheses.", "Distribute through 3(2m - (m + 7))."]'::jsonb, 'approved', 'in_depth', 'topic', 'distribution_and_expansion'),
('distribution_followed_by_term_collection', 'Distribution followed by term collection', 'Distribution followed by term collection', 'After distributing, like terms may need to be collected to rewrite the expression in a cleaner equivalent form. This combines expansion with term collection.', 'algebraic_expressions', '["Rewrite 3(x + 4) + 2x by expanding and collecting terms.", "Expand and collect like terms in 5(a - 1) - 2a.", "Determine the equivalent expression for 4m + 2(m - 7)."]'::jsonb, 'approved', 'in_depth', 'topic', 'distribution_and_expansion'),
('partial_distribution_error_recognition', 'Partial distribution error recognition', 'Partial distribution error recognition', 'Distribution must apply to every term inside the group, not only the first term. This targets incomplete expansion errors.', 'algebraic_expressions', '["Identify the error in 3(x + 5) = 3x + 5.", "Determine whether 2(a - 7) = 2a - 14 is correctly distributed.", "Correct the expansion of 4(m + 6) written as 4m + 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'distribution_and_expansion'),
('distribution_sign_error_recognition', 'Distribution sign error recognition', 'Distribution sign error recognition', 'Negative distribution and subtraction of groups require sign changes on each affected term. This targets incorrect signs after expansion.', 'algebraic_expressions', '["Identify the error in -(x - 4) = -x - 4.", "Correct the expansion of -2(a + 5) written as -2a + 10.", "Determine whether x - (3x - 1) becomes x - 3x + 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'distribution_and_expansion')
ON CONFLICT (id) DO NOTHING;

-- ─── equivalent_expression_properties topics (additive_inverse_terms_in_expressions removed) ──
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('equivalent_expressions_definition', 'Equivalent expressions', 'Equivalent expressions', 'Equivalent expressions have the same value for every allowed value of the variable. This is expression comparison, not solving an equation.', 'algebraic_expressions', '["Determine whether 3x + 6 and 3(x + 2) are equivalent.", "Identify which expression is equivalent to 5a - 2a.", "Classify 2(x + 4) and 2x + 8 as equivalent or not equivalent."]'::jsonb, 'approved', 'in_depth', 'topic', 'equivalent_expression_properties'),
('equivalence_by_like_term_collection', 'Equivalence through like-term collection', 'Equivalence through like-term collection', 'Expressions can be equivalent when one form collects like terms from another. This focuses on recognizing collection as a valid rewrite.', 'algebraic_expressions', '["Identify the expression equivalent to 4x + 7x.", "Determine whether 6a - 2 + 3a and 9a - 2 are equivalent.", "Rewrite 5m + 8 - 2m as an equivalent expression."]'::jsonb, 'approved', 'in_depth', 'topic', 'equivalent_expression_properties'),
('equivalence_by_distribution', 'Equivalence through distribution', 'Equivalence through distribution', 'Expressions can be equivalent when one form is the distributed or factored structural version of another. This focuses on distribution equivalence, not polynomial factoring.', 'algebraic_expressions', '["Determine whether 4(x + 3) and 4x + 12 are equivalent.", "Identify the expression equivalent to -2(a - 5).", "Match 3m + 15 with its grouped equivalent form."]'::jsonb, 'approved', 'in_depth', 'topic', 'equivalent_expression_properties'),
('testing_equivalence_by_substitution', 'Testing equivalence by substitution', 'Testing equivalence by substitution', 'Substituting the same value into two expressions can test whether they match for that value, though one value alone does not prove full equivalence.', 'algebraic_expressions', '["Test whether 2x + 6 and 2(x + 3) give the same value when x = 4.", "Evaluate two expressions at a = -1 to compare their values.", "Determine whether x + x and x^2 match when x = 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'equivalent_expression_properties'),
('non_equivalence_from_counterexample', 'Non-equivalence from a counterexample', 'Non-equivalence from a counterexample', 'If two expressions produce different values for the same input, they are not equivalent. This uses a counterexample to reject equivalence.', 'algebraic_expressions', '["Show that x + 3 and 3x are not equivalent using x = 2.", "Find a value that makes 2a + 4 and 2(a + 4) different.", "Determine whether one counterexample is enough to show expressions are not equivalent."]'::jsonb, 'approved', 'in_depth', 'topic', 'equivalent_expression_properties'),
('coefficient_matching_in_equivalent_linear_expressions', 'Coefficient matching in equivalent linear expressions', 'Coefficient matching in equivalent linear expressions', 'Equivalent linear expressions must have matching variable coefficients and matching constant terms. This compares expression structure without solving an equation.', 'algebraic_expressions', '["Determine whether 3x + 5 and 5 + 3x have matching coefficients and constants.", "Identify the missing coefficient that makes ax + 4 equivalent to 7x + 4.", "Compare 2m - 9 and 2m + 9 by coefficient and constant structure."]'::jsonb, 'approved', 'in_depth', 'topic', 'equivalent_expression_properties'),
('commutative_property_algebraic_addition', 'Commutative property of algebraic addition', 'Commutative property of algebraic addition', 'Additive terms can be reordered without changing the value of the expression, as long as each term keeps its sign.', 'algebraic_expressions', '["Rewrite x + 7 as 7 + x.", "Identify the property shown by 3a + 5 = 5 + 3a.", "Reorder -2m + 9 using the commutative property of addition."]'::jsonb, 'approved', 'in_depth', 'topic', 'equivalent_expression_properties'),
('commutative_property_algebraic_multiplication', 'Commutative property of algebraic multiplication', 'Commutative property of algebraic multiplication', 'Factors in a product can be reordered without changing the product. This supports rewriting terms like 3x and x·3.', 'algebraic_expressions', '["Rewrite 5x as x times 5.", "Identify the property shown by ab = ba.", "Determine whether 4mn and n4m represent the same product structure."]'::jsonb, 'approved', 'in_depth', 'topic', 'equivalent_expression_properties'),
('associative_property_algebraic_addition', 'Associative property of algebraic addition', 'Associative property of algebraic addition', 'Additive grouping can change without changing a sum. This applies only when the operation remains addition among terms.', 'algebraic_expressions', '["Rewrite (x + 3) + 5 as x + (3 + 5).", "Identify the property shown by (a + b) + c = a + (b + c).", "Regroup 4m + 7 + 2 using the associative property of addition."]'::jsonb, 'approved', 'in_depth', 'topic', 'equivalent_expression_properties'),
('associative_property_algebraic_multiplication', 'Associative property of algebraic multiplication', 'Associative property of algebraic multiplication', 'Multiplicative grouping can change without changing a product. This supports regrouping factors inside algebraic terms.', 'algebraic_expressions', '["Rewrite (3x)y as 3(xy).", "Identify the property shown by (ab)c = a(bc).", "Regroup 5(mn) using the associative property of multiplication."]'::jsonb, 'approved', 'in_depth', 'topic', 'equivalent_expression_properties'),
('identity_properties_in_algebraic_expressions', 'Identity properties in algebraic expressions', 'Identity properties in algebraic expressions', 'Adding 0 or multiplying by 1 leaves an algebraic expression unchanged. This recognizes equivalent forms involving identities.', 'algebraic_expressions', '["Identify why x + 0 is equivalent to x.", "Determine whether 1(4a - 7) is equivalent to 4a - 7.", "Rewrite m times 1 + 0 without identity elements."]'::jsonb, 'approved', 'in_depth', 'topic', 'equivalent_expression_properties'),
('zero_factor_in_algebraic_expressions', 'Zero factor in algebraic expressions', 'Zero factor in algebraic expressions', 'Any algebraic factor multiplied by 0 gives 0. This is expression structure only, not solving with the zero-product property.', 'algebraic_expressions', '["Rewrite 0(x + 5).", "Determine the value of 0 times 7a.", "Identify why 0(m - 3) is equivalent to 0."]'::jsonb, 'approved', 'in_depth', 'topic', 'equivalent_expression_properties')
ON CONFLICT (id) DO NOTHING;

-- ─── verbal_to_symbolic_expression_structure topics ───────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('addition_phrase_expressions', 'Addition phrase expressions', 'Addition phrase expressions', 'Addition phrases describe sums, increases, totals, or quantities more than another quantity. This focuses on symbolic expression structure, not equation modeling.', 'algebraic_expressions', '["Write an expression for 8 more than x.", "Translate the sum of n and 12 into an algebraic expression.", "Represent a number increased by 5."]'::jsonb, 'approved', 'in_depth', 'topic', 'verbal_to_symbolic_expression_structure'),
('subtraction_phrase_expressions', 'Subtraction phrase expressions', 'Subtraction phrase expressions', 'Subtraction phrases describe differences, decreases, or quantities less than another quantity. This targets correct order in subtraction expressions.', 'algebraic_expressions', '["Write an expression for x decreased by 9.", "Translate the difference of a and 4 into an algebraic expression.", "Represent 12 less than n."]'::jsonb, 'approved', 'in_depth', 'topic', 'verbal_to_symbolic_expression_structure'),
('less_than_phrase_order', 'Less-than phrase order', 'Less-than phrase order', 'Phrases like 5 less than x reverse the order from the words, producing x - 5 rather than 5 - x. This targets a specific translation misconception.', 'algebraic_expressions', '["Write an expression for 7 less than y.", "Translate 12 less than twice a number.", "Identify the correct expression for 4 less than n."]'::jsonb, 'approved', 'in_depth', 'topic', 'verbal_to_symbolic_expression_structure'),
('more_than_phrase_order', 'More-than phrase order', 'More-than phrase order', 'Phrases like 5 more than x produce x + 5. Although addition is commutative, this skill focuses on interpreting the relationship correctly.', 'algebraic_expressions', '["Write an expression for 6 more than x.", "Translate 10 more than three times a number.", "Represent a value that is 15 more than n."]'::jsonb, 'approved', 'in_depth', 'topic', 'verbal_to_symbolic_expression_structure'),
('multiplication_phrase_expressions', 'Multiplication phrase expressions', 'Multiplication phrase expressions', 'Multiplication phrases describe products, multiples, or scaled quantities. This includes forms like 3x, ab, and 5(n + 1).', 'algebraic_expressions', '["Write an expression for the product of 6 and x.", "Translate 4 times a number into an algebraic expression.", "Represent twice the quantity n + 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'verbal_to_symbolic_expression_structure'),
('division_phrase_expressions', 'Division phrase expressions', 'Division phrase expressions', 'Division phrases describe quotients or ratios of algebraic quantities. This targets correct placement of dividend and divisor.', 'algebraic_expressions', '["Write an expression for x divided by 7.", "Translate the quotient of a and 5.", "Represent 12 divided by a number."]'::jsonb, 'approved', 'in_depth', 'topic', 'verbal_to_symbolic_expression_structure'),
('quotient_order_in_phrases', 'Quotient phrase order', 'Quotient phrase order', 'Quotient phrases require preserving which quantity is being divided by which. This targets order errors in noncommutative division.', 'algebraic_expressions', '["Write an expression for the quotient of 20 and x.", "Translate the quotient of n + 4 and 3.", "Identify the expression for 5 divided by a number."]'::jsonb, 'approved', 'in_depth', 'topic', 'verbal_to_symbolic_expression_structure'),
('grouped_sum_phrase_expressions', 'Grouped sum phrase expressions', 'Grouped sum phrase expressions', 'Phrases involving a sum as one quantity require parentheses when that sum is multiplied, divided, or otherwise treated as a unit.', 'algebraic_expressions', '["Write an expression for three times the sum of x and 4.", "Translate the sum of a and b divided by 5.", "Represent twice the quantity m plus 7."]'::jsonb, 'approved', 'in_depth', 'topic', 'verbal_to_symbolic_expression_structure'),
('grouped_difference_phrase_expressions', 'Grouped difference phrase expressions', 'Grouped difference phrase expressions', 'Phrases involving a difference as one quantity require parentheses when that difference is multiplied, divided, or treated as a unit.', 'algebraic_expressions', '["Write an expression for four times the difference of x and 9.", "Translate the difference of a and b divided by 3.", "Represent twice the quantity m minus 5."]'::jsonb, 'approved', 'in_depth', 'topic', 'verbal_to_symbolic_expression_structure'),
('power_phrase_expressions', 'Power phrase expressions', 'Power phrase expressions', 'Phrases such as square, cube, or raised to a power translate to exponent notation. This is translation only, not exponent-law manipulation.', 'algebraic_expressions', '["Write an expression for the square of x.", "Translate n cubed plus 4 into an algebraic expression.", "Represent 5 times a number squared."]'::jsonb, 'approved', 'in_depth', 'topic', 'verbal_to_symbolic_expression_structure'),
('consecutive_integer_expressions', 'Consecutive integer expressions', 'Consecutive integer expressions', 'Consecutive integers can be represented using a starting variable and increments of 1. This is expression construction, not equation solving.', 'algebraic_expressions', '["Write expressions for three consecutive integers starting with n.", "Represent the next integer after x.", "Identify expressions for two consecutive integers."]'::jsonb, 'approved', 'in_depth', 'topic', 'verbal_to_symbolic_expression_structure'),
('consecutive_even_integer_expressions', 'Consecutive even integer expressions', 'Consecutive even integer expressions', 'Consecutive even integers differ by 2 and can be represented using expressions such as n, n + 2, and n + 4 when n is even.', 'algebraic_expressions', '["Write expressions for three consecutive even integers starting with n.", "Represent the next even integer after 2k.", "Identify expressions for two consecutive even integers."]'::jsonb, 'approved', 'in_depth', 'topic', 'verbal_to_symbolic_expression_structure'),
('consecutive_odd_integer_expressions', 'Consecutive odd integer expressions', 'Consecutive odd integer expressions', 'Consecutive odd integers differ by 2 and can be represented using expressions such as n, n + 2, and n + 4 when n is odd.', 'algebraic_expressions', '["Write expressions for three consecutive odd integers starting with n.", "Represent the next odd integer after 2k + 1.", "Identify expressions for two consecutive odd integers."]'::jsonb, 'approved', 'in_depth', 'topic', 'verbal_to_symbolic_expression_structure'),
('percent_of_variable_expression', 'Percent of a variable quantity', 'Percent of a variable quantity', 'A percent of an unknown quantity is represented by converting the percent to a decimal or fraction multiplier. This is expression construction, not percent word-problem solving.', 'algebraic_expressions', '["Write an expression for 20% of x.", "Represent 15% of a number n.", "Translate 125% of y into an algebraic expression."]'::jsonb, 'approved', 'in_depth', 'topic', 'verbal_to_symbolic_expression_structure'),
('variable_expression_from_unit_rate', 'Variable expression from a unit rate', 'Variable expression from a unit rate', 'A unit rate times a variable quantity gives an algebraic expression for a total. This is expression construction, not linear function analysis.', 'algebraic_expressions', '["Write an expression for the cost of x items at 6 dollars each.", "Represent the distance traveled in t hours at 45 miles per hour.", "Translate 12 dollars per ticket for n tickets into an expression."]'::jsonb, 'approved', 'in_depth', 'topic', 'verbal_to_symbolic_expression_structure')
ON CONFLICT (id) DO NOTHING;

-- ─── algebraic_expression_order_and_grouping topics (negative_sign_outside_group, subtraction_before_group removed) ──
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('operation_precedence_with_variables', 'Operation precedence with variables', 'Operation precedence with variables', 'Algebraic expressions follow the same operation order as numeric expressions. This focuses on reading which operation applies first in expressions with variables.', 'algebraic_expressions', '["Identify the first operation in 3x + 5.", "Determine whether multiplication or addition happens first in 2a + 7.", "Evaluate 4x + 6 when x = 3 using correct operation order."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_order_and_grouping'),
('grouping_precedence_with_variables', 'Grouping precedence with variables', 'Grouping precedence with variables', 'Grouped algebraic quantities are treated as units before outside operations are applied. This targets expressions with parentheses and variables.', 'algebraic_expressions', '["Identify the grouped quantity in 5(x + 2).", "Evaluate 3(a - 4) when a = 9.", "Determine which operation happens first in 2(m + 7)."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_order_and_grouping'),
('nested_grouping_with_variables', 'Nested grouping with variables', 'Nested grouping with variables', 'Algebraic expressions can contain grouping symbols inside other grouping symbols. The inner grouped quantity must be interpreted first.', 'algebraic_expressions', '["Identify the innermost group in 2[x + (y - 4)].", "Evaluate 3[a - (b + 2)] when a = 10 and b = 5.", "Rewrite 4(m + [n - 3]) after identifying the nested group."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_order_and_grouping'),
('coefficient_attached_to_group', 'Coefficient attached to a group', 'Coefficient attached to a group', 'A coefficient directly next to parentheses multiplies the entire grouped expression. This supports correct parsing before distribution.', 'algebraic_expressions', '["Identify what 6 multiplies in 6(x + 4).", "Determine whether 3(a + b) means 3a + b or 3a + 3b.", "Rewrite 5(m - 2) as a product."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_order_and_grouping'),
('power_applied_to_variable_vs_coefficient', 'Power applied to variable versus coefficient', 'Power applied to variable versus coefficient', 'In a term like 3x^2, the power applies to the variable unless grouping shows otherwise. This is expression parsing, not exponent-law manipulation.', 'algebraic_expressions', '["Identify whether the 2 applies to x only or to 3x in 3x^2.", "Compare 4x^2 and (4x)^2 as expression structures.", "Determine the base of the power in -2a^3."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_order_and_grouping'),
('negative_variable_power_grouping', 'Negative variable power grouping', 'Negative variable power grouping', 'Parentheses determine whether a negative sign is part of the base of a power. This targets expressions like -x^2 versus (-x)^2.', 'algebraic_expressions', '["Compare -x^2 and (-x)^2 when x = 3.", "Identify the base in -a^2.", "Evaluate (-m)^2 and -m^2 when m = -4."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_order_and_grouping'),
('fraction_coefficient_vs_division_structure', 'Fraction coefficient versus division structure', 'Fraction coefficient versus division structure', 'A fraction next to a variable may represent a coefficient, while a fraction bar may also divide an entire expression. This focuses on reading structure correctly.', 'algebraic_expressions', '["Interpret 3/4x as a fraction coefficient times x.", "Identify whether (x + 2)/5 divides the whole quantity x + 2.", "Rewrite one-half of n as an algebraic expression."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_order_and_grouping'),
('ambiguous_linear_expression_grouping', 'Ambiguous linear expression grouping', 'Ambiguous linear expression grouping', 'Expressions such as x + 3/2 and (x + 3)/2 have different structures. This targets grouping clarity in written algebraic forms.', 'algebraic_expressions', '["Distinguish x + 4/3 from (x + 4)/3.", "Identify the expression that means the quantity x plus 5 divided by 2.", "Rewrite a phrase to show whether the numerator is x or x + 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'algebraic_expression_order_and_grouping')
ON CONFLICT (id) DO NOTHING;
