-- Category
INSERT INTO learn_categories (id, name, description, order_index)
VALUES ('linear_equations_and_inequalities', 'Linear Equations and Inequalities', 'Solving, rearranging, and interpreting one-variable linear equations and inequalities.', 3)
ON CONFLICT (id) DO NOTHING;

-- ─── Umbrella keywords ────────────────────────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('linear_equation_foundations', 'Linear Equation Foundations', 'Linear Equation Foundations', 'Core ideas behind one-variable linear equations, including equality, solutions, inverse operations, and equivalent equations.', 'linear_equations_and_inequalities', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('one_step_linear_equations', 'One-Step Linear Equations', 'One-Step Linear Equations', 'One-variable linear equations that require a single inverse operation to isolate the variable.', 'linear_equations_and_inequalities', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('two_step_linear_equations', 'Two-Step Linear Equations', 'Two-Step Linear Equations', 'One-variable linear equations that require undoing addition or subtraction and multiplication or division in the correct order.', 'linear_equations_and_inequalities', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('multi_step_linear_equations', 'Multi-Step Linear Equations', 'Multi-Step Linear Equations', 'One-variable linear equations requiring expression rewriting, distribution, term collection, clearing coefficients, or moving variable terms before isolating the variable.', 'linear_equations_and_inequalities', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('literal_equations_and_formula_rearrangement', 'Literal Equations and Formula Rearrangement', 'Literal Equations and Formula Rearrangement', 'Equations with multiple variables or parameters where one specified variable must be isolated using linear equation principles.', 'linear_equations_and_inequalities', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('linear_inequality_foundations', 'Linear Inequality Foundations', 'Linear Inequality Foundations', 'Core ideas behind one-variable linear inequalities, including inequality symbols, solution sets, endpoint behavior, interval notation, and equivalent inequalities.', 'linear_equations_and_inequalities', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('one_and_two_step_linear_inequalities', 'One- and Two-Step Linear Inequalities', 'One- and Two-Step Linear Inequalities', 'Linear inequalities that require one or two inverse operations to isolate the variable while preserving or reversing the inequality symbol correctly.', 'linear_equations_and_inequalities', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('multi_step_linear_inequalities', 'Multi-Step Linear Inequalities', 'Multi-Step Linear Inequalities', 'Linear inequalities requiring distribution, term collection, variables on both sides, clearing coefficients, or special-case analysis.', 'linear_equations_and_inequalities', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('compound_linear_inequalities', 'Compound Linear Inequalities', 'Compound Linear Inequalities', 'Solution sets formed by combining linear inequalities with AND or OR relationships, including bounded intervals, unions, contradictions, and all-real-number cases.', 'linear_equations_and_inequalities', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('linear_equation_and_inequality_interpretation', 'Linear Equation and Inequality Interpretation', 'Linear Equation and Inequality Interpretation', 'Interpreting solved linear equations and inequalities, identifying valid solution types, and avoiding common structural confusions.', 'linear_equations_and_inequalities', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL)
ON CONFLICT (id) DO NOTHING;

-- ─── linear_equation_foundations topics ───────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('equation_statement_structure', 'Equation statement structure', 'Equation statement structure', 'An equation states that two expressions have equal value using an equals sign. This focuses on recognizing the left side, right side, and equality relationship before solving.', 'linear_equations_and_inequalities', '["Identify the left side and right side of 3x + 5 = 17.", "Classify x + 4 = 10 as an equation rather than an expression.", "Determine what the equals sign means in 2a - 7 = 9."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_foundations'),
('linear_equation_solution_meaning', 'Meaning of a linear equation solution', 'Meaning of a linear equation solution', 'A solution to a one-variable linear equation is a value that makes the equation true. This distinguishes solving from simply rewriting expressions.', 'linear_equations_and_inequalities', '["Determine whether x = 4 is a solution to 3x + 2 = 14.", "Identify the value that makes 5a - 1 = 19 true.", "Explain why m = -2 satisfies 4m + 7 = -1."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_foundations'),
('linear_equation_solution_verification', 'Solution verification for linear equations', 'Solution verification for linear equations', 'A proposed solution can be checked by substituting it into both sides and comparing the resulting values. This targets errors where a value is found but not validated.', 'linear_equations_and_inequalities', '["Check whether x = 6 solves 2x - 5 = 7.", "Verify the solution a = -3 for 4a + 10 = -2.", "Determine whether n = 1 or n = 2 satisfies 8 - 3n = 5."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_foundations'),
('equivalent_linear_equations', 'Equivalent linear equations', 'Equivalent linear equations', 'Equivalent equations have the same solution set. This focuses on preserving solutions while transforming an equation.', 'linear_equations_and_inequalities', '["Determine whether x + 5 = 12 and x = 7 are equivalent equations.", "Identify which equation is equivalent to 3x = 18.", "Classify 2x + 4 = 10 and 2x = 6 as equivalent or not equivalent."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_foundations'),
('balance_principle_for_equations', 'Balance principle for equations', 'Balance principle for equations', 'The same valid operation must be applied to both sides of an equation to preserve equality. This is the structural idea behind equation solving.', 'linear_equations_and_inequalities', '["Identify why adding 4 to both sides preserves x - 4 = 9.", "Determine what must be done to both sides of 3x = 15.", "Explain why changing only one side of x + 2 = 8 breaks equality."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_foundations'),
('addition_property_of_equality', 'Addition property of equality', 'Addition property of equality', 'Adding the same quantity to both sides of an equation creates an equivalent equation. This is commonly used to undo subtraction.', 'linear_equations_and_inequalities', '["Use the addition property of equality on x - 7 = 12.", "Identify the property shown by x - 3 = 5 becoming x = 8.", "Determine what to add to both sides of a - 9 = -4."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_foundations'),
('subtraction_property_of_equality', 'Subtraction property of equality', 'Subtraction property of equality', 'Subtracting the same quantity from both sides of an equation creates an equivalent equation. This is commonly used to undo addition.', 'linear_equations_and_inequalities', '["Use the subtraction property of equality on x + 6 = 14.", "Identify the property shown by m + 10 = 3 becoming m = -7.", "Determine what to subtract from both sides of a + 5 = 21."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_foundations'),
('multiplication_property_of_equality', 'Multiplication property of equality', 'Multiplication property of equality', 'Multiplying both sides of an equation by the same nonzero quantity creates an equivalent equation. This is commonly used to undo division or fractional coefficients.', 'linear_equations_and_inequalities', '["Use the multiplication property of equality on x/5 = 8.", "Identify the property shown by x/3 = 7 becoming x = 21.", "Determine what to multiply both sides by in a/4 = -6."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_foundations'),
('division_property_of_equality', 'Division property of equality', 'Division property of equality', 'Dividing both sides of an equation by the same nonzero quantity creates an equivalent equation. This is commonly used to undo multiplication by a coefficient.', 'linear_equations_and_inequalities', '["Use the division property of equality on 6x = 42.", "Identify the property shown by -3a = 15 becoming a = -5.", "Determine what to divide both sides by in 8m = -32."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_foundations'),
('inverse_operations_in_linear_equations', 'Inverse operations in linear equations', 'Inverse operations in linear equations', 'Inverse operations undo each other and are used to isolate a variable. This includes addition with subtraction and multiplication with division.', 'linear_equations_and_inequalities', '["Identify the inverse operation needed for x + 9 = 20.", "Determine which operation undoes multiplication by -4.", "Select the inverse operation for x/7 = 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_foundations'),
('variable_isolation_concept', 'Variable isolation', 'Variable isolation', 'Isolating a variable means rewriting an equation so the variable appears alone on one side. This is the goal structure of solving a one-variable linear equation.', 'linear_equations_and_inequalities', '["Identify whether x is isolated in x = 12.", "Determine what prevents x from being isolated in 3x + 5 = 20.", "Classify x/4 = 8 as isolated or not isolated."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_foundations'),
('solution_set_single_value', 'Single-value solution sets', 'Single-value solution sets', 'Most one-variable linear equations have exactly one solution value. This topic focuses on representing that solution as a set or statement.', 'linear_equations_and_inequalities', '["Write the solution set for x = 9.", "Identify the solution set of a linear equation whose only solution is -4.", "Determine whether {6} represents one solution or many solutions."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_foundations'),
('equation_sides_with_variable_terms', 'Variable terms on equation sides', 'Variable terms on equation sides', 'A linear equation may have variable terms on the left side, right side, or both sides. This focuses on recognizing where variable terms occur before moving terms.', 'linear_equations_and_inequalities', '["Identify the variable terms in 4x + 1 = 2x + 9.", "Determine which side contains the variable in 15 = 3m - 6.", "Classify x + 5 = 2x - 1 as having variables on one side or both sides."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_foundations')
ON CONFLICT (id) DO NOTHING;

-- ─── one_step_linear_equations topics ─────────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('one_step_addition_equations', 'One-step equations with addition', 'One-step equations with addition', 'Equations of the form x + a = b require subtracting the same constant from both sides. This targets the structure where addition is attached to the variable.', 'linear_equations_and_inequalities', '["Solve x + 8 = 19.", "Solve a + 5 = -2.", "Determine the value of n in n + 12 = 30."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_step_linear_equations'),
('one_step_subtraction_equations', 'One-step equations with subtraction', 'One-step equations with subtraction', 'Equations of the form x - a = b require adding the same constant to both sides. This targets the structure where subtraction follows the variable.', 'linear_equations_and_inequalities', '["Solve x - 7 = 15.", "Solve m - 10 = -3.", "Determine the value of a in a - 4 = 11."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_step_linear_equations'),
('one_step_variable_subtracted_from_constant_equations', 'One-step equations with variable subtracted from a constant', 'One-step equations with variable subtracted from a constant', 'Equations of the form a - x = b require careful handling because the variable term has an implied coefficient of -1. This differs from x - a = b.', 'linear_equations_and_inequalities', '["Solve 9 - x = 4.", "Solve 3 - a = 11.", "Determine the value of n in -5 - n = 8."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_step_linear_equations'),
('one_step_multiplication_equations', 'One-step equations with multiplication', 'One-step equations with multiplication', 'Equations of the form ax = b require dividing both sides by the nonzero coefficient. This targets variable terms multiplied by integer coefficients.', 'linear_equations_and_inequalities', '["Solve 6x = 42.", "Solve -4a = 20.", "Determine the value of m in 9m = -63."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_step_linear_equations'),
('one_step_division_equations', 'One-step equations with division', 'One-step equations with division', 'Equations of the form x/a = b require multiplying both sides by the nonzero divisor. This targets variables divided by constants.', 'linear_equations_and_inequalities', '["Solve x/5 = 9.", "Solve a/-3 = 7.", "Determine the value of n in n/8 = -4."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_step_linear_equations'),
('one_step_negative_coefficient_equations', 'One-step equations with negative coefficients', 'One-step equations with negative coefficients', 'Equations with a negative coefficient require dividing by a negative number, which affects the sign of the solution. This targets sign errors in simple linear equations.', 'linear_equations_and_inequalities', '["Solve -7x = 35.", "Solve -2a = -18.", "Determine the value of m in -11m = 44."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_step_linear_equations'),
('one_step_fraction_coefficient_equations', 'One-step equations with fraction coefficients', 'One-step equations with fraction coefficients', 'Equations of the form (a/b)x = c require multiplying by the reciprocal or dividing by the fractional coefficient. This focuses on fractional coefficients attached to the variable.', 'linear_equations_and_inequalities', '["Solve (1/3)x = 6.", "Solve (2/5)a = 10.", "Determine the value of m in (-3/4)m = 12."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_step_linear_equations'),
('one_step_decimal_coefficient_equations', 'One-step equations with decimal coefficients', 'One-step equations with decimal coefficients', 'Equations with decimal coefficients require dividing by the decimal coefficient or converting to an equivalent fraction. This targets coefficient interpretation, not decimal arithmetic alone.', 'linear_equations_and_inequalities', '["Solve 0.5x = 8.", "Solve 1.2a = 6.", "Determine the value of m in -0.25m = 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_step_linear_equations'),
('one_step_equations_with_fraction_solutions', 'One-step equations with fraction solutions', 'One-step equations with fraction solutions', 'A one-step linear equation may have a fractional solution even when the equation uses integers. This targets the misconception that all simple equations have integer answers.', 'linear_equations_and_inequalities', '["Solve 4x = 7.", "Solve 9a = -2.", "Determine the value of m in 5m = 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_step_linear_equations'),
('one_step_equations_with_zero_solution', 'One-step equations with zero solution', 'One-step equations with zero solution', 'Some one-step equations have solution 0, often when the constant side is 0. This targets confusion between zero as a solution and no solution.', 'linear_equations_and_inequalities', '["Solve 8x = 0.", "Solve a + 5 = 5.", "Determine the value of n in n - 12 = -12."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_step_linear_equations'),
('one_step_equations_with_variable_on_right', 'One-step equations with variable on the right', 'One-step equations with variable on the right', 'The variable may appear on the right side of a one-step equation. The same inverse-operation logic applies, but students must not assume the variable is always on the left.', 'linear_equations_and_inequalities', '["Solve 15 = x + 6.", "Solve -20 = 5a.", "Determine the value of m in 7 = m/3."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_step_linear_equations'),
('one_step_equations_with_signed_constants', 'One-step equations with signed constants', 'One-step equations with signed constants', 'One-step equations may involve negative constants on either side. This targets signed-number errors while isolating the variable.', 'linear_equations_and_inequalities', '["Solve x + (-6) = 11.", "Solve a - (-4) = 9.", "Determine the value of n in n + 3 = -8."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_step_linear_equations')
ON CONFLICT (id) DO NOTHING;

-- ─── two_step_linear_equations topics ─────────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('two_step_equations_ax_plus_b_equals_c', 'Two-step equations of the form ax + b = c', 'Two-step equations of the form ax + b = c', 'Equations with a multiplied variable term plus a constant require undoing the constant first, then undoing the coefficient. This is the standard two-step linear structure.', 'linear_equations_and_inequalities', '["Solve 3x + 5 = 20.", "Solve 7a + 2 = -19.", "Determine the value of m in 4m + 9 = 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'two_step_linear_equations'),
('two_step_equations_ax_minus_b_equals_c', 'Two-step equations of the form ax - b = c', 'Two-step equations of the form ax - b = c', 'Equations with a multiplied variable term minus a constant require adding the constant to both sides before dividing by the coefficient.', 'linear_equations_and_inequalities', '["Solve 5x - 8 = 17.", "Solve -2a - 9 = 3.", "Determine the value of m in 6m - 11 = -5."]'::jsonb, 'approved', 'in_depth', 'topic', 'two_step_linear_equations'),
('two_step_equations_b_plus_ax_equals_c', 'Two-step equations with constant before variable term', 'Two-step equations with constant before variable term', 'Equations where the constant is written before the variable term still follow the same inverse-operation structure. This targets parsing expressions such as 7 + 3x.', 'linear_equations_and_inequalities', '["Solve 4 + 2x = 18.", "Solve -9 + 5a = 11.", "Determine the value of m in 13 - 4m = 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'two_step_linear_equations'),
('two_step_equations_variable_term_negative', 'Two-step equations with negative variable term', 'Two-step equations with negative variable term', 'Equations with a negative variable coefficient require careful sign handling after the constant term is removed. This targets structures such as -3x + 8 = 20.', 'linear_equations_and_inequalities', '["Solve -3x + 8 = 20.", "Solve -5a - 4 = 16.", "Determine the value of m in 10 - 2m = 18."]'::jsonb, 'approved', 'in_depth', 'topic', 'two_step_linear_equations'),
('two_step_equations_variable_divided_by_constant', 'Two-step equations with variable divided by a constant', 'Two-step equations with variable divided by a constant', 'Equations of the form x/a + b = c require undoing the added or subtracted constant before multiplying by the divisor.', 'linear_equations_and_inequalities', '["Solve x/4 + 3 = 9.", "Solve a/5 - 2 = -6.", "Determine the value of n in n/-3 + 7 = 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'two_step_linear_equations'),
('two_step_equations_fraction_coefficient', 'Two-step equations with fraction coefficients', 'Two-step equations with fraction coefficients', 'Equations with fractional coefficients require isolating the variable term and then undoing the fractional multiplier. This targets reciprocal use in a two-step setting.', 'linear_equations_and_inequalities', '["Solve (2/3)x + 5 = 17.", "Solve (1/4)a - 6 = 2.", "Determine the value of m in (-3/5)m + 7 = -8."]'::jsonb, 'approved', 'in_depth', 'topic', 'two_step_linear_equations'),
('two_step_equations_decimal_coefficient', 'Two-step equations with decimal coefficients', 'Two-step equations with decimal coefficients', 'Equations with decimal coefficients require isolating the variable term and dividing by the decimal coefficient. This is coefficient structure within a two-step equation.', 'linear_equations_and_inequalities', '["Solve 0.5x + 4 = 10.", "Solve 1.25a - 3 = 7.", "Determine the value of m in -0.2m + 9 = 5."]'::jsonb, 'approved', 'in_depth', 'topic', 'two_step_linear_equations'),
('two_step_equations_with_negative_solution', 'Two-step equations with negative solutions', 'Two-step equations with negative solutions', 'A two-step linear equation may produce a negative solution, often from signed constants or negative coefficients. This targets sign interpretation in final answers.', 'linear_equations_and_inequalities', '["Solve 4x + 9 = -7.", "Solve 3a - 5 = -20.", "Determine the value of m in -2m + 1 = 15."]'::jsonb, 'approved', 'in_depth', 'topic', 'two_step_linear_equations'),
('two_step_equations_with_zero_solution', 'Two-step equations with zero solution', 'Two-step equations with zero solution', 'A two-step equation can have solution 0 after the variable term is isolated. This distinguishes zero as a valid value from no solution.', 'linear_equations_and_inequalities', '["Solve 5x + 8 = 8.", "Solve -3a - 6 = -6.", "Determine the value of m in 7 - 2m = 7."]'::jsonb, 'approved', 'in_depth', 'topic', 'two_step_linear_equations'),
('two_step_equations_operation_order_reversal', 'Reverse order of operations in two-step equations', 'Reverse order of operations in two-step equations', 'Solving a two-step equation usually reverses the order used to evaluate the expression: undo addition or subtraction before multiplication or division.', 'linear_equations_and_inequalities', '["Identify the first inverse operation for 4x + 7 = 31.", "Determine why subtracting 5 comes before dividing in 6x + 5 = 23.", "Select the correct first step for x/3 - 8 = 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'two_step_linear_equations'),
('two_step_equations_right_side_variable_expression', 'Two-step equations with variable expression on the right', 'Two-step equations with variable expression on the right', 'A two-step variable expression may appear on the right side of the equation. The same isolation logic applies while preserving equality.', 'linear_equations_and_inequalities', '["Solve 19 = 4x + 3.", "Solve -5 = 2a - 11.", "Determine the value of m in 12 = m/2 + 7."]'::jsonb, 'approved', 'in_depth', 'topic', 'two_step_linear_equations'),
('two_step_equations_with_parenthesized_constants', 'Two-step equations with signed constant grouping', 'Two-step equations with signed constant grouping', 'Two-step equations may write signed constants with parentheses, requiring correct interpretation before applying inverse operations. This targets expressions such as x + (-5).', 'linear_equations_and_inequalities', '["Solve 3x + (-4) = 11.", "Solve -2a - (-7) = 13.", "Determine the value of m in 5m + (-9) = -24."]'::jsonb, 'approved', 'in_depth', 'topic', 'two_step_linear_equations')
ON CONFLICT (id) DO NOTHING;

-- ─── multi_step_linear_equations topics ───────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('linear_equations_combining_like_terms_one_side', 'Linear equations requiring like-term collection on one side', 'Linear equations requiring like-term collection on one side', 'Some equations require collecting like terms on one side before inverse operations isolate the variable. This focuses on equations such as 3x + 4x - 5 = 16.', 'linear_equations_and_inequalities', '["Solve 3x + 4x - 5 = 16.", "Solve 8a - 2a + 9 = -3.", "Determine the value of m in 5m + 7 - 2m = 19."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_equations_with_distribution_one_side', 'Linear equations requiring distribution on one side', 'Linear equations requiring distribution on one side', 'Equations with a grouped expression on one side may require distribution before isolating the variable. This targets structures such as 3(x + 4) = 21.', 'linear_equations_and_inequalities', '["Solve 3(x + 4) = 21.", "Solve 5(a - 2) = -10.", "Determine the value of m in 2(m + 7) = 30."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_equations_with_negative_distribution', 'Linear equations requiring negative distribution', 'Linear equations requiring negative distribution', 'Equations with a negative factor outside parentheses require distributing the negative sign correctly before solving. This targets sign errors in multi-step equations.', 'linear_equations_and_inequalities', '["Solve -2(x + 5) = 14.", "Solve -3(a - 4) = 9.", "Determine the value of m in 6 - 2(m + 1) = 0."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_equations_with_subtracted_parentheses', 'Linear equations with subtracted parentheses', 'Linear equations with subtracted parentheses', 'Subtracting a parenthesized expression changes the sign of every term inside before collecting terms. This is a common multi-step equation structure.', 'linear_equations_and_inequalities', '["Solve x - (2x + 5) = 11.", "Solve 4a - (a - 6) = 18.", "Determine the value of m in 7 - (3m - 2) = -9."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_equations_with_multiple_parentheses', 'Linear equations with multiple grouped expressions', 'Linear equations with multiple grouped expressions', 'Equations may require distributing across two or more grouped expressions before combining like terms. Each group must be rewritten correctly.', 'linear_equations_and_inequalities', '["Solve 2(x + 3) + 4(x - 1) = 20.", "Solve 5(a - 2) - 3(a + 4) = 8.", "Determine the value of m in 7(m + 1) + 2(m - 5) = 24."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_equations_variables_on_both_sides', 'Linear equations with variables on both sides', 'Linear equations with variables on both sides', 'Equations with variable terms on both sides require moving variable terms to one side and constants to the other before isolating the variable.', 'linear_equations_and_inequalities', '["Solve 5x + 2 = 2x + 14.", "Solve 7a - 3 = 4a + 12.", "Determine the value of m in 9m + 1 = 3m - 17."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_equations_constants_on_both_sides', 'Linear equations with constants on both sides', 'Linear equations with constants on both sides', 'Constants may appear on both sides and need to be gathered on the side opposite the variable terms. This focuses on constant movement within equations.', 'linear_equations_and_inequalities', '["Solve 4x + 9 = 2x - 5.", "Solve 8a - 11 = 3a + 4.", "Determine the value of m in 6m + 13 = m - 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_equations_distribution_both_sides', 'Linear equations requiring distribution on both sides', 'Linear equations requiring distribution on both sides', 'Both sides of a linear equation may contain grouped expressions that must be expanded before variable terms are collected.', 'linear_equations_and_inequalities', '["Solve 3(x + 2) = 2(x + 9).", "Solve 5(a - 1) = 2(a + 7).", "Determine the value of m in 4(m + 3) = 6(m - 1)."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_equations_combining_like_terms_both_sides', 'Linear equations requiring like-term collection on both sides', 'Linear equations requiring like-term collection on both sides', 'Each side may need internal simplification before moving terms across the equation. This targets equations with repeated variable or constant terms on both sides.', 'linear_equations_and_inequalities', '["Solve 3x + 2x - 7 = x + 9.", "Solve 8a - 4 + 2a = 5a + 11.", "Determine the value of m in 6m + 3 - m = 2m - 12."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_equations_with_fraction_coefficients', 'Multi-step linear equations with fraction coefficients', 'Multi-step linear equations with fraction coefficients', 'Fraction coefficients may appear throughout a linear equation and require careful arithmetic or clearing denominators. This focuses on coefficient structure, not rational equations with variable denominators.', 'linear_equations_and_inequalities', '["Solve (1/2)x + 3 = (3/4)x - 5.", "Solve (2/3)a - 4 = (1/6)a + 1.", "Determine the value of m in (5/8)m + 2 = (1/4)m - 7."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_equations_clearing_fraction_coefficients', 'Clearing fraction coefficients in linear equations', 'Clearing fraction coefficients in linear equations', 'Multiplying every term by the least common denominator can remove fraction coefficients from a linear equation. This applies only when denominators are constants.', 'linear_equations_and_inequalities', '["Solve x/3 + 2 = 5 by clearing the denominator.", "Solve (1/4)a - (1/2) = 3 by clearing fractions.", "Determine the LCD needed to clear fractions in x/6 + x/4 = 5."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_equations_with_decimal_coefficients', 'Multi-step linear equations with decimal coefficients', 'Multi-step linear equations with decimal coefficients', 'Decimal coefficients may be solved directly or cleared by multiplying by a power of 10. This targets equations where decimals appear in variable and constant terms.', 'linear_equations_and_inequalities', '["Solve 0.4x + 1.2 = 3.6.", "Solve 1.5a - 0.25 = 2.75.", "Determine the value of m in 0.08m + 4 = 0.2m - 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_equations_clearing_decimal_coefficients', 'Clearing decimal coefficients in linear equations', 'Clearing decimal coefficients in linear equations', 'Multiplying every term by a power of 10 can remove decimal coefficients from a linear equation. This supports cleaner integer-coefficient solving.', 'linear_equations_and_inequalities', '["Rewrite 0.5x + 1.2 = 4.7 without decimals.", "Solve 0.03a + 0.2 = 0.5 by clearing decimals.", "Determine what power of 10 clears all decimals in 1.25m - 0.4 = 2.6."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_proportion_equations_variable_numerator', 'Linear proportion equations with variable numerator', 'Linear proportion equations with variable numerator', 'A proportion equation with the variable only in a numerator can be solved by equivalent ratios or cross products. This excludes variable-denominator rational equations.', 'linear_equations_and_inequalities', '["Solve x/5 = 12/15.", "Solve a/6 = 10/15.", "Determine the value of n in n/8 = 9/12."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_equations_from_cross_products_constant_denominators', 'Cross-product linear equations with constant denominators', 'Cross-product linear equations with constant denominators', 'When a proportion has constant denominators and a variable numerator or linear numerator, cross products can create a linear equation. This avoids rational equations where the variable is in a denominator.', 'linear_equations_and_inequalities', '["Solve (x + 2)/3 = 5/6.", "Solve (2a - 1)/4 = 7/8.", "Determine the value of m in (m - 3)/5 = 2/10."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_equations_special_case_no_solution', 'Linear equations with no solution', 'Linear equations with no solution', 'A linear equation has no solution when equivalent transformations produce a false statement such as 0 = 5. This usually occurs after variable terms cancel.', 'linear_equations_and_inequalities', '["Solve 3x + 4 = 3x - 8.", "Solve 5(a - 2) = 5a + 1.", "Determine whether 2m + 7 = 2m + 7 has no solution or infinitely many solutions."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_equations_special_case_identity', 'Linear equations with infinitely many solutions', 'Linear equations with infinitely many solutions', 'A linear equation has infinitely many solutions when transformations produce a true identity such as 0 = 0. This means every real number satisfies the equation.', 'linear_equations_and_inequalities', '["Solve 4x + 6 = 2(2x + 3).", "Solve 7a - 5 = 7a - 5.", "Determine whether 3(m + 2) = 3m + 6 has one solution or infinitely many solutions."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations'),
('linear_equations_zero_coefficient_after_simplification', 'Zero variable coefficient after simplification', 'Zero variable coefficient after simplification', 'When variable terms cancel, the equation reduces to either a true or false constant statement. This is the structural fork behind no-solution and identity cases.', 'linear_equations_and_inequalities', '["Identify what happens to the variable terms in 6x + 1 = 6x + 9.", "Simplify 2(a + 3) = 2a + 6 to determine the remaining statement.", "Determine whether 0m = 12 or 0m = 0 results after simplifying."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_equations')
ON CONFLICT (id) DO NOTHING;

-- ─── literal_equations_and_formula_rearrangement topics ───────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('literal_equations_isolating_added_variable', 'Literal equations isolating a variable with addition', 'Literal equations isolating a variable with addition', 'A specified variable can be isolated by undoing addition or subtraction involving other variables or constants. This focuses on symbolic isolation, not numeric solving.', 'linear_equations_and_inequalities', '["Solve x + y = 10 for x.", "Solve a + b = c for a.", "Rearrange p + q = r to isolate q."]'::jsonb, 'approved', 'in_depth', 'topic', 'literal_equations_and_formula_rearrangement'),
('literal_equations_isolating_multiplied_variable', 'Literal equations isolating a multiplied variable', 'Literal equations isolating a multiplied variable', 'A variable multiplied by another nonzero quantity is isolated by division. This targets forms such as ax = b and ab = c solved for one factor.', 'linear_equations_and_inequalities', '["Solve ax = b for x.", "Solve mn = p for n.", "Rearrange py = q to isolate y."]'::jsonb, 'approved', 'in_depth', 'topic', 'literal_equations_and_formula_rearrangement'),
('literal_equations_isolating_divided_variable', 'Literal equations isolating a divided variable', 'Literal equations isolating a divided variable', 'A variable appearing in a numerator over a constant or parameter can be isolated by multiplying both sides by the denominator. This excludes solving for variables in denominators.', 'linear_equations_and_inequalities', '["Solve x/a = b for x.", "Solve m/5 = n for m.", "Rearrange y/k = p to isolate y."]'::jsonb, 'approved', 'in_depth', 'topic', 'literal_equations_and_formula_rearrangement'),
('literal_equations_two_step_linear_forms', 'Literal equations with two-step linear forms', 'Literal equations with two-step linear forms', 'A specified variable in a form such as ax + b = c is isolated by undoing addition or subtraction before undoing multiplication. This mirrors two-step linear solving with parameters.', 'linear_equations_and_inequalities', '["Solve ax + b = c for x.", "Solve 3y + k = m for y.", "Rearrange p = 2q - r to isolate q."]'::jsonb, 'approved', 'in_depth', 'topic', 'literal_equations_and_formula_rearrangement'),
('literal_equations_variable_on_both_sides', 'Literal equations with the target variable on both sides', 'Literal equations with the target variable on both sides', 'When the target variable appears on both sides, terms containing that variable must be gathered before factoring out the variable if needed. This remains linear in the target variable.', 'linear_equations_and_inequalities', '["Solve ax + b = cx + d for x.", "Solve 3y + k = my - 2 for y.", "Rearrange pz + q = rz for z."]'::jsonb, 'approved', 'in_depth', 'topic', 'literal_equations_and_formula_rearrangement'),
('literal_equations_factoring_target_variable', 'Factoring out the target variable in literal equations', 'Factoring out the target variable in literal equations', 'After collecting terms with the target variable, the variable may need to be factored out before division isolates it. This is formula rearrangement, not polynomial factoring as a standalone skill.', 'linear_equations_and_inequalities', '["Solve ax + bx = c for x.", "Solve py - qy = r for y.", "Rearrange mx + n = px to isolate x."]'::jsonb, 'approved', 'in_depth', 'topic', 'literal_equations_and_formula_rearrangement'),
('linear_formula_rearrangement_for_y', 'Linear formula rearrangement for y', 'Linear formula rearrangement for y', 'A linear relationship involving x and y can be rearranged to isolate y. This is algebraic rearrangement only, not graphing or function analysis.', 'linear_equations_and_inequalities', '["Solve 3x + 2y = 12 for y.", "Rearrange 5x - y = 8 to isolate y.", "Solve Ax + By = C for y."]'::jsonb, 'approved', 'in_depth', 'topic', 'literal_equations_and_formula_rearrangement'),
('linear_formula_rearrangement_for_x', 'Linear formula rearrangement for x', 'Linear formula rearrangement for x', 'A linear relationship involving x and y can be rearranged to isolate x. This targets moving terms and dividing by a coefficient symbolically.', 'linear_equations_and_inequalities', '["Solve 4x + 3y = 18 for x.", "Rearrange y = 2x + 7 to isolate x.", "Solve Ax + By = C for x."]'::jsonb, 'approved', 'in_depth', 'topic', 'literal_equations_and_formula_rearrangement'),
('formula_rearrangement_with_fraction_coefficients', 'Formula rearrangement with fraction coefficients', 'Formula rearrangement with fraction coefficients', 'Formulas with fractional coefficients require clearing denominators or using reciprocal operations to isolate the requested variable.', 'linear_equations_and_inequalities', '["Solve y = (1/2)x + b for x.", "Rearrange A = (1/2)bh to isolate h.", "Solve p = q/3 + r for q."]'::jsonb, 'approved', 'in_depth', 'topic', 'literal_equations_and_formula_rearrangement'),
('formula_rearrangement_with_parentheses', 'Formula rearrangement with parentheses', 'Formula rearrangement with parentheses', 'Formulas with grouped expressions may require distribution or division by a common factor before isolating the requested variable.', 'linear_equations_and_inequalities', '["Solve P = 2l + 2w for l.", "Rearrange A = h(b1 + b2)/2 to isolate h.", "Solve C = k(x - a) for x."]'::jsonb, 'approved', 'in_depth', 'topic', 'literal_equations_and_formula_rearrangement'),
('formula_rearrangement_with_subtracted_target_variable', 'Formula rearrangement with subtracted target variable', 'Formula rearrangement with subtracted target variable', 'When the target variable is subtracted, its implied negative coefficient must be handled correctly. This targets forms such as a - x = b.', 'linear_equations_and_inequalities', '["Solve a - x = b for x.", "Rearrange p - q = r to isolate q.", "Solve m - 2n = k for n."]'::jsonb, 'approved', 'in_depth', 'topic', 'literal_equations_and_formula_rearrangement'),
('formula_rearrangement_solution_restrictions', 'Restrictions in formula rearrangement', 'Restrictions in formula rearrangement', 'Some formula rearrangements require noting that a divisor cannot be zero. This focuses on restrictions introduced by division during isolation.', 'linear_equations_and_inequalities', '["Solve ax = b for x and state the restriction on a.", "Rearrange By = C - Ax for y and identify the nonzero parameter.", "Solve kx + m = n for x and state when the rearrangement is valid."]'::jsonb, 'approved', 'in_depth', 'topic', 'literal_equations_and_formula_rearrangement')
ON CONFLICT (id) DO NOTHING;

-- ─── linear_inequality_foundations topics ─────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('inequality_statement_structure', 'Inequality statement structure', 'Inequality statement structure', 'An inequality compares two expressions using symbols such as <, >, ≤, or ≥. This focuses on reading the left side, right side, and comparison relationship.', 'linear_equations_and_inequalities', '["Identify the inequality symbol in 3x + 2 < 11.", "Classify x - 4 ≥ 8 as an inequality rather than an equation.", "Determine the left side and right side of 5a - 1 ≤ 9."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_inequality_foundations'),
('strict_inequality_symbols', 'Strict inequality symbols', 'Strict inequality symbols', 'The symbols < and > exclude equality at the boundary value. This affects solution sets and open endpoints.', 'linear_equations_and_inequalities', '["Identify whether x < 5 includes x = 5.", "Classify x > -2 as a strict inequality.", "Determine which symbol means strictly less than."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_inequality_foundations'),
('inclusive_inequality_symbols', 'Inclusive inequality symbols', 'Inclusive inequality symbols', 'The symbols ≤ and ≥ include equality at the boundary value. This affects solution sets and closed endpoints.', 'linear_equations_and_inequalities', '["Identify whether x ≤ 5 includes x = 5.", "Classify x ≥ -2 as an inclusive inequality.", "Determine which symbol means greater than or equal to."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_inequality_foundations'),
('linear_inequality_solution_meaning', 'Meaning of a linear inequality solution', 'Meaning of a linear inequality solution', 'A solution to a one-variable linear inequality is any value that makes the inequality true. Unlike most linear equations, inequalities usually have infinitely many solutions.', 'linear_equations_and_inequalities', '["Determine whether x = 3 is a solution to x + 4 < 10.", "Identify a value that satisfies 2a - 1 ≥ 7.", "Classify -5 as a solution or non-solution of m > -8."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_inequality_foundations'),
('linear_inequality_solution_verification', 'Solution verification for linear inequalities', 'Solution verification for linear inequalities', 'A proposed inequality solution can be checked by substituting a value and testing whether the comparison is true. This includes boundary-value checks.', 'linear_equations_and_inequalities', '["Check whether x = 4 satisfies 3x - 2 ≤ 10.", "Verify whether a = -1 is a solution to 5a + 7 > 0.", "Determine whether the boundary value satisfies x ≤ 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_inequality_foundations'),
('equivalent_linear_inequalities', 'Equivalent linear inequalities', 'Equivalent linear inequalities', 'Equivalent inequalities have the same solution set. Valid transformations preserve the solution set, with special care for multiplication or division by negatives.', 'linear_equations_and_inequalities', '["Determine whether x + 3 < 8 and x < 5 are equivalent.", "Identify which inequality is equivalent to 2x ≥ 10.", "Classify -x < 4 and x > -4 as equivalent or not equivalent."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_inequality_foundations'),
('addition_property_of_inequality', 'Addition property of inequality', 'Addition property of inequality', 'Adding the same quantity to both sides of an inequality preserves the direction of the inequality. This is used to undo subtraction.', 'linear_equations_and_inequalities', '["Use the addition property of inequality on x - 6 < 9.", "Identify the property shown by a - 3 ≥ 5 becoming a ≥ 8.", "Determine what to add to both sides of m - 10 ≤ -2."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_inequality_foundations'),
('subtraction_property_of_inequality', 'Subtraction property of inequality', 'Subtraction property of inequality', 'Subtracting the same quantity from both sides of an inequality preserves the direction of the inequality. This is used to undo addition.', 'linear_equations_and_inequalities', '["Use the subtraction property of inequality on x + 4 > 11.", "Identify the property shown by m + 8 ≤ 2 becoming m ≤ -6.", "Determine what to subtract from both sides of a + 5 ≥ 13."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_inequality_foundations'),
('positive_multiplication_property_of_inequality', 'Positive multiplication property of inequality', 'Positive multiplication property of inequality', 'Multiplying both sides of an inequality by the same positive number preserves the inequality direction. This is used to undo division by a positive number.', 'linear_equations_and_inequalities', '["Use positive multiplication on x/3 < 5.", "Identify why multiplying both sides of a/4 ≥ -2 by 4 keeps the symbol the same.", "Determine the equivalent inequality after multiplying m/6 ≤ 7 by 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_inequality_foundations'),
('positive_division_property_of_inequality', 'Positive division property of inequality', 'Positive division property of inequality', 'Dividing both sides of an inequality by the same positive number preserves the inequality direction. This is used to undo positive coefficients.', 'linear_equations_and_inequalities', '["Use positive division on 5x < 20.", "Identify why dividing 8a ≥ -16 by 8 keeps the symbol the same.", "Determine the equivalent inequality after dividing 3m ≤ 21 by 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_inequality_foundations'),
('negative_multiplication_property_of_inequality', 'Negative multiplication property of inequality', 'Negative multiplication property of inequality', 'Multiplying both sides of an inequality by the same negative number reverses the inequality direction. This is one of the most important linear inequality distinctions.', 'linear_equations_and_inequalities', '["Solve x/-4 < 3 by multiplying by -4.", "Identify why multiplying both sides by -2 reverses the symbol.", "Determine the equivalent inequality after multiplying -x > 7 by -1."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_inequality_foundations'),
('negative_division_property_of_inequality', 'Negative division property of inequality', 'Negative division property of inequality', 'Dividing both sides of an inequality by the same negative number reverses the inequality direction. This is used to undo negative coefficients.', 'linear_equations_and_inequalities', '["Solve -3x ≤ 12.", "Identify why dividing -5a > 20 by -5 reverses the symbol.", "Determine the equivalent inequality after dividing -2m ≥ -8 by -2."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_inequality_foundations'),
('inequality_boundary_values', 'Inequality boundary values', 'Inequality boundary values', 'A boundary value is the value where the related equation would be true. The inequality symbol determines whether that boundary is included.', 'linear_equations_and_inequalities', '["Identify the boundary value for x < 9.", "Determine whether the boundary is included in x ≥ -4.", "Find the boundary value for 2x + 3 ≤ 11."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_inequality_foundations'),
('number_line_representation_inequalities', 'Number-line representations of inequalities', 'Number-line representations of inequalities', 'One-variable inequality solutions can be represented on a number line using open or closed endpoints and shading direction. This is not coordinate-plane graphing.', 'linear_equations_and_inequalities', '["Graph x < 5 on a number line.", "Identify the inequality represented by a closed dot at -2 shaded right.", "Determine whether x ≥ 7 uses an open or closed dot."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_inequality_foundations'),
('interval_notation_for_inequalities', 'Interval notation for inequalities', 'Interval notation for inequalities', 'Inequality solution sets can be written using interval notation with parentheses, brackets, and infinity symbols. This focuses on notation conversion.', 'linear_equations_and_inequalities', '["Write x < 4 in interval notation.", "Convert x ≥ -3 to interval notation.", "Identify the inequality represented by (-∞, 8]."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_inequality_foundations')
ON CONFLICT (id) DO NOTHING;

-- ─── one_and_two_step_linear_inequalities topics ───────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('one_step_inequalities_addition', 'One-step inequalities with addition', 'One-step inequalities with addition', 'Inequalities of the form x + a < b or x + a > b require subtracting the same constant from both sides while keeping the inequality direction.', 'linear_equations_and_inequalities', '["Solve x + 7 < 15.", "Solve a + 4 ≥ -2.", "Determine the solution set for n + 10 > 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_and_two_step_linear_inequalities'),
('one_step_inequalities_subtraction', 'One-step inequalities with subtraction', 'One-step inequalities with subtraction', 'Inequalities of the form x - a < b or x - a > b require adding the same constant to both sides while keeping the inequality direction.', 'linear_equations_and_inequalities', '["Solve x - 5 ≤ 12.", "Solve m - 9 > -4.", "Determine the solution set for a - 6 ≥ 0."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_and_two_step_linear_inequalities'),
('one_step_inequalities_positive_multiplication', 'One-step inequalities with positive multiplication', 'One-step inequalities with positive multiplication', 'Inequalities with a positive coefficient multiplying the variable are solved by dividing by that positive coefficient without reversing the symbol.', 'linear_equations_and_inequalities', '["Solve 4x < 28.", "Solve 6a ≥ -18.", "Determine the solution set for 9m ≤ 45."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_and_two_step_linear_inequalities'),
('one_step_inequalities_negative_multiplication', 'One-step inequalities with negative multiplication', 'One-step inequalities with negative multiplication', 'Inequalities with a negative coefficient multiplying the variable require division by a negative number and reversal of the inequality symbol.', 'linear_equations_and_inequalities', '["Solve -3x < 12.", "Solve -5a ≥ 20.", "Determine the solution set for -2m ≤ -14."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_and_two_step_linear_inequalities'),
('one_step_inequalities_positive_division', 'One-step inequalities with positive division', 'One-step inequalities with positive division', 'Inequalities with the variable divided by a positive number are solved by multiplying by that positive number without reversing the symbol.', 'linear_equations_and_inequalities', '["Solve x/4 > 6.", "Solve a/7 ≤ -3.", "Determine the solution set for m/5 ≥ 8."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_and_two_step_linear_inequalities'),
('one_step_inequalities_negative_division', 'One-step inequalities with negative division', 'One-step inequalities with negative division', 'Inequalities with the variable divided by a negative number are solved by multiplying by that negative number and reversing the inequality symbol.', 'linear_equations_and_inequalities', '["Solve x/-3 < 9.", "Solve a/-5 ≥ -2.", "Determine the solution set for m/-4 ≤ 7."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_and_two_step_linear_inequalities'),
('one_step_inequalities_fraction_coefficients', 'One-step inequalities with fraction coefficients', 'One-step inequalities with fraction coefficients', 'Inequalities with fractional coefficients require undoing the fraction multiplier, with reversal only if the multiplier or divisor used is negative.', 'linear_equations_and_inequalities', '["Solve (1/2)x < 6.", "Solve (-3/4)a ≥ 9.", "Determine the solution set for (2/5)m ≤ -8."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_and_two_step_linear_inequalities'),
('one_step_inequalities_decimal_coefficients', 'One-step inequalities with decimal coefficients', 'One-step inequalities with decimal coefficients', 'Inequalities with decimal coefficients require dividing by the decimal coefficient, with sign reversal only for negative coefficients.', 'linear_equations_and_inequalities', '["Solve 0.5x > 4.", "Solve -0.2a ≤ 3.", "Determine the solution set for 1.5m ≥ -6."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_and_two_step_linear_inequalities'),
('two_step_inequalities_positive_coefficient', 'Two-step inequalities with positive coefficients', 'Two-step inequalities with positive coefficients', 'Inequalities such as ax + b < c with a positive coefficient require undoing the constant and then dividing by a positive number without reversing the symbol.', 'linear_equations_and_inequalities', '["Solve 3x + 5 < 20.", "Solve 4a - 7 ≥ 9.", "Determine the solution set for 2m + 1 ≤ -5."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_and_two_step_linear_inequalities'),
('two_step_inequalities_negative_coefficient', 'Two-step inequalities with negative coefficients', 'Two-step inequalities with negative coefficients', 'Inequalities such as ax + b < c with a negative coefficient require undoing the constant and then dividing by a negative number, reversing the symbol.', 'linear_equations_and_inequalities', '["Solve -3x + 5 < 20.", "Solve -4a - 7 ≥ 9.", "Determine the solution set for -2m + 1 ≤ -5."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_and_two_step_linear_inequalities'),
('two_step_inequalities_variable_divided_by_positive', 'Two-step inequalities with variable divided by a positive constant', 'Two-step inequalities with variable divided by a positive constant', 'Inequalities with x/a plus or minus a constant require isolating the quotient and multiplying by a positive divisor, preserving the inequality direction.', 'linear_equations_and_inequalities', '["Solve x/3 + 4 < 10.", "Solve a/5 - 2 ≥ -1.", "Determine the solution set for m/7 + 6 ≤ 8."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_and_two_step_linear_inequalities'),
('two_step_inequalities_variable_divided_by_negative', 'Two-step inequalities with variable divided by a negative constant', 'Two-step inequalities with variable divided by a negative constant', 'Inequalities with x divided by a negative constant require reversal when multiplying by the negative divisor. This targets sign reversal in quotient structures.', 'linear_equations_and_inequalities', '["Solve x/-4 + 2 < 6.", "Solve a/-3 - 5 ≥ 1.", "Determine the solution set for m/-2 + 7 ≤ 0."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_and_two_step_linear_inequalities'),
('two_step_inequalities_with_fraction_coefficients', 'Two-step inequalities with fraction coefficients', 'Two-step inequalities with fraction coefficients', 'Two-step inequalities may include fractional variable coefficients that must be undone after the constant term is moved. Reversal depends on the sign of the fractional coefficient.', 'linear_equations_and_inequalities', '["Solve (2/3)x + 4 < 10.", "Solve (-1/5)a - 2 ≥ 6.", "Determine the solution set for (3/4)m + 1 ≤ -8."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_and_two_step_linear_inequalities'),
('two_step_inequalities_with_decimal_coefficients', 'Two-step inequalities with decimal coefficients', 'Two-step inequalities with decimal coefficients', 'Two-step inequalities with decimal coefficients require careful decimal arithmetic and sign-aware division. This is inequality solving with decimal coefficients.', 'linear_equations_and_inequalities', '["Solve 0.5x + 3 > 9.", "Solve -1.2a - 4 ≤ 8.", "Determine the solution set for 0.25m + 1 ≥ -2."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_and_two_step_linear_inequalities'),
('two_step_inequalities_boundary_inclusion', 'Boundary inclusion in two-step inequalities', 'Boundary inclusion in two-step inequalities', 'After solving a two-step inequality, the original symbol determines whether the boundary value is included. This targets open versus closed endpoint errors.', 'linear_equations_and_inequalities', '["Solve 2x + 3 ≤ 11 and identify whether the boundary is included.", "Solve -4a + 1 > 9 and determine the endpoint type.", "Graph the solution to 5m - 7 ≥ 18 using the correct endpoint."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_and_two_step_linear_inequalities'),
('inequality_symbol_reversal_error_recognition', 'Inequality symbol reversal errors', 'Inequality symbol reversal errors', 'The inequality symbol reverses only when multiplying or dividing by a negative number. This topic targets recognizing and correcting reversal mistakes.', 'linear_equations_and_inequalities', '["Identify the error in solving -2x < 8 as x < -4.", "Correct the inequality step from -5a ≥ 10 to a ≥ -2.", "Determine whether the symbol should reverse when solving x - 3 < 7."]'::jsonb, 'approved', 'in_depth', 'topic', 'one_and_two_step_linear_inequalities')
ON CONFLICT (id) DO NOTHING;

-- ─── multi_step_linear_inequalities topics ─────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('linear_inequalities_combining_like_terms_one_side', 'Linear inequalities requiring like-term collection on one side', 'Linear inequalities requiring like-term collection on one side', 'Some inequalities require combining like terms before isolating the variable. This mirrors multi-step equation structure with inequality direction preserved unless negative division occurs.', 'linear_equations_and_inequalities', '["Solve 3x + 2x - 4 < 16.", "Solve 8a - 5a + 7 ≥ -2.", "Determine the solution set for 6m + 1 - 2m ≤ 13."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_inequalities'),
('linear_inequalities_with_distribution_one_side', 'Linear inequalities requiring distribution on one side', 'Linear inequalities requiring distribution on one side', 'A grouped expression on one side may need distribution before the inequality can be solved. This targets inequalities such as 3(x + 2) < 15.', 'linear_equations_and_inequalities', '["Solve 3(x + 2) < 15.", "Solve 5(a - 4) ≥ 10.", "Determine the solution set for -2(m + 7) ≤ 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_inequalities'),
('linear_inequalities_with_subtracted_parentheses', 'Linear inequalities with subtracted parentheses', 'Linear inequalities with subtracted parentheses', 'Subtracted parentheses require changing signs inside the group before solving the inequality. This combines grouping errors with inequality solving.', 'linear_equations_and_inequalities', '["Solve x - (2x + 5) < 9.", "Solve 4a - (a - 3) ≥ 12.", "Determine the solution set for 7 - (3m + 1) ≤ -5."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_inequalities'),
('linear_inequalities_with_multiple_parentheses', 'Linear inequalities with multiple grouped expressions', 'Linear inequalities with multiple grouped expressions', 'Multiple grouped expressions may need to be expanded before terms are collected and the variable is isolated.', 'linear_equations_and_inequalities', '["Solve 2(x + 3) + 4(x - 1) < 20.", "Solve 5(a - 2) - 3(a + 4) ≥ 8.", "Determine the solution set for 7(m + 1) + 2(m - 5) ≤ 24."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_inequalities'),
('linear_inequalities_variables_on_both_sides', 'Linear inequalities with variables on both sides', 'Linear inequalities with variables on both sides', 'Inequalities with variable terms on both sides require moving variable terms and constants before isolating the variable. Direction reversal depends on the final negative operation.', 'linear_equations_and_inequalities', '["Solve 5x + 2 < 2x + 14.", "Solve 7a - 3 ≥ 4a + 12.", "Determine the solution set for 9m + 1 ≤ 3m - 17."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_inequalities'),
('linear_inequalities_distribution_both_sides', 'Linear inequalities requiring distribution on both sides', 'Linear inequalities requiring distribution on both sides', 'Both sides of an inequality may contain grouped expressions that must be distributed before variable terms are collected.', 'linear_equations_and_inequalities', '["Solve 3(x + 2) < 2(x + 9).", "Solve 5(a - 1) ≥ 2(a + 7).", "Determine the solution set for 4(m + 3) ≤ 6(m - 1)."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_inequalities'),
('linear_inequalities_with_fraction_coefficients', 'Multi-step linear inequalities with fraction coefficients', 'Multi-step linear inequalities with fraction coefficients', 'Fraction coefficients in multi-step inequalities require fraction arithmetic or clearing denominators. Symbol reversal occurs only when multiplying or dividing by a negative number.', 'linear_equations_and_inequalities', '["Solve (1/2)x + 3 < (3/4)x - 5.", "Solve (2/3)a - 4 ≥ (1/6)a + 1.", "Determine the solution set for (5/8)m + 2 ≤ (1/4)m - 7."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_inequalities'),
('linear_inequalities_clearing_positive_denominators', 'Clearing positive denominators in linear inequalities', 'Clearing positive denominators in linear inequalities', 'Multiplying every term by a positive common denominator removes fraction coefficients without reversing the inequality. This applies when denominators are constant and positive.', 'linear_equations_and_inequalities', '["Solve x/3 + 2 < 5 by clearing the denominator.", "Solve (1/4)a - (1/2) ≥ 3 by clearing fractions.", "Determine the positive LCD needed to clear fractions in x/6 + x/4 ≤ 5."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_inequalities'),
('linear_inequalities_with_decimal_coefficients', 'Multi-step linear inequalities with decimal coefficients', 'Multi-step linear inequalities with decimal coefficients', 'Decimal coefficients in multi-step inequalities require decimal operations or clearing decimals before solving. Reversal depends on negative multiplication or division.', 'linear_equations_and_inequalities', '["Solve 0.4x + 1.2 < 3.6.", "Solve 1.5a - 0.25 ≥ 2.75.", "Determine the solution set for 0.08m + 4 ≤ 0.2m - 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_inequalities'),
('linear_inequalities_clearing_decimal_coefficients', 'Clearing decimal coefficients in linear inequalities', 'Clearing decimal coefficients in linear inequalities', 'Multiplying every term by a positive power of 10 removes decimal coefficients without reversing the inequality. This supports cleaner integer-coefficient solving.', 'linear_equations_and_inequalities', '["Rewrite 0.5x + 1.2 < 4.7 without decimals.", "Solve 0.03a + 0.2 ≥ 0.5 by clearing decimals.", "Determine what power of 10 clears all decimals in 1.25m - 0.4 ≤ 2.6."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_inequalities'),
('linear_inequalities_special_case_no_solution', 'Linear inequalities with no solution', 'Linear inequalities with no solution', 'A linear inequality has no solution when simplification produces a false constant inequality such as 0 > 5. This usually happens after variable terms cancel.', 'linear_equations_and_inequalities', '["Solve 3x + 4 > 3x + 8.", "Solve 5(a - 2) ≤ 5a - 11.", "Determine whether 2m + 7 < 2m + 7 has no solution or infinitely many solutions."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_inequalities'),
('linear_inequalities_special_case_all_real_numbers', 'Linear inequalities true for all real numbers', 'Linear inequalities true for all real numbers', 'A linear inequality has all real numbers as solutions when simplification produces a true constant inequality such as 0 < 5. This is the inequality version of an identity case.', 'linear_equations_and_inequalities', '["Solve 4x + 6 < 4x + 10.", "Solve 7a - 5 ≥ 7a - 5.", "Determine whether 3(m + 2) ≤ 3m + 6 is true for all real numbers."]'::jsonb, 'approved', 'in_depth', 'topic', 'multi_step_linear_inequalities')
ON CONFLICT (id) DO NOTHING;

-- ─── compound_linear_inequalities topics ──────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('compound_inequalities_and_structure', 'AND compound inequality structure', 'AND compound inequality structure', 'An AND compound inequality requires values to satisfy both inequalities at the same time. Its solution set is the intersection of the two solution sets.', 'linear_equations_and_inequalities', '["Identify whether x > 2 and x < 7 is an AND compound inequality.", "Determine the values that satisfy both x ≥ -1 and x < 4.", "Graph x > 0 and x ≤ 5 on one number line."]'::jsonb, 'approved', 'in_depth', 'topic', 'compound_linear_inequalities'),
('compound_inequalities_or_structure', 'OR compound inequality structure', 'OR compound inequality structure', 'An OR compound inequality allows values that satisfy at least one inequality. Its solution set is the union of the two solution sets.', 'linear_equations_and_inequalities', '["Identify whether x < -3 or x > 5 is an OR compound inequality.", "Determine the values that satisfy x ≤ 1 or x ≥ 8.", "Graph x < 0 or x > 6 on one number line."]'::jsonb, 'approved', 'in_depth', 'topic', 'compound_linear_inequalities'),
('bounded_compound_inequalities', 'Bounded compound inequalities', 'Bounded compound inequalities', 'A bounded compound inequality places a variable between two boundary values, such as a < x < b. This represents an interval with two endpoints.', 'linear_equations_and_inequalities', '["Solve -2 < x + 1 < 6.", "Write 3 ≤ x < 9 in interval notation.", "Identify the endpoints of -5 < m ≤ 4."]'::jsonb, 'approved', 'in_depth', 'topic', 'compound_linear_inequalities'),
('three_part_inequality_solving', 'Three-part linear inequality solving', 'Three-part linear inequality solving', 'A three-part inequality requires applying the same operation to all three parts to isolate the variable in the middle. This targets forms such as a < bx + c < d.', 'linear_equations_and_inequalities', '["Solve 1 < 2x + 3 < 9.", "Solve -4 ≤ 3a - 1 < 8.", "Determine the solution set for 5 < m/2 + 1 ≤ 11."]'::jsonb, 'approved', 'in_depth', 'topic', 'compound_linear_inequalities'),
('compound_inequality_interval_intersections', 'Interval intersections for compound inequalities', 'Interval intersections for compound inequalities', 'AND compound inequalities are represented by overlapping interval regions. This topic focuses on finding the intersection of two linear inequality solution sets.', 'linear_equations_and_inequalities', '["Find the intersection of x > 1 and x ≤ 6.", "Determine the overlap of x ≥ -3 and x < 2.", "Identify the interval that satisfies both x < 10 and x > 4."]'::jsonb, 'approved', 'in_depth', 'topic', 'compound_linear_inequalities'),
('compound_inequality_interval_unions', 'Interval unions for compound inequalities', 'Interval unions for compound inequalities', 'OR compound inequalities are represented by the union of interval regions. This topic focuses on combining separate solution intervals.', 'linear_equations_and_inequalities', '["Find the union of x < -2 or x ≥ 5.", "Write x ≤ 1 or x > 8 in interval notation.", "Identify the number-line graph for x < 0 or x ≥ 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'compound_linear_inequalities'),
('compound_inequalities_no_overlap', 'Compound inequalities with no overlap', 'Compound inequalities with no overlap', 'An AND compound inequality has no solution when the required intervals do not overlap. This is a contradiction in compound inequality form.', 'linear_equations_and_inequalities', '["Determine the solution set for x < 2 and x > 5.", "Identify why x ≤ -1 and x ≥ 4 has no solution.", "Graph x > 7 and x < 3 to show no overlap."]'::jsonb, 'approved', 'in_depth', 'topic', 'compound_linear_inequalities'),
('compound_inequalities_all_real_union', 'Compound inequalities with all-real-number union', 'Compound inequalities with all-real-number union', 'An OR compound inequality may cover every real number when the combined intervals overlap or leave no gap. This is a union-based all-real-number case.', 'linear_equations_and_inequalities', '["Determine the solution set for x < 5 or x ≥ 5.", "Identify why x ≤ 2 or x > 0 includes all real numbers.", "Write the union of (-∞, 4) and [4, ∞) in interval notation."]'::jsonb, 'approved', 'in_depth', 'topic', 'compound_linear_inequalities'),
('compound_inequality_endpoint_inclusion', 'Endpoint inclusion in compound inequalities', 'Endpoint inclusion in compound inequalities', 'Each endpoint in a compound inequality may be included or excluded depending on the corresponding inequality symbol. This affects brackets, parentheses, and number-line dots.', 'linear_equations_and_inequalities', '["Determine the endpoint types in -3 ≤ x < 8.", "Write 2 < x ≤ 9 in interval notation.", "Graph -1 < m < 6 using correct endpoint symbols."]'::jsonb, 'approved', 'in_depth', 'topic', 'compound_linear_inequalities'),
('compound_inequalities_from_separate_solutions', 'Compound inequalities from separate solved inequalities', 'Compound inequalities from separate solved inequalities', 'Some compound inequalities require solving two separate inequalities before combining their solution sets with AND or OR. This focuses on solution-set combination after solving.', 'linear_equations_and_inequalities', '["Solve 2x + 1 > 7 and x - 4 < 3.", "Solve 3a - 2 ≤ 10 or -a > 5.", "Determine the combined solution for 5m + 1 ≥ 11 and m/2 < 4."]'::jsonb, 'approved', 'in_depth', 'topic', 'compound_linear_inequalities'),
('interval_notation_for_compound_inequalities', 'Interval notation for compound inequalities', 'Interval notation for compound inequalities', 'Compound inequality solution sets may be written as intervals, intersections, or unions of intervals. This focuses on notation after the solution set is known.', 'linear_equations_and_inequalities', '["Write -2 < x ≤ 5 in interval notation.", "Write x < -1 or x ≥ 4 in interval notation.", "Identify the compound inequality represented by (-3, 7]."]'::jsonb, 'approved', 'in_depth', 'topic', 'compound_linear_inequalities'),
('number_line_graphs_for_compound_inequalities', 'Number-line graphs for compound inequalities', 'Number-line graphs for compound inequalities', 'Compound inequalities can be graphed using multiple shaded regions or bounded intervals on a number line. This is one-variable solution representation only.', 'linear_equations_and_inequalities', '["Graph x ≤ -2 or x > 3 on a number line.", "Graph -4 < x ≤ 6 on a number line.", "Identify the compound inequality shown by two rays on a number line."]'::jsonb, 'approved', 'in_depth', 'topic', 'compound_linear_inequalities')
ON CONFLICT (id) DO NOTHING;

-- ─── linear_equation_and_inequality_interpretation topics ─────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('equation_vs_inequality_solution_type', 'Equation versus inequality solution type', 'Equation versus inequality solution type', 'A typical one-variable linear equation has a single solution, while a linear inequality usually has an interval or ray of solutions. This focuses on interpreting solution forms.', 'linear_equations_and_inequalities', '["Compare the solution type of x = 4 and x > 4.", "Identify whether x ≤ 7 represents one value or many values.", "Determine why 2x = 10 and 2x < 10 have different kinds of solutions."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_and_inequality_interpretation'),
('boundary_value_vs_solution_region', 'Boundary value versus solution region', 'Boundary value versus solution region', 'The boundary value is only the cutoff point, while the full inequality solution includes all values on the correct side, with possible boundary inclusion.', 'linear_equations_and_inequalities', '["Identify the boundary value and solution region for x > 3.", "Determine why x = 5 is not the full solution to x ≤ 5.", "Graph the solution region for x ≥ -2 after identifying the boundary."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_and_inequality_interpretation'),
('open_vs_closed_endpoint_meaning', 'Open versus closed endpoint meaning', 'Open versus closed endpoint meaning', 'Open endpoints exclude boundary values, while closed endpoints include them. This connects inequality symbols, number-line graphs, and interval notation.', 'linear_equations_and_inequalities', '["Identify whether x < 6 uses an open or closed endpoint.", "Determine whether [2, ∞) includes 2.", "Match x ≥ -1 to the correct endpoint type."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_and_inequality_interpretation'),
('infinity_endpoint_notation', 'Infinity endpoint notation', 'Infinity endpoint notation', 'Infinity and negative infinity always use parentheses in interval notation because they are directions, not reachable endpoints. This targets bracket errors with infinity.', 'linear_equations_and_inequalities', '["Write x < 9 in interval notation with the correct infinity symbol.", "Identify the error in writing [-∞, 4].", "Determine why x ≥ 2 is written [2, ∞)."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_and_inequality_interpretation'),
('solution_set_empty_set_notation', 'Empty solution set notation', 'Empty solution set notation', 'A contradiction has no solutions and can be represented by the empty set. This applies to no-solution equations and impossible compound inequalities.', 'linear_equations_and_inequalities', '["Write the solution set for 3x + 1 = 3x + 5.", "Identify the notation for no solution.", "Determine the solution set for x < 2 and x > 9."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_and_inequality_interpretation'),
('all_real_numbers_solution_notation', 'All real numbers solution notation', 'All real numbers solution notation', 'An identity equation or always-true inequality has every real number as a solution. This can be represented as all real numbers or (-∞, ∞).', 'linear_equations_and_inequalities', '["Write the solution set for 2(x + 3) = 2x + 6.", "Identify the interval notation for all real numbers.", "Determine whether 4x + 1 ≤ 4x + 9 is true for all real numbers."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_and_inequality_interpretation'),
('extraneous_results_from_invalid_linear_steps', 'Invalid steps causing wrong linear solutions', 'Invalid steps causing wrong linear solutions', 'Incorrect operations such as changing only one side, distributing incorrectly, or reversing inequality symbols unnecessarily can produce invalid results. This topic targets structural error diagnosis.', 'linear_equations_and_inequalities', '["Identify the invalid step in solving x + 4 = 9 by subtracting 4 from only one side.", "Correct the mistaken solution of -2x < 8 as x < -4.", "Determine why 3(x + 5) = 3x + 5 gives a wrong equation step."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_and_inequality_interpretation'),
('linear_solution_reasonableness', 'Reasonableness of linear solutions', 'Reasonableness of linear solutions', 'A solved value or inequality can be checked for reasonableness using substitution, sign, boundary behavior, or comparison to the original structure.', 'linear_equations_and_inequalities', '["Check whether x = 100 is reasonable for 2x + 1 = 9.", "Determine whether the solution x > 4 makes sense for -x < -4.", "Verify a solved inequality by testing a value inside and outside the solution region."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_equation_and_inequality_interpretation')
ON CONFLICT (id) DO NOTHING;
