-- Category
INSERT INTO learn_categories (id, name, description, order_index)
VALUES ('systems_of_equations', 'Systems of Equations', 'Solving and interpreting systems of linear and nonlinear equations and inequalities.', 4)
ON CONFLICT (id) DO NOTHING;

-- ─── Umbrella keywords ────────────────────────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('systems_foundations_and_solution_sets', 'Systems Foundations and Solution Sets', 'Systems Foundations and Solution Sets', 'Core structure of systems, including simultaneous solutions, ordered-pair or ordered-triple solutions, verification, and solution-set types.', 'systems_of_equations', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('graphical_systems_of_linear_equations', 'Graphical Systems of Linear Equations', 'Graphical Systems of Linear Equations', 'Solving and interpreting two-variable linear systems through line intersections, parallel lines, coincident lines, and coordinate-plane graphs.', 'systems_of_equations', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('substitution_method_linear_systems', 'Substitution Method for Linear Systems', 'Substitution Method for Linear Systems', 'Solving linear systems by replacing one variable expression with an equivalent expression from another equation.', 'systems_of_equations', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('elimination_method_linear_systems', 'Elimination Method for Linear Systems', 'Elimination Method for Linear Systems', 'Solving linear systems by combining equations to remove one variable and create a one-variable equation.', 'systems_of_equations', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('linear_system_preparation_and_structure', 'Linear System Preparation and Structure', 'Linear System Preparation and Structure', 'Rewriting system equations into useful forms before solving, including clearing denominators, clearing decimals, distributing, collecting terms, and recognizing equivalent equations.', 'systems_of_equations', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('special_case_and_parameter_linear_systems', 'Special-Case and Parameter Linear Systems', 'Special-Case and Parameter Linear Systems', 'Systems whose solution type depends on coefficient relationships, equivalent equations, contradictions, or unknown parameters.', 'systems_of_equations', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('three_variable_linear_systems_non_matrix', 'Three-Variable Linear Systems Without Matrices', 'Three-Variable Linear Systems Without Matrices', 'Solving and interpreting linear systems in three variables using substitution and elimination without matrix notation, row reduction, determinants, or inverse matrices.', 'systems_of_equations', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('systems_of_linear_inequalities', 'Systems of Linear Inequalities', 'Systems of Linear Inequalities', 'Coordinate-plane solution regions satisfying two or more linear inequalities, including boundary lines, shading, overlap, and feasible regions.', 'systems_of_equations', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('nonlinear_systems_of_equations', 'Nonlinear Systems of Equations', 'Nonlinear Systems of Equations', 'Systems involving at least one nonlinear equation, interpreted through intersections and solved using substitution or elimination when appropriate.', 'systems_of_equations', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('structured_linear_system_relationships', 'Structured Linear System Relationships', 'Structured Linear System Relationships', 'Common algebraic relationship patterns that naturally form systems, described by their mathematical structure rather than by word-problem context.', 'systems_of_equations', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL)
ON CONFLICT (id) DO NOTHING;

-- ─── systems_foundations_and_solution_sets topics ─────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('system_of_equations_structure', 'System of equations structure', 'System of equations structure', 'A system of equations is a set of two or more equations that must be considered together. This focuses on recognizing a system as multiple simultaneous conditions, not solving a single equation.', 'systems_of_equations', '["Identify the two equations in the system y = 2x + 1 and y = -x + 7.", "Classify x + y = 8 and x - y = 2 as a system of equations.", "Determine whether 3x + 4 = 10 is a system or a single equation."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_foundations_and_solution_sets'),
('simultaneous_solution_meaning', 'Simultaneous solution meaning', 'Simultaneous solution meaning', 'A solution to a system must satisfy every equation in the system at the same time. This distinguishes system solutions from values that satisfy only one equation.', 'systems_of_equations', '["Determine whether (2, 5) satisfies both y = 2x + 1 and x + y = 7.", "Identify why a point that satisfies only one equation is not a system solution.", "Classify (3, 4) as a solution or non-solution of a given two-equation system."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_foundations_and_solution_sets'),
('ordered_pair_solutions_to_two_variable_systems', 'Ordered-pair solutions to two-variable systems', 'Ordered-pair solutions to two-variable systems', 'A solution to a two-variable system is usually written as an ordered pair (x, y). The order matters because each coordinate corresponds to a different variable.', 'systems_of_equations', '["Identify the x-value and y-value in the solution (4, -1).", "Determine whether (2, 7) and (7, 2) represent the same system solution.", "Write the solution x = -3 and y = 5 as an ordered pair."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_foundations_and_solution_sets'),
('ordered_triple_solutions_to_three_variable_systems', 'Ordered-triple solutions to three-variable systems', 'Ordered-triple solutions to three-variable systems', 'A solution to a three-variable system is written as an ordered triple (x, y, z). Each coordinate must match the correct variable position.', 'systems_of_equations', '["Identify the x-, y-, and z-values in the solution (2, -1, 5).", "Write x = 4, y = 0, and z = -3 as an ordered triple.", "Determine whether (1, 2, 3) and (3, 2, 1) represent the same ordered triple."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_foundations_and_solution_sets'),
('solution_verification_two_variable_systems', 'Solution verification for two-variable systems', 'Solution verification for two-variable systems', 'A proposed ordered pair is checked by substituting the x- and y-values into every equation in the system. This targets checking both equations, not just one.', 'systems_of_equations', '["Check whether (3, 2) solves x + y = 5 and 2x - y = 4.", "Verify whether (-1, 6) satisfies y = -2x + 4 and x + y = 5.", "Determine whether (0, -3) is a solution to both equations in a system."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_foundations_and_solution_sets'),
('solution_verification_three_variable_systems', 'Solution verification for three-variable systems', 'Solution verification for three-variable systems', 'A proposed ordered triple is checked by substituting all three values into every equation in the system. This targets complete verification across multiple equations.', 'systems_of_equations', '["Check whether (1, 2, 3) solves x + y + z = 6 and 2x - y + z = 3.", "Verify whether (0, -1, 4) satisfies all equations in a three-variable system.", "Determine which ordered triple solves a given system of three equations."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_foundations_and_solution_sets'),
('system_solution_as_intersection', 'System solution as intersection', 'System solution as intersection', 'A system solution represents the point or set of points where the graphs of the equations intersect. This connects algebraic solutions to geometric meaning.', 'systems_of_equations', '["Identify the solution of two lines as their intersection point.", "Determine what the intersection of y = x + 1 and y = -x + 5 represents.", "Classify the point where two graphs cross as a solution to the system."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_foundations_and_solution_sets'),
('consistent_systems', 'Consistent systems', 'Consistent systems', 'A consistent system has at least one solution. This includes systems with exactly one solution and systems with infinitely many solutions.', 'systems_of_equations', '["Classify a system with one intersection point as consistent or inconsistent.", "Determine whether a system with infinitely many solutions is consistent.", "Identify whether two intersecting lines form a consistent system."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_foundations_and_solution_sets'),
('inconsistent_systems', 'Inconsistent systems', 'Inconsistent systems', 'An inconsistent system has no solution because no ordered pair or ordered triple satisfies all equations at once. In two-variable linear systems, this often means parallel lines.', 'systems_of_equations', '["Classify two parallel lines with different y-intercepts as inconsistent.", "Determine whether x + y = 4 and x + y = 9 can both be true.", "Identify the solution type of a system that simplifies to 0 = 5."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_foundations_and_solution_sets'),
('independent_linear_systems', 'Independent linear systems', 'Independent linear systems', 'An independent two-variable linear system has exactly one solution because the equations represent distinct intersecting lines. This differs from dependent or inconsistent systems.', 'systems_of_equations', '["Classify a system of two lines that intersect once as independent.", "Determine whether y = 2x + 1 and y = -x + 7 form an independent system.", "Identify the solution type of two nonparallel, nonidentical lines."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_foundations_and_solution_sets'),
('dependent_linear_systems', 'Dependent linear systems', 'Dependent linear systems', 'A dependent linear system has infinitely many solutions because the equations represent the same line or equivalent relationship. This differs from one-solution systems.', 'systems_of_equations', '["Classify y = 2x + 3 and 2y = 4x + 6 as dependent or independent.", "Determine the solution type when two equations simplify to the same equation.", "Identify whether 3x + 6y = 12 and x + 2y = 4 represent the same line."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_foundations_and_solution_sets'),
('system_solution_set_notation', 'System solution-set notation', 'System solution-set notation', 'System solutions can be represented as ordered pairs, ordered triples, no solution, infinitely many solutions, or a set notation statement. This focuses on final-answer structure.', 'systems_of_equations', '["Write the solution x = 2 and y = -5 as an ordered pair.", "Represent a no-solution system using appropriate notation.", "Identify whether {(3, 1)} represents one solution or many solutions."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_foundations_and_solution_sets'),
('variables_and_equations_count_in_systems', 'Number of variables and equations in systems', 'Number of variables and equations in systems', 'Systems can contain different numbers of equations and variables, which affects possible solution behavior. This focuses on recognizing system size and structure before choosing a method.', 'systems_of_equations', '["Identify the number of variables in a system with equations x + y = 5 and 2x - y = 1.", "Determine whether a system has two or three variables.", "Classify a system of three equations in x, y, and z by its number of variables."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_foundations_and_solution_sets'),
('equivalent_systems', 'Equivalent systems', 'Equivalent systems', 'Equivalent systems have the same solution set, even if the equations are rewritten. Valid transformations include replacing an equation with an equivalent equation or combining equations without changing solutions.', 'systems_of_equations', '["Determine whether x + y = 6 and 2x + 2y = 12 preserve the same relationship.", "Identify whether multiplying one equation by 3 changes the solution set of a system.", "Classify two systems as equivalent when they have the same ordered-pair solution."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_foundations_and_solution_sets')
ON CONFLICT (id) DO NOTHING;

-- ─── graphical_systems_of_linear_equations topics ─────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('linear_system_graphical_intersection', 'Graphical intersection of two lines', 'Graphical intersection of two lines', 'The graphical solution of a two-variable linear system is the point where the two lines intersect. This focuses on reading the intersection as an ordered pair.', 'systems_of_equations', '["Identify the solution of a graphed system from the intersection point.", "Determine the ordered pair where two graphed lines cross.", "Read the solution of y = x + 2 and y = -x + 6 from a graph."]'::jsonb, 'approved', 'in_depth', 'topic', 'graphical_systems_of_linear_equations'),
('graphing_systems_from_slope_intercept_form', 'Graphing systems from slope-intercept form', 'Graphing systems from slope-intercept form', 'A system written in slope-intercept form can be graphed by using each line''s slope and y-intercept. This is specific to systems, not general single-line graphing.', 'systems_of_equations', '["Graph y = 2x + 1 and y = -x + 7 to find their intersection.", "Identify the solution of a system where both equations are written as y = mx + b.", "Determine the intersection of two slope-intercept lines from their graph."]'::jsonb, 'approved', 'in_depth', 'topic', 'graphical_systems_of_linear_equations'),
('graphing_systems_from_standard_form', 'Graphing systems from standard form', 'Graphing systems from standard form', 'A system in standard form can be graphed by finding intercepts or rewriting each equation. This targets systems where equations are not already solved for y.', 'systems_of_equations', '["Graph x + y = 6 and 2x - y = 3 to find the solution.", "Rewrite two standard-form equations before graphing their system.", "Identify the intersection of 3x + y = 9 and x - y = 1 from a graph."]'::jsonb, 'approved', 'in_depth', 'topic', 'graphical_systems_of_linear_equations'),
('graphing_systems_with_horizontal_lines', 'Graphing systems with horizontal lines', 'Graphing systems with horizontal lines', 'Systems may include equations of the form y = c, which graph as horizontal lines. This focuses on intersections involving a fixed y-value.', 'systems_of_equations', '["Find the intersection of y = 4 and y = 2x - 6.", "Graph y = -3 with x + y = 5 to solve the system.", "Determine the solution of a system containing the horizontal line y = 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'graphical_systems_of_linear_equations'),
('graphing_systems_with_vertical_lines', 'Graphing systems with vertical lines', 'Graphing systems with vertical lines', 'Systems may include equations of the form x = c, which graph as vertical lines. This focuses on intersections involving a fixed x-value.', 'systems_of_equations', '["Find the intersection of x = 3 and y = 2x + 1.", "Graph x = -2 with x + y = 5 to solve the system.", "Determine the solution of a system containing the vertical line x = 4."]'::jsonb, 'approved', 'in_depth', 'topic', 'graphical_systems_of_linear_equations'),
('graphical_parallel_lines_no_solution', 'Parallel lines and no solution', 'Parallel lines and no solution', 'Two distinct parallel lines never intersect, so their system has no solution. This connects equal slopes and different intercepts to inconsistency.', 'systems_of_equations', '["Identify the solution type of y = 2x + 1 and y = 2x - 5.", "Classify a graphed system of parallel lines as having no solution.", "Determine why two lines with the same slope and different y-intercepts do not solve as an ordered pair."]'::jsonb, 'approved', 'in_depth', 'topic', 'graphical_systems_of_linear_equations'),
('graphical_coincident_lines_infinite_solutions', 'Coincident lines and infinitely many solutions', 'Coincident lines and infinitely many solutions', 'Coincident lines lie exactly on top of each other, so every point on the line satisfies both equations. This is the graphical form of a dependent system.', 'systems_of_equations', '["Identify the solution type of y = 3x - 2 and 2y = 6x - 4.", "Classify a graphed system where both equations form the same line.", "Determine why two identical lines have infinitely many solutions."]'::jsonb, 'approved', 'in_depth', 'topic', 'graphical_systems_of_linear_equations'),
('estimating_system_solutions_from_graphs', 'Estimating system solutions from graphs', 'Estimating system solutions from graphs', 'When an intersection does not land exactly on grid lines, the graphical solution may be estimated. This distinguishes approximate graphical solving from exact algebraic solving.', 'systems_of_equations', '["Estimate the intersection point of two graphed lines.", "Approximate the solution of a linear system from a coordinate grid.", "Determine whether a graph gives an exact or estimated system solution."]'::jsonb, 'approved', 'in_depth', 'topic', 'graphical_systems_of_linear_equations'),
('exact_vs_approximate_system_solutions', 'Exact versus approximate system solutions', 'Exact versus approximate system solutions', 'Some system solutions can be read exactly from a graph, while others require algebra for exact values. This targets recognizing limits of graphical methods.', 'systems_of_equations', '["Identify whether the graphed intersection at (2, 5) is exact or approximate.", "Determine why an intersection between grid lines may need algebraic solving.", "Classify a decimal intersection read from a graph as exact or approximate."]'::jsonb, 'approved', 'in_depth', 'topic', 'graphical_systems_of_linear_equations'),
('graph_scale_in_system_solution_reading', 'Graph scale in system solution reading', 'Graph scale in system solution reading', 'Reading a graphical system solution depends on the coordinate scale and tick marks. This targets errors caused by misreading axes.', 'systems_of_equations', '["Read the intersection point of two lines using the given axis scale.", "Determine the ordered pair of a system solution from a graph with tick marks of 2.", "Identify why the same point may be misread when the graph scale changes."]'::jsonb, 'approved', 'in_depth', 'topic', 'graphical_systems_of_linear_equations'),
('line_intersection_outside_viewing_window', 'Line intersection outside the viewing window', 'Line intersection outside the viewing window', 'Two lines may intersect outside the visible graph window, so a graph can appear misleading if the window is too small. This focuses on interpreting incomplete graphical evidence.', 'systems_of_equations', '["Determine whether two graphed line segments might intersect outside the window.", "Identify why a visible graph may not show the solution of a system.", "Classify a system as unresolved from a graph when the intersection is off-screen."]'::jsonb, 'approved', 'in_depth', 'topic', 'graphical_systems_of_linear_equations')
ON CONFLICT (id) DO NOTHING;

-- ─── substitution_method_linear_systems topics ────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('substitution_method_explicit_variable', 'Substitution with an explicit variable expression', 'Substitution with an explicit variable expression', 'When one equation already gives a variable explicitly, that expression can replace the variable in the other equation. This is the simplest substitution structure.', 'systems_of_equations', '["Solve y = 2x + 1 and x + y = 10 by substitution.", "Substitute y = x - 4 into 3x + y = 8.", "Determine the solution of x = 5 - y and 2x + y = 7."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_method_linear_systems'),
('substitution_after_isolating_variable', 'Substitution after isolating a variable', 'Substitution after isolating a variable', 'If neither equation is already solved for a variable, one variable can be isolated first and then substituted into the other equation. This focuses on preparing for substitution.', 'systems_of_equations', '["Solve x + y = 9 and 2x - y = 3 by first isolating y.", "Rewrite 3x + y = 10 for y before substituting into x - 2y = 4.", "Isolate x in x + 4y = 12 before using substitution."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_method_linear_systems'),
('substitution_into_standard_form_equation', 'Substitution into a standard-form equation', 'Substitution into a standard-form equation', 'A solved expression for one variable may be substituted into an equation written in standard form. This targets correct replacement inside expressions like ax + by = c.', 'systems_of_equations', '["Substitute y = x + 2 into 3x + 2y = 16.", "Solve x = 4 - y and 5x - 2y = 1.", "Determine the result of replacing x with 2y - 3 in 4x + y = 10."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_method_linear_systems'),
('substitution_with_negative_expressions', 'Substitution with negative expressions', 'Substitution with negative expressions', 'Substitution may involve replacing a variable with a negative expression or substituting into a term with a negative coefficient. This targets sign and parentheses errors.', 'systems_of_equations', '["Substitute y = -2x + 5 into x - y = 7.", "Solve x = -y + 3 and 2x + y = 8.", "Determine the correct substitution step for -3y when y = x - 4."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_method_linear_systems'),
('substitution_with_fraction_coefficients', 'Substitution with fraction coefficients', 'Substitution with fraction coefficients', 'Linear systems solved by substitution may produce or contain fractional coefficients. This requires careful fraction arithmetic after replacement.', 'systems_of_equations', '["Solve y = 1/2 x + 3 and x + y = 9.", "Substitute x = 2/3 y - 1 into 3x + y = 5.", "Determine the solution of y = -1/4 x and x - 2y = 12."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_method_linear_systems'),
('substitution_with_decimal_coefficients', 'Substitution with decimal coefficients', 'Substitution with decimal coefficients', 'Linear systems solved by substitution may involve decimal coefficients. This targets decimal arithmetic inside the substitution method.', 'systems_of_equations', '["Solve y = 0.5x + 2 and x + y = 11.", "Substitute x = 1.2y - 4 into 2x + y = 10.", "Determine the solution of y = -0.25x + 3 and x - y = 5."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_method_linear_systems'),
('substitution_leading_to_one_variable_equation', 'Substitution leading to a one-variable equation', 'Substitution leading to a one-variable equation', 'After substitution, the system becomes a one-variable linear equation. This topic focuses on recognizing and solving the resulting equation structure.', 'systems_of_equations', '["Substitute y = 3x - 1 into x + y = 11 and solve the resulting equation.", "Identify the one-variable equation formed from y = x + 5 and 2x + y = 14.", "Determine the equation in x after replacing y in 4x - y = 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_method_linear_systems'),
('back_substitution_in_two_variable_systems', 'Back substitution in two-variable systems', 'Back substitution in two-variable systems', 'After one variable is found, it must be substituted back into an original or equivalent equation to find the other variable. This targets incomplete solutions with only one coordinate.', 'systems_of_equations', '["Find y after solving x = 3 in the system y = 2x + 1.", "Use x = -2 to determine y in x + y = 7.", "Complete the ordered pair after finding one variable by substitution."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_method_linear_systems'),
('substitution_method_no_solution_case', 'No-solution case by substitution', 'No-solution case by substitution', 'Substitution can produce a false statement such as 0 = 5, showing that the system has no solution. This is the substitution-method form of inconsistency.', 'systems_of_equations', '["Use substitution to classify y = 2x + 3 and y = 2x - 4.", "Identify the solution type when substitution gives 7 = -1.", "Determine whether a system has no solution after the variable terms cancel."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_method_linear_systems'),
('substitution_method_dependent_case', 'Dependent case by substitution', 'Dependent case by substitution', 'Substitution can produce a true statement such as 0 = 0, showing that the equations are equivalent and the system has infinitely many solutions.', 'systems_of_equations', '["Use substitution to classify y = x + 2 and 2y = 2x + 4.", "Identify the solution type when substitution gives 5 = 5.", "Determine whether a system is dependent after all variable terms cancel."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_method_linear_systems'),
('choosing_substitution_when_coefficient_is_one', 'Choosing substitution when a coefficient is 1', 'Choosing substitution when a coefficient is 1', 'Substitution is often efficient when one variable has coefficient 1 or -1, because isolating that variable avoids fractions. This is method selection based on system structure.', 'systems_of_equations', '["Choose a variable to isolate in x + 3y = 10 and 2x - y = 5.", "Identify why substitution is efficient for y = 4x - 7 and x + y = 8.", "Determine which equation is easiest to solve for a variable before substituting."]'::jsonb, 'approved', 'in_depth', 'topic', 'substitution_method_linear_systems')
ON CONFLICT (id) DO NOTHING;

-- ─── elimination_method_linear_systems topics ─────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('elimination_with_opposite_coefficients', 'Elimination with opposite coefficients', 'Elimination with opposite coefficients', 'A variable can be eliminated immediately when its coefficients are opposites in the two equations. This is the most direct elimination structure.', 'systems_of_equations', '["Solve x + y = 9 and x - y = 3 by elimination.", "Eliminate y from 2x + 5y = 14 and 3x - 5y = 6.", "Identify which variable cancels in 4a - b = 7 and 2a + b = 5."]'::jsonb, 'approved', 'in_depth', 'topic', 'elimination_method_linear_systems'),
('elimination_with_matching_coefficients', 'Elimination with matching coefficients', 'Elimination with matching coefficients', 'A variable can be eliminated by subtracting equations when its coefficients match. This differs from adding equations with opposite coefficients.', 'systems_of_equations', '["Solve 3x + 2y = 10 and x + 2y = 4 by elimination.", "Eliminate x from 5x + y = 8 and 5x - 3y = 20.", "Determine which equations should be subtracted to eliminate a variable."]'::jsonb, 'approved', 'in_depth', 'topic', 'elimination_method_linear_systems'),
('elimination_by_adding_equations', 'Elimination by adding equations', 'Elimination by adding equations', 'Adding equations can eliminate a variable when its coefficients are additive inverses. This focuses on the addition version of elimination.', 'systems_of_equations', '["Add the equations 2x + y = 7 and 3x - y = 8 to eliminate y.", "Solve a system by adding equations with opposite x-coefficients.", "Determine the new equation after adding 4x - 3y = 5 and -4x + y = 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'elimination_method_linear_systems'),
('elimination_by_subtracting_equations', 'Elimination by subtracting equations', 'Elimination by subtracting equations', 'Subtracting equations can eliminate a variable when its coefficients are the same. This targets sign errors from subtracting an entire equation.', 'systems_of_equations', '["Subtract equations to eliminate y from 2x + y = 9 and x + y = 4.", "Solve a system where both equations have 3x as a term.", "Determine the result of subtracting x - 2y = 5 from 4x - 2y = 11."]'::jsonb, 'approved', 'in_depth', 'topic', 'elimination_method_linear_systems'),
('elimination_by_multiplying_one_equation', 'Elimination by multiplying one equation', 'Elimination by multiplying one equation', 'One equation may need to be multiplied by a constant so one variable has matching or opposite coefficients. This is common when only one equation needs scaling.', 'systems_of_equations', '["Solve x + 2y = 7 and 3x + y = 11 by multiplying one equation.", "Multiply one equation to eliminate x from 2x + y = 5 and 6x - 4y = 8.", "Determine what to multiply x + 3y = 4 by to match the y-coefficient in 2x - 6y = 10."]'::jsonb, 'approved', 'in_depth', 'topic', 'elimination_method_linear_systems'),
('elimination_by_multiplying_both_equations', 'Elimination by multiplying both equations', 'Elimination by multiplying both equations', 'Both equations may need to be multiplied by constants to create matching or opposite coefficients. This often uses the least common multiple of coefficients.', 'systems_of_equations', '["Solve 2x + 3y = 13 and 5x - 4y = 2 by multiplying both equations.", "Create opposite x-coefficients for 3x + 2y = 8 and 4x - y = 5.", "Determine multipliers that make the y-coefficients cancel in 5x + 6y = 12 and 7x - 4y = 9."]'::jsonb, 'approved', 'in_depth', 'topic', 'elimination_method_linear_systems'),
('choosing_variable_to_eliminate', 'Choosing a variable to eliminate', 'Choosing a variable to eliminate', 'The variable chosen for elimination should usually be the one with coefficients easiest to match or cancel. This is method efficiency within elimination.', 'systems_of_equations', '["Choose which variable to eliminate in 2x + y = 5 and 3x - y = 7.", "Identify the easier variable to eliminate in 4x + 6y = 10 and 2x - 3y = 1.", "Determine whether x or y requires smaller multipliers to eliminate."]'::jsonb, 'approved', 'in_depth', 'topic', 'elimination_method_linear_systems'),
('elimination_with_negative_coefficients', 'Elimination with negative coefficients', 'Elimination with negative coefficients', 'Negative coefficients require careful sign handling when equations are added, subtracted, or scaled. This targets common errors in elimination arithmetic.', 'systems_of_equations', '["Solve -2x + 3y = 7 and 2x + y = 9 by elimination.", "Eliminate y from 4x - 5y = 11 and 3x + 5y = 4.", "Determine the sign of each term after multiplying -x + 2y = 6 by -3."]'::jsonb, 'approved', 'in_depth', 'topic', 'elimination_method_linear_systems'),
('elimination_with_fraction_coefficients', 'Elimination with fraction coefficients', 'Elimination with fraction coefficients', 'Systems with fraction coefficients can be solved by elimination directly or by clearing fractions first. This focuses on fractional coefficient handling in systems.', 'systems_of_equations', '["Solve 1/2 x + y = 5 and x - y = 1 by elimination.", "Clear fractions before eliminating in 2/3 a + b = 4 and a - 1/2 b = 3.", "Determine the multiplier needed to eliminate x in 1/3 x + y = 2 and 2/3 x - y = 5."]'::jsonb, 'approved', 'in_depth', 'topic', 'elimination_method_linear_systems'),
('elimination_with_decimal_coefficients', 'Elimination with decimal coefficients', 'Elimination with decimal coefficients', 'Systems with decimal coefficients can be solved by elimination directly or by clearing decimals first. This targets decimal coefficient systems.', 'systems_of_equations', '["Solve 0.5x + y = 6 and x - y = 2 by elimination.", "Clear decimals before eliminating in 1.2a + 0.4b = 8 and 0.6a - b = 3.", "Determine a multiplier that eliminates x in 0.25x + y = 5 and 0.5x - y = 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'elimination_method_linear_systems'),
('elimination_creating_one_variable_equation', 'Elimination creating a one-variable equation', 'Elimination creating a one-variable equation', 'After one variable cancels, elimination produces a one-variable linear equation. This topic focuses on interpreting and solving the resulting equation.', 'systems_of_equations', '["Identify the one-variable equation formed after adding 2x + y = 7 and x - y = 5.", "Solve the equation created after eliminating y from a system.", "Determine the remaining variable after x-coefficients cancel."]'::jsonb, 'approved', 'in_depth', 'topic', 'elimination_method_linear_systems'),
('back_substitution_after_elimination', 'Back substitution after elimination', 'Back substitution after elimination', 'After elimination finds one variable, that value must be substituted into an original or equivalent equation to find the other variable. This targets completing the ordered pair.', 'systems_of_equations', '["Find y after elimination gives x = 4 in x + y = 10.", "Use a = -2 to find b in 3a + b = 7.", "Complete the solution of a system after one variable is found by elimination."]'::jsonb, 'approved', 'in_depth', 'topic', 'elimination_method_linear_systems'),
('elimination_method_no_solution_case', 'No-solution case by elimination', 'No-solution case by elimination', 'Elimination can produce a false statement such as 0 = 8, showing that the system is inconsistent. This is the elimination-method form of no solution.', 'systems_of_equations', '["Use elimination to classify x + y = 4 and x + y = 9.", "Identify the solution type when elimination gives 0 = -6.", "Determine whether a system has no solution after both variables cancel."]'::jsonb, 'approved', 'in_depth', 'topic', 'elimination_method_linear_systems'),
('elimination_method_dependent_case', 'Dependent case by elimination', 'Dependent case by elimination', 'Elimination can produce a true statement such as 0 = 0, showing that the system has infinitely many solutions. This is the elimination-method form of dependence.', 'systems_of_equations', '["Use elimination to classify 2x + 4y = 10 and x + 2y = 5.", "Identify the solution type when elimination gives 0 = 0.", "Determine whether two equations represent the same line after all terms cancel."]'::jsonb, 'approved', 'in_depth', 'topic', 'elimination_method_linear_systems')
ON CONFLICT (id) DO NOTHING;

-- ─── linear_system_preparation_and_structure topics ───────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('standard_form_linear_systems', 'Standard-form linear systems', 'Standard-form linear systems', 'A standard-form two-variable linear system uses equations such as ax + by = c. This structure is especially useful for elimination.', 'systems_of_equations', '["Identify whether 3x + 2y = 8 and x - y = 4 are in standard form.", "Rewrite y = 2x + 5 into standard form for a system.", "Classify a system as standard form or slope-intercept form."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_system_preparation_and_structure'),
('slope_intercept_form_linear_systems', 'Slope-intercept form linear systems', 'Slope-intercept form linear systems', 'A slope-intercept form system has equations written as y = mx + b. This structure is useful for graphing and direct substitution.', 'systems_of_equations', '["Identify whether y = 3x - 1 and y = -x + 7 are in slope-intercept form.", "Rewrite 2x + y = 9 as y = mx + b for a system.", "Determine which equation is easiest to substitute when it is solved for y."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_system_preparation_and_structure'),
('clearing_denominators_in_linear_systems', 'Clearing denominators in linear systems', 'Clearing denominators in linear systems', 'Multiplying an equation by a common denominator can remove fraction coefficients before solving a system. This applies when denominators are constants.', 'systems_of_equations', '["Clear denominators in x/2 + y/3 = 5 before solving a system.", "Rewrite 1/4 x - 1/2 y = 3 without fractions.", "Determine the least common denominator needed for 2/3 x + 1/6 y = 4."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_system_preparation_and_structure'),
('clearing_decimals_in_linear_systems', 'Clearing decimals in linear systems', 'Clearing decimals in linear systems', 'Multiplying an equation by a power of 10 can remove decimal coefficients before solving a system. This supports cleaner substitution or elimination.', 'systems_of_equations', '["Rewrite 0.5x + 0.2y = 4 without decimals.", "Clear decimals in 1.25a - 0.4b = 3.", "Determine what power of 10 removes all decimals from 0.03x + 0.7y = 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_system_preparation_and_structure'),
('distribution_before_solving_systems', 'Distribution before solving systems', 'Distribution before solving systems', 'A system equation may need distribution before variables and constants can be aligned. This targets grouped expressions inside system equations.', 'systems_of_equations', '["Expand 2(x + y) = 10 before solving a system.", "Rewrite 3(x - 2y) = 12 in standard form.", "Distribute in 5(a + 1) - b = 9 before using elimination."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_system_preparation_and_structure'),
('like_term_collection_before_solving_systems', 'Like-term collection before solving systems', 'Like-term collection before solving systems', 'A system equation may need like terms collected before applying substitution or elimination. This focuses on simplifying each equation first.', 'systems_of_equations', '["Combine terms in 3x + 2y - x = 8 before solving.", "Rewrite 5a - 2a + b = 10 in simpler form.", "Collect like terms in 4m + n - 2m + 3n = 12."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_system_preparation_and_structure'),
('variables_on_both_sides_in_system_equations', 'Variables on both sides in system equations', 'Variables on both sides in system equations', 'A system equation may have variables on both sides and must be rearranged before substitution or elimination. This targets equations such as 2x + y = x - 3y.', 'systems_of_equations', '["Rewrite 2x + y = x - 3y in standard form.", "Move variables to one side in a system equation before solving.", "Transform 4a - b = 2a + 5 into a standard-form equation."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_system_preparation_and_structure'),
('equation_scaling_in_systems', 'Equation scaling in systems', 'Equation scaling in systems', 'Multiplying an entire equation in a system by a nonzero constant preserves its solution set. This is the foundation of elimination scaling.', 'systems_of_equations', '["Determine whether multiplying x + y = 6 by 3 changes its solutions.", "Rewrite 2x - y = 5 after scaling the entire equation by -2.", "Identify why only one side of an equation cannot be multiplied during system solving."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_system_preparation_and_structure'),
('equivalent_equations_within_systems', 'Equivalent equations within systems', 'Equivalent equations within systems', 'An equation inside a system may be replaced by an equivalent equation without changing the system''s solution set. This supports rewriting before solving.', 'systems_of_equations', '["Determine whether x + y = 5 and 2x + 2y = 10 represent the same equation.", "Replace 3x - 6y = 12 with an equivalent simpler equation.", "Identify an equivalent form of 4a + 8b = 20 for use in a system."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_system_preparation_and_structure'),
('method_selection_substitution_vs_elimination', 'Method selection: substitution versus elimination', 'Method selection: substitution versus elimination', 'Substitution is often efficient when a variable is isolated or easy to isolate, while elimination is often efficient when coefficients align or can align. This is strategy selection based on system structure.', 'systems_of_equations', '["Choose a method for y = 2x + 1 and 3x + y = 10.", "Determine whether substitution or elimination is more efficient for 4x + 3y = 8 and 2x - 3y = 6.", "Identify the solving method suggested by a system with opposite y-coefficients."]'::jsonb, 'approved', 'in_depth', 'topic', 'linear_system_preparation_and_structure')
ON CONFLICT (id) DO NOTHING;

-- ─── special_case_and_parameter_linear_systems topics ─────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('same_slope_different_intercepts_systems', 'Same slope, different intercepts', 'Same slope, different intercepts', 'Two lines with the same slope but different y-intercepts are parallel and form a no-solution system. This is a coefficient-pattern route to inconsistency.', 'systems_of_equations', '["Classify y = 3x + 2 and y = 3x - 5 by solution type.", "Determine why two lines with equal slopes and different intercepts do not intersect.", "Identify the solution type of y = -x + 4 and y = -x - 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'special_case_and_parameter_linear_systems'),
('same_slope_same_intercept_systems', 'Same slope, same intercept', 'Same slope, same intercept', 'Two slope-intercept equations with the same slope and same intercept represent the same line and have infinitely many solutions.', 'systems_of_equations', '["Classify y = 2x + 7 and y = 2x + 7 by solution type.", "Determine why identical slope-intercept equations are dependent.", "Identify the solution type of y = -4x + 1 and 2y = -8x + 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'special_case_and_parameter_linear_systems'),
('proportional_coefficients_dependent_systems', 'Proportional coefficients in dependent systems', 'Proportional coefficients in dependent systems', 'In standard form, if all corresponding coefficients and constants are proportional, the equations represent the same line. This indicates infinitely many solutions.', 'systems_of_equations', '["Determine whether 2x + 4y = 10 and x + 2y = 5 are dependent.", "Identify the solution type of 3x - 6y = 9 and x - 2y = 3.", "Classify a system where every term in one equation is twice the corresponding term in the other."]'::jsonb, 'approved', 'in_depth', 'topic', 'special_case_and_parameter_linear_systems'),
('proportional_coefficients_inconsistent_systems', 'Proportional variable coefficients with nonproportional constants', 'Proportional variable coefficients with nonproportional constants', 'In standard form, if variable coefficients are proportional but constants are not, the lines are parallel and the system has no solution.', 'systems_of_equations', '["Classify 2x + 4y = 10 and x + 2y = 9 by solution type.", "Determine why 3x - 6y = 12 and x - 2y = 1 are inconsistent.", "Identify a no-solution system from proportional variable coefficients."]'::jsonb, 'approved', 'in_depth', 'topic', 'special_case_and_parameter_linear_systems'),
('nonproportional_coefficients_one_solution_systems', 'Nonproportional coefficients and one solution', 'Nonproportional coefficients and one solution', 'In a two-variable linear system, nonproportional variable coefficients usually indicate distinct nonparallel lines with exactly one solution.', 'systems_of_equations', '["Classify 2x + 3y = 7 and 4x - y = 1 by solution type.", "Determine why nonproportional coefficients suggest one intersection.", "Identify whether a standard-form system has one solution from its coefficient ratios."]'::jsonb, 'approved', 'in_depth', 'topic', 'special_case_and_parameter_linear_systems'),
('parameter_values_for_no_solution_systems', 'Parameter values for no-solution systems', 'Parameter values for no-solution systems', 'A parameter in a linear system can make equations parallel and inconsistent. This topic focuses on finding parameter values that create no solution.', 'systems_of_equations', '["Find k so y = 2x + 3 and y = kx - 4 have no solution.", "Determine the value of a that makes ax + 2y = 5 parallel to 3x + 6y = 1.", "Identify the parameter value that creates proportional variable coefficients but nonproportional constants."]'::jsonb, 'approved', 'in_depth', 'topic', 'special_case_and_parameter_linear_systems'),
('parameter_values_for_infinite_solution_systems', 'Parameter values for infinitely many solutions', 'Parameter values for infinitely many solutions', 'A parameter in a linear system can make two equations equivalent. This topic focuses on values that create a dependent system.', 'systems_of_equations', '["Find k so y = 3x + k and 2y = 6x + 8 have infinitely many solutions.", "Determine the value of a that makes ax + 4y = 12 equivalent to 3x + 2y = 6.", "Identify the parameter value that makes all coefficients and constants proportional."]'::jsonb, 'approved', 'in_depth', 'topic', 'special_case_and_parameter_linear_systems'),
('parameter_values_for_one_solution_systems', 'Parameter values for one-solution systems', 'Parameter values for one-solution systems', 'A parameter in a linear system can affect whether lines intersect once. This topic focuses on excluding values that cause parallel or coincident lines.', 'systems_of_equations', '["Find k so y = kx + 2 and y = 4x - 1 have exactly one solution.", "Determine which parameter values make two standard-form equations nonparallel.", "Identify values of a for which ax + y = 3 and 2x + y = 5 have one solution."]'::jsonb, 'approved', 'in_depth', 'topic', 'special_case_and_parameter_linear_systems'),
('contradiction_from_system_simplification', 'Contradiction from system simplification', 'Contradiction from system simplification', 'A system contradiction occurs when valid transformations lead to a false statement. This signals no solution and must be interpreted as a system-level result.', 'systems_of_equations', '["Interpret 0 = 9 after simplifying a system.", "Classify the solution type when elimination gives 5 = -2.", "Determine why all variables canceling to a false statement means no solution."]'::jsonb, 'approved', 'in_depth', 'topic', 'special_case_and_parameter_linear_systems'),
('identity_from_system_simplification', 'Identity from system simplification', 'Identity from system simplification', 'A system identity occurs when valid transformations lead to a true statement. This signals that the equations are dependent and have infinitely many solutions.', 'systems_of_equations', '["Interpret 0 = 0 after simplifying a system.", "Classify the solution type when substitution gives 12 = 12.", "Determine why all variables canceling to a true statement means infinitely many solutions."]'::jsonb, 'approved', 'in_depth', 'topic', 'special_case_and_parameter_linear_systems')
ON CONFLICT (id) DO NOTHING;

-- ─── three_variable_linear_systems_non_matrix topics ──────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('three_variable_system_structure', 'Three-variable system structure', 'Three-variable system structure', 'A three-variable system contains equations involving variables such as x, y, and z. This focuses on recognizing the structure before applying non-matrix methods.', 'systems_of_equations', '["Identify the variables in a system involving x, y, and z.", "Classify three equations in x, y, and z as a three-variable system.", "Determine whether a system has two variables or three variables."]'::jsonb, 'approved', 'in_depth', 'topic', 'three_variable_linear_systems_non_matrix'),
('three_variable_substitution_method', 'Substitution in three-variable systems', 'Substitution in three-variable systems', 'One variable can be isolated and substituted into other equations to reduce a three-variable system. This is the non-matrix substitution approach.', 'systems_of_equations', '["Solve x = y + 2 and two other equations by substituting for x.", "Substitute z = 3 - x into the remaining equations of a three-variable system.", "Reduce a three-variable system by replacing one variable with an equivalent expression."]'::jsonb, 'approved', 'in_depth', 'topic', 'three_variable_linear_systems_non_matrix'),
('three_variable_elimination_to_two_variable_system', 'Elimination reducing three variables to two variables', 'Elimination reducing three variables to two variables', 'A three-variable system can be reduced by eliminating the same variable from pairs of equations, producing a two-variable system. This is the key non-matrix elimination step.', 'systems_of_equations', '["Eliminate z from two pairs of equations to create a system in x and y.", "Reduce a three-variable system to two equations in two variables.", "Determine which variable to eliminate first from a three-equation system."]'::jsonb, 'approved', 'in_depth', 'topic', 'three_variable_linear_systems_non_matrix'),
('three_variable_elimination_pair_selection', 'Equation-pair selection in three-variable elimination', 'Equation-pair selection in three-variable elimination', 'Different pairs of equations can be combined to eliminate a chosen variable. This topic focuses on selecting useful pairs to create a solvable two-variable system.', 'systems_of_equations', '["Choose two equation pairs that eliminate z from a three-variable system.", "Identify which equations should be paired to eliminate y most efficiently.", "Determine a pair of equations with matching x-coefficients."]'::jsonb, 'approved', 'in_depth', 'topic', 'three_variable_linear_systems_non_matrix'),
('three_variable_back_substitution', 'Back substitution in three-variable systems', 'Back substitution in three-variable systems', 'After two variables are found, their values must be substituted back to find the remaining variable. This completes the ordered triple.', 'systems_of_equations', '["Find z after solving x = 2 and y = -1 in a three-variable system.", "Use two known variable values to determine the third value.", "Complete the ordered triple after reducing a system to two variables."]'::jsonb, 'approved', 'in_depth', 'topic', 'three_variable_linear_systems_non_matrix'),
('three_variable_ordered_triple_completion', 'Ordered-triple completion', 'Ordered-triple completion', 'A three-variable system solution must include all three variable values in the correct order. This targets incomplete or misordered final answers.', 'systems_of_equations', '["Write x = 1, y = -4, and z = 2 as an ordered triple.", "Complete the solution after finding x and y but not z.", "Determine whether (2, 1, -3) matches x = 2, y = 1, z = -3."]'::jsonb, 'approved', 'in_depth', 'topic', 'three_variable_linear_systems_non_matrix'),
('three_variable_system_one_solution', 'One-solution three-variable systems', 'One-solution three-variable systems', 'A three-variable linear system can have exactly one ordered-triple solution. This is the non-matrix interpretation of a unique solution.', 'systems_of_equations', '["Classify a three-variable system that produces x = 1, y = 2, and z = 3.", "Determine whether a completed ordered triple means the system has one solution.", "Verify the unique solution of a three-equation system."]'::jsonb, 'approved', 'in_depth', 'topic', 'three_variable_linear_systems_non_matrix'),
('three_variable_system_no_solution', 'No-solution three-variable systems', 'No-solution three-variable systems', 'A three-variable linear system has no solution when its equations cannot all be true at once. Algebraically, this may appear as a false statement after elimination.', 'systems_of_equations', '["Classify a three-variable system after elimination gives 0 = 5.", "Determine whether a contradiction means no ordered triple satisfies the system.", "Identify a no-solution outcome in a three-equation system."]'::jsonb, 'approved', 'in_depth', 'topic', 'three_variable_linear_systems_non_matrix'),
('three_variable_system_infinite_solutions', 'Infinitely many solutions in three-variable systems', 'Infinitely many solutions in three-variable systems', 'A three-variable system may have infinitely many solutions when equations are dependent or do not determine a unique ordered triple. This is interpreted without matrix methods.', 'systems_of_equations', '["Classify a three-variable system after simplification gives 0 = 0 and one variable remains free.", "Determine whether dependent equations can produce infinitely many ordered triples.", "Identify a system outcome where one variable can take many values."]'::jsonb, 'approved', 'in_depth', 'topic', 'three_variable_linear_systems_non_matrix'),
('free_variable_in_three_variable_systems', 'Free variables in three-variable systems', 'Free variables in three-variable systems', 'A free variable appears when a three-variable system has infinitely many solutions and one variable is not uniquely determined. This topic focuses on parameterized solution descriptions without matrices.', 'systems_of_equations', '["Identify the free variable when a system reduces to x + y = 4.", "Write y in terms of a free variable after solving a dependent three-variable system.", "Determine why infinitely many ordered triples may require a parameter."]'::jsonb, 'approved', 'in_depth', 'topic', 'three_variable_linear_systems_non_matrix')
ON CONFLICT (id) DO NOTHING;

-- ─── systems_of_linear_inequalities topics ────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('system_of_linear_inequalities_structure', 'System of linear inequalities structure', 'System of linear inequalities structure', 'A system of linear inequalities contains two or more inequalities that must be satisfied by the same ordered pairs. This focuses on recognizing multiple coordinate-plane constraints.', 'systems_of_equations', '["Identify the inequalities in the system y > x + 1 and y ≤ -2x + 5.", "Classify y < 3x and x + y ≥ 4 as a system of inequalities.", "Determine whether a pair of linear inequalities forms a coordinate-plane system."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_of_linear_inequalities'),
('solution_to_system_of_inequalities_meaning', 'Solution meaning for systems of inequalities', 'Solution meaning for systems of inequalities', 'A solution to a system of inequalities is an ordered pair that satisfies every inequality in the system. This is region-based rather than a single intersection point.', 'systems_of_equations', '["Determine whether (2, 3) satisfies y > x and x + y ≤ 6.", "Identify an ordered pair in the solution region of two inequalities.", "Classify a point as a solution or non-solution of a system of inequalities."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_of_linear_inequalities'),
('boundary_lines_for_linear_inequalities', 'Boundary lines for linear inequalities', 'Boundary lines for linear inequalities', 'Each linear inequality has a boundary line formed by replacing the inequality symbol with an equals sign. This line separates the coordinate plane into possible regions.', 'systems_of_equations', '["Identify the boundary line for y < 2x + 1.", "Write the boundary equation for x + y ≥ 5.", "Determine the boundary line of 3x - 2y ≤ 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_of_linear_inequalities'),
('solid_boundary_lines', 'Solid boundary lines', 'Solid boundary lines', 'Inclusive inequalities with ≤ or ≥ use solid boundary lines because points on the boundary are included in the solution set.', 'systems_of_equations', '["Determine whether y ≤ x + 4 uses a solid or dashed line.", "Graph the boundary for x + y ≥ 3 using the correct line type.", "Identify why the line is included for y ≥ -2x."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_of_linear_inequalities'),
('dashed_boundary_lines', 'Dashed boundary lines', 'Dashed boundary lines', 'Strict inequalities with < or > use dashed boundary lines because points on the boundary are not included in the solution set.', 'systems_of_equations', '["Determine whether y < x - 1 uses a solid or dashed line.", "Graph the boundary for x + y > 7 using the correct line type.", "Identify why the line is excluded for y > 3x."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_of_linear_inequalities'),
('shading_above_or_below_boundary', 'Shading above or below a boundary line', 'Shading above or below a boundary line', 'Inequalities solved for y often indicate shading above or below the boundary line. This focuses on interpreting symbols such as y > mx + b and y < mx + b.', 'systems_of_equations', '["Determine whether to shade above or below y > 2x - 3.", "Graph the solution region for y ≤ -x + 4.", "Identify the correct half-plane for y < 5."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_of_linear_inequalities'),
('test_point_for_inequality_shading', 'Test-point shading for inequalities', 'Test-point shading for inequalities', 'A test point can determine which side of a boundary line satisfies an inequality. This is especially useful when the inequality is not solved for y.', 'systems_of_equations', '["Use (0, 0) to decide the shading for 2x + y ≥ 5.", "Test a point to determine the solution side of x - 3y < 6.", "Identify whether the origin satisfies 4x + 2y ≤ 8."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_of_linear_inequalities'),
('overlap_region_for_systems_of_inequalities', 'Overlap region for systems of inequalities', 'Overlap region for systems of inequalities', 'The solution set of a system of inequalities is the overlap of all individual solution regions. This focuses on intersection of half-planes.', 'systems_of_equations', '["Identify the overlapping region for y > x and y < -x + 6.", "Graph two inequalities and shade only the common solution region.", "Determine which region satisfies both inequalities in a system."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_of_linear_inequalities'),
('bounded_feasible_regions', 'Bounded feasible regions', 'Bounded feasible regions', 'A bounded feasible region is enclosed by boundary lines and has finite area. This appears when inequalities trap the solution set on all sides.', 'systems_of_equations', '["Identify whether a graphed feasible region is bounded.", "Graph inequalities that form a triangular feasible region.", "Determine whether the overlap of three half-planes is enclosed."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_of_linear_inequalities'),
('unbounded_feasible_regions', 'Unbounded feasible regions', 'Unbounded feasible regions', 'An unbounded feasible region extends infinitely in at least one direction. This occurs when the inequalities do not enclose the solution set completely.', 'systems_of_equations', '["Identify whether a shaded solution region is unbounded.", "Determine why y ≥ x and y ≥ -x form an unbounded region.", "Graph a system of inequalities whose overlap extends forever."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_of_linear_inequalities'),
('vertices_of_feasible_regions', 'Vertices of feasible regions', 'Vertices of feasible regions', 'Vertices of a feasible region occur where boundary lines intersect. This is coordinate-plane intersection structure, not optimization.', 'systems_of_equations', '["Find the vertex where x + y = 6 intersects y = x.", "Identify the corner points of a triangular feasible region.", "Determine the intersection points of boundary lines in a system of inequalities."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_of_linear_inequalities'),
('systems_of_inequalities_no_solution_region', 'Systems of inequalities with no solution region', 'Systems of inequalities with no solution region', 'A system of inequalities has no solution when the individual regions have no overlap. This is the coordinate-plane version of an empty solution set.', 'systems_of_equations', '["Determine whether y > 3 and y < 1 have any common solutions.", "Identify why two shaded regions do not overlap.", "Classify a system of inequalities as having no solution region."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_of_linear_inequalities'),
('systems_of_inequalities_boundary_point_inclusion', 'Boundary point inclusion in systems of inequalities', 'Boundary point inclusion in systems of inequalities', 'A boundary point belongs to the solution set only if it satisfies every inequality, including each inequality''s strict or inclusive condition. This targets endpoint and boundary mistakes.', 'systems_of_equations', '["Determine whether a point on a solid boundary line is included in the system solution.", "Check whether an intersection point of two boundaries satisfies both inequalities.", "Identify why a point on a dashed boundary is excluded from the solution region."]'::jsonb, 'approved', 'in_depth', 'topic', 'systems_of_linear_inequalities')
ON CONFLICT (id) DO NOTHING;

-- ─── nonlinear_systems_of_equations topics ────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('nonlinear_system_structure', 'Nonlinear system structure', 'Nonlinear system structure', 'A nonlinear system contains at least one equation that is not linear. This focuses on recognizing systems involving curves such as quadratics, circles, or other nonlinear relations.', 'systems_of_equations', '["Classify y = x^2 and y = x + 2 as a nonlinear system.", "Identify which equation makes a system nonlinear.", "Determine whether x + y = 5 and y = 3x - 1 form a linear or nonlinear system."]'::jsonb, 'approved', 'in_depth', 'topic', 'nonlinear_systems_of_equations'),
('linear_quadratic_systems', 'Linear-quadratic systems', 'Linear-quadratic systems', 'A linear-quadratic system contains one line and one quadratic relation. Solutions are intersection points between the line and the parabola.', 'systems_of_equations', '["Solve y = x^2 and y = x + 6.", "Find the intersection points of y = x^2 - 4 and y = 2x.", "Determine how many real solutions y = x^2 and y = 5 can have."]'::jsonb, 'approved', 'in_depth', 'topic', 'nonlinear_systems_of_equations'),
('quadratic_quadratic_systems', 'Quadratic-quadratic systems', 'Quadratic-quadratic systems', 'A quadratic-quadratic system contains two quadratic relations. Solving often involves setting the quadratic expressions equal and finding intersection points.', 'systems_of_equations', '["Solve y = x^2 and y = -x^2 + 4.", "Find the intersections of y = x^2 and y = -x^2 + 8.", "Determine the solution points for y = x^2 - 1 and y = 2x^2 - 5."]'::jsonb, 'approved', 'in_depth', 'topic', 'nonlinear_systems_of_equations'),
('line_circle_systems', 'Line-circle systems', 'Line-circle systems', 'A line-circle system contains a linear equation and a circle equation. Solutions are intersection points between the line and the circle.', 'systems_of_equations', '["Solve y = x and x^2 + y^2 = 18.", "Find the intersection points of x = 3 and x^2 + y^2 = 25.", "Determine whether a line intersects a circle in zero, one, or two points."]'::jsonb, 'approved', 'in_depth', 'topic', 'nonlinear_systems_of_equations'),
('circle_circle_systems', 'Circle-circle systems', 'Circle-circle systems', 'A circle-circle system contains two circle equations. Solutions are the intersection points shared by both circles.', 'systems_of_equations', '["Solve x^2 + y^2 = 25 and (x - 3)^2 + y^2 = 16.", "Find the intersection points of two given circles.", "Determine whether two circles have zero, one, two, or infinitely many common points."]'::jsonb, 'approved', 'in_depth', 'topic', 'nonlinear_systems_of_equations'),
('nonlinear_system_substitution', 'Substitution in nonlinear systems', 'Substitution in nonlinear systems', 'A nonlinear system can often be solved by substituting one expression into another equation. This may produce a quadratic or other nonlinear single-variable equation.', 'systems_of_equations', '["Substitute y = x + 1 into x^2 + y^2 = 13.", "Solve y = x^2 - 3 and y = 2x + 1 by substitution.", "Determine the equation formed after replacing y in a nonlinear system."]'::jsonb, 'approved', 'in_depth', 'topic', 'nonlinear_systems_of_equations'),
('nonlinear_systems_leading_to_quadratic_equations', 'Nonlinear systems leading to quadratic equations', 'Nonlinear systems leading to quadratic equations', 'Many nonlinear systems reduce to a quadratic equation after substitution or elimination. This topic focuses on the system structure that creates a quadratic equation.', 'systems_of_equations', '["Solve y = x + 2 and y = x^2 by setting the expressions equal.", "Determine the quadratic equation formed from y = 3x - 1 and y = x^2 + 4.", "Find the x-values where a line and parabola intersect."]'::jsonb, 'approved', 'in_depth', 'topic', 'nonlinear_systems_of_equations'),
('number_of_real_solutions_nonlinear_systems', 'Number of real solutions in nonlinear systems', 'Number of real solutions in nonlinear systems', 'A nonlinear system may have zero, one, two, or more real solutions depending on how the graphs intersect. This focuses on solution count from algebraic or graphical structure.', 'systems_of_equations', '["Determine how many real intersections y = x^2 and y = -1 have.", "Classify the number of solutions for a line tangent to a parabola.", "Identify whether a circle and line intersect in zero, one, or two points."]'::jsonb, 'approved', 'in_depth', 'topic', 'nonlinear_systems_of_equations'),
('tangent_intersection_systems', 'Tangent intersection systems', 'Tangent intersection systems', 'A tangent system has exactly one intersection point because a line or curve touches another curve without crossing it. This is a special one-solution nonlinear case.', 'systems_of_equations', '["Determine whether y = 2x + 1 is tangent to y = x^2 + 2.", "Identify the solution type when a line touches a circle at one point.", "Find the single intersection point of a tangent line and a parabola."]'::jsonb, 'approved', 'in_depth', 'topic', 'nonlinear_systems_of_equations'),
('nonlinear_system_solution_verification', 'Solution verification in nonlinear systems', 'Solution verification in nonlinear systems', 'A proposed solution to a nonlinear system must satisfy every equation in the system. This is especially important when algebraic solving produces multiple candidates.', 'systems_of_equations', '["Check whether (2, 4) solves y = x^2 and y = 2x.", "Verify the intersection points of a line and circle system.", "Determine which candidate points satisfy both nonlinear equations."]'::jsonb, 'approved', 'in_depth', 'topic', 'nonlinear_systems_of_equations'),
('extraneous_candidates_in_nonlinear_systems', 'Extraneous candidates in nonlinear systems', 'Extraneous candidates in nonlinear systems', 'Some nonlinear system-solving processes can produce candidate points that do not satisfy the original equations. This topic focuses on checking and rejecting invalid candidates.', 'systems_of_equations', '["Check candidate solutions after solving a nonlinear system by substitution.", "Identify which candidate point fails one equation in the original system.", "Verify all possible intersections before writing the final system solution."]'::jsonb, 'approved', 'in_depth', 'topic', 'nonlinear_systems_of_equations'),
('graphical_intersections_nonlinear_systems', 'Graphical intersections in nonlinear systems', 'Graphical intersections in nonlinear systems', 'Nonlinear system solutions can be interpreted as intersection points between curves. This includes line-curve and curve-curve intersections.', 'systems_of_equations', '["Identify the intersection points of a graphed line and parabola.", "Estimate the solutions of a nonlinear system from a graph.", "Determine where two graphed curves satisfy both equations."]'::jsonb, 'approved', 'in_depth', 'topic', 'nonlinear_systems_of_equations')
ON CONFLICT (id) DO NOTHING;

-- ─── structured_linear_system_relationships topics ────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('sum_and_difference_systems', 'Sum-and-difference systems', 'Sum-and-difference systems', 'A system may give the sum of two quantities and their difference. This structure often solves efficiently by elimination.', 'systems_of_equations', '["Solve x + y = 20 and x - y = 4.", "Determine two numbers whose sum is 15 and difference is 3.", "Identify the elimination shortcut in a sum-and-difference system."]'::jsonb, 'approved', 'in_depth', 'topic', 'structured_linear_system_relationships'),
('total_and_part_systems', 'Total-and-part systems', 'Total-and-part systems', 'A system may relate two parts to a total while a second equation gives another relationship between the parts. This focuses on part-total algebraic structure.', 'systems_of_equations', '["Write a system where x + y = 50 and one part is 8 more than the other.", "Solve x + y = 100 and x = 3y.", "Identify the total equation in a two-part linear system."]'::jsonb, 'approved', 'in_depth', 'topic', 'structured_linear_system_relationships'),
('value_and_quantity_systems', 'Value-and-quantity systems', 'Value-and-quantity systems', 'A system may use one equation for total quantity and another for total value. This structure appears when different item types have different values or rates.', 'systems_of_equations', '["Write a system with x + y = 30 and 5x + 8y = 180.", "Solve a quantity-value system represented by x + y = 12 and 2x + 3y = 31.", "Identify which equation represents total value in a two-variable system."]'::jsonb, 'approved', 'in_depth', 'topic', 'structured_linear_system_relationships'),
('rate_and_total_systems', 'Rate-and-total systems', 'Rate-and-total systems', 'A system may combine unknown quantities with different rates to produce a total. This is the algebraic structure behind weighted totals.', 'systems_of_equations', '["Write a system using x + y = 10 and 40x + 60y = 520.", "Solve a rate-total system with two unknown quantities.", "Identify the rate coefficients in 25x + 15y = 300."]'::jsonb, 'approved', 'in_depth', 'topic', 'structured_linear_system_relationships'),
('mixture_systems_two_components', 'Two-component mixture systems', 'Two-component mixture systems', 'A two-component mixture system uses one equation for total amount and another for total concentration, value, or weighted contribution. This focuses on the algebraic structure of mixtures.', 'systems_of_equations', '["Write a system with x + y = 20 and 0.10x + 0.30y = 4.", "Solve a two-component mixture system involving total amount and total active ingredient.", "Identify the weighted equation in a mixture system."]'::jsonb, 'approved', 'in_depth', 'topic', 'structured_linear_system_relationships'),
('comparison_systems', 'Comparison systems', 'Comparison systems', 'A system may include an equation comparing one variable to another, such as x = y + k or x = ky. This structure is often efficient for substitution.', 'systems_of_equations', '["Solve x = y + 6 and x + y = 24.", "Write a system where one quantity is three times the other and their sum is 40.", "Identify the comparison equation in x = 2y - 5 and x + y = 19."]'::jsonb, 'approved', 'in_depth', 'topic', 'structured_linear_system_relationships'),
('break_even_systems', 'Break-even systems', 'Break-even systems', 'A break-even system compares two linear expressions by finding where they are equal. The solution represents the input where both quantities match.', 'systems_of_equations', '["Solve 20x + 50 = 35x + 5 as a system comparison.", "Find the intersection of C = 12x + 100 and R = 20x.", "Determine the break-even point of two linear cost expressions."]'::jsonb, 'approved', 'in_depth', 'topic', 'structured_linear_system_relationships'),
('linear_systems_from_two_constraints', 'Linear systems from two constraints', 'Linear systems from two constraints', 'Two independent linear constraints on the same variables can form a system. This focuses on translating simultaneous restrictions into equations without treating word-problem context as a separate topic.', 'systems_of_equations', '["Write two equations for variables x and y given two simultaneous constraints.", "Identify the pair of constraints that forms a solvable linear system.", "Determine the system represented by x + y = 18 and 4x + y = 45."]'::jsonb, 'approved', 'in_depth', 'topic', 'structured_linear_system_relationships')
ON CONFLICT (id) DO NOTHING;
