-- Category
INSERT INTO learn_categories (id, name, description, order_index)
VALUES ('polynomials', 'Polynomials', 'Structure, operations, factoring, division, equations, zeros, graphs, and finite differences for polynomial expressions and functions.', 6)
ON CONFLICT (id) DO NOTHING;

-- ─── Umbrella keywords ────────────────────────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('polynomial_structure_and_classification', 'Polynomial Structure and Classification', 'Polynomial Structure and Classification', 'Recognizing polynomial expressions, their parts, their degree, their term structure, and the boundary between polynomial and non-polynomial forms.', 'polynomials', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('polynomial_values_and_identities', 'Polynomial Values and Identities', 'Polynomial Values and Identities', 'Substituting values into polynomials, interpreting polynomial notation, recognizing equivalent polynomial expressions, and using coefficient comparison in identities.', 'polynomials', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('polynomial_addition_and_subtraction', 'Polynomial Addition and Subtraction', 'Polynomial Addition and Subtraction', 'Adding and subtracting polynomial expressions by aligning like terms, preserving signs, and understanding degree behavior under addition and subtraction.', 'polynomials', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('polynomial_multiplication_and_special_products', 'Polynomial Multiplication and Special Products', 'Polynomial Multiplication and Special Products', 'Multiplying monomials and polynomials, using exponent rules and distribution, and recognizing common product patterns.', 'polynomials', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('gcf_factoring_and_grouping', 'GCF Factoring and Grouping', 'GCF Factoring and Grouping', 'Factoring polynomial expressions by common factors, negative common factors, common binomial factors, and grouping structures.', 'polynomials', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('quadratic_and_special_form_factoring', 'Quadratic and Special-Form Factoring', 'Quadratic and Special-Form Factoring', 'Factoring quadratic trinomials and common special polynomial forms such as difference of squares, perfect-square trinomials, sums and differences of cubes, and quadratic-form polynomials.', 'polynomials', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('polynomial_division_and_factor_theorems', 'Polynomial Division and Factor Theorems', 'Polynomial Division and Factor Theorems', 'Dividing polynomials by monomials or polynomial divisors, interpreting quotients and remainders, and using the Remainder Theorem and Factor Theorem.', 'polynomials', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('polynomial_equations_and_roots', 'Polynomial Equations and Roots', 'Polynomial Equations and Roots', 'Solving polynomial equations using factoring, interpreting roots from factored form, and distinguishing real-solution behavior in polynomial equations.', 'polynomials', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('polynomial_zeros_and_graph_behavior', 'Polynomial Zeros and Graph Behavior', 'Polynomial Zeros and Graph Behavior', 'General polynomial-function behavior, including zeros, factors, intercepts, multiplicity, end behavior, smoothness, and degree-based graph features.', 'polynomials', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('polynomial_tables_and_finite_differences', 'Polynomial Tables and Finite Differences', 'Polynomial Tables and Finite Differences', 'Using equally spaced input-output tables and finite differences to recognize polynomial degree patterns.', 'polynomials', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL)
ON CONFLICT (id) DO NOTHING;

-- ─── polynomial_structure_and_classification topics ───────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('polynomial_expression_definition', 'Polynomial expression definition', 'Polynomial expression definition', 'A polynomial expression is a finite sum of terms with variables raised only to nonnegative integer powers and coefficients from a specified number set. This excludes variable denominators, negative variable exponents, fractional variable exponents, and radicals containing variables.', 'polynomials', '["Classify 3x^4 - 2x + 7 as a polynomial or non-polynomial.", "Identify which expression is a polynomial: x^2 + 5x, 1/x + 3, or sqrt(x) + 1.", "Determine whether 4a^3b^2 - 9b + 1 is a polynomial."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('polynomial_term_structure', 'Polynomial term structure', 'Polynomial term structure', 'A polynomial term is one additive part of a polynomial, consisting of a coefficient multiplied by variables with nonnegative integer exponents. This focuses on parsing terms before combining or factoring.', 'polynomials', '["Identify the terms in 5x^3 - 2x + 9.", "List the terms of -4a^2 + 7a - 1 with their signs.", "Determine how many terms are in 6m^4 - m^2 + 3m - 8."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('polynomial_coefficients', 'Polynomial coefficients', 'Polynomial coefficients', 'A coefficient is the numerical factor multiplying a variable power in a polynomial term. This includes positive, negative, fractional, decimal, and implied coefficients.', 'polynomials', '["Identify the coefficient of x^3 in -7x^3 + 4x - 2.", "Determine the coefficient of a^2 in a^2 - 5a + 1.", "List the coefficients in 3m^4 - m + 8."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('polynomial_constant_term', 'Polynomial constant term', 'Polynomial constant term', 'The constant term is the polynomial term with degree 0, meaning it has no variable factor. This term affects values and intercepts but not the degree unless it is the only nonzero term.', 'polynomials', '["Identify the constant term in 4x^5 - 3x + 11.", "Determine the constant term of -2a^3 + 9a^2 - 6.", "Classify 8 as the constant term in 7m^2 + 8."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('leading_term_polynomial', 'Leading term of a polynomial', 'Leading term of a polynomial', 'The leading term is the nonzero term with the greatest degree when the polynomial is written in standard form. It determines many high-level behaviors of the polynomial.', 'polynomials', '["Identify the leading term of 2x^5 - 7x^3 + x - 1.", "Determine the leading term after writing 4 - 3a^2 + a^4 in standard form.", "Select the leading term of -6m + 9m^7 - 2m^2."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('leading_coefficient_polynomial', 'Leading coefficient of a polynomial', 'Leading coefficient of a polynomial', 'The leading coefficient is the coefficient of the leading term. This is distinct from the degree and from the constant term.', 'polynomials', '["Identify the leading coefficient of -5x^4 + 2x - 8.", "Determine the leading coefficient of 7a^6 - a^3 + 1.", "Find the leading coefficient after arranging 3 - 2m^5 + 9m in standard form."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('polynomial_standard_form', 'Polynomial standard form', 'Polynomial standard form', 'A univariate polynomial is in standard form when terms are written in descending powers of the variable. This supports degree, leading-term, and operation work.', 'polynomials', '["Write 5 - 2x^3 + 7x in standard form.", "Arrange 4a^2 - 9 + a^5 - a in descending powers.", "Identify whether 3m^4 + 2m^2 - 7 is in standard form."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('descending_power_order', 'Descending power order', 'Descending power order', 'Descending power order means terms are arranged from greatest exponent to least exponent for a chosen variable. This is the ordering convention behind standard form.', 'polynomials', '["Order the terms x, x^5, 1, and x^2 from highest power to lowest power.", "Rewrite -3a + a^4 + 6 in descending power order.", "Determine which term should appear first in 2m^3 + 8m^7 - 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('missing_terms_zero_coefficients', 'Missing terms and zero coefficients', 'Missing terms and zero coefficients', 'A polynomial may skip powers because the missing terms have coefficient 0. This matters when aligning terms, dividing polynomials, and interpreting degree structure.', 'polynomials', '["Rewrite x^4 - 7x + 2 with zero-coefficient missing terms.", "Identify the missing degree terms in 3a^5 + 2a^2 - 1.", "Insert zero placeholders in m^3 - 4 before polynomial division."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('polynomial_degree_univariate', 'Degree of a univariate polynomial', 'Degree of a univariate polynomial', 'The degree of a nonzero univariate polynomial is the greatest exponent of the variable after like terms are combined. This is different from the number of terms.', 'polynomials', '["Determine the degree of 4x^6 - 2x + 9.", "Identify the degree of 7a^2 - 3a^5 + 1 after arranging terms.", "Find the degree of 8m - 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('zero_polynomial_degree_undefined', 'Zero polynomial degree', 'Zero polynomial degree', 'The zero polynomial has all coefficients equal to 0 and does not have a standard finite degree. This prevents incorrectly assigning degree 0 to the zero polynomial.', 'polynomials', '["Classify the degree of the zero polynomial.", "Determine why 0 is not treated like a nonzero constant polynomial for degree.", "Identify the polynomial whose degree is undefined rather than 0."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('polynomial_classification_by_number_of_terms', 'Polynomial classification by number of terms', 'Polynomial classification by number of terms', 'Polynomials can be classified as monomials, binomials, trinomials, or more general polynomials based on the number of nonzero terms after like terms are combined.', 'polynomials', '["Classify 3x^2 - 5x + 1 by number of terms.", "Determine whether 7a^4 - 2 is a monomial, binomial, or trinomial.", "Identify the term-count classification of 4m^3 + m^2 - m + 9."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('polynomial_classification_by_degree', 'Polynomial classification by degree', 'Polynomial classification by degree', 'Polynomials can be classified by degree using names such as constant, linear, quadratic, cubic, quartic, and higher-degree polynomial. This is structural classification, not graph analysis.', 'polynomials', '["Classify 5x^3 - 2x + 1 by degree.", "Identify whether 7a^2 + 3a - 4 is linear, quadratic, or cubic.", "Determine the degree name for -2m^4 + m."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('monomial_polynomial_structure', 'Monomial polynomial structure', 'Monomial polynomial structure', 'A monomial is a polynomial with exactly one nonzero term. This includes constants and variable terms with nonnegative integer exponents.', 'polynomials', '["Classify -8x^5 as a monomial.", "Determine whether 6ab^2 is a monomial polynomial.", "Identify which expression is a monomial: 3x^2, x + 3, or 1/x."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('binomial_polynomial_structure', 'Binomial polynomial structure', 'Binomial polynomial structure', 'A binomial is a polynomial with exactly two nonzero terms after like terms are combined. This term-count classification is separate from degree.', 'polynomials', '["Classify x^2 - 9 as a binomial.", "Determine whether 4a^3 + 7a - 2 is a binomial.", "Identify the binomial in a list of polynomial expressions."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('trinomial_polynomial_structure', 'Trinomial polynomial structure', 'Trinomial polynomial structure', 'A trinomial is a polynomial with exactly three nonzero terms after like terms are combined. This includes but is not limited to quadratic trinomials.', 'polynomials', '["Classify x^2 + 5x + 6 as a trinomial.", "Determine whether 3a^4 - 2a + 1 is a trinomial.", "Identify which polynomial has exactly three terms."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('univariate_polynomials', 'Univariate polynomials', 'Univariate polynomials', 'A univariate polynomial contains exactly one variable. This structure supports standard form, single-variable degree, division, zeros, and graph behavior.', 'polynomials', '["Classify 4x^3 - x + 8 as a univariate polynomial.", "Identify the variable in the polynomial 7a^5 - 2a.", "Determine whether 3x^2y + 1 is univariate."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('multivariable_polynomials', 'Multivariable polynomials', 'Multivariable polynomials', 'A multivariable polynomial contains two or more variables, with each variable raised only to nonnegative integer powers. This differs from univariate polynomial structure.', 'polynomials', '["Classify 3x^2y - 5xy + 7 as a multivariable polynomial.", "Identify the variables in 4a^2b^3 - 2b + 1.", "Determine whether x^2 + y^2 + z^2 is multivariable."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('multivariable_monomial_degree', 'Degree of a multivariable monomial', 'Degree of a multivariable monomial', 'The degree of a multivariable monomial is the sum of the exponents of its variable factors. This differs from univariate degree, where there is only one exponent.', 'polynomials', '["Determine the degree of 5x^3y^2.", "Identify the degree of -7ab^4c.", "Find the total degree of 2m^2n^5."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('multivariable_polynomial_degree', 'Degree of a multivariable polynomial', 'Degree of a multivariable polynomial', 'The degree of a multivariable polynomial is the greatest total degree among its terms after like terms are combined. This focuses on total degree, not any single variable alone.', 'polynomials', '["Determine the degree of 3x^2y + 4xy^5 - 1.", "Identify the highest-degree term in a multivariable polynomial.", "Find the degree of a^3b^2 - 6ab + 9."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('polynomial_vs_nonpolynomial_negative_exponents', 'Non-polynomial forms with negative variable exponents', 'Non-polynomial forms with negative variable exponents', 'An expression with a variable raised to a negative exponent is not a polynomial in that variable. This targets forms such as x^-1 or 3x^-2 + 5.', 'polynomials', '["Determine whether x^-2 + 4 is a polynomial.", "Identify why 5a^3 + a^-1 is not a polynomial.", "Classify 7m^-4 as polynomial or non-polynomial."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('polynomial_vs_nonpolynomial_variable_denominators', 'Non-polynomial forms with variable denominators', 'Non-polynomial forms with variable denominators', 'An expression with a variable in a denominator is not a polynomial, because it can be rewritten with a negative variable exponent. This distinguishes polynomials from rational expressions.', 'polynomials', '["Determine whether 1/x + 3 is a polynomial.", "Identify why 5 + 2/(a - 1) is not a polynomial.", "Classify x^2 + 4/x as polynomial or non-polynomial."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('polynomial_vs_nonpolynomial_fractional_exponents', 'Non-polynomial forms with fractional variable exponents', 'Non-polynomial forms with fractional variable exponents', 'An expression with a variable raised to a fractional exponent is not a polynomial in standard precalculus. This includes radical forms involving variables.', 'polynomials', '["Determine whether x^(1/2) + 4 is a polynomial.", "Identify why sqrt(a) + a^2 is not a polynomial.", "Classify m^(3/2) - 1 as polynomial or non-polynomial."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification'),
('polynomial_coefficient_domain', 'Polynomial coefficient domain', 'Polynomial coefficient domain', 'Polynomial coefficients may come from a specified number set such as integers, rationals, reals, or complex numbers. The variable-power requirement is separate from the coefficient type.', 'polynomials', '["Classify 1/2 x^3 - 0.7x + pi as a polynomial over the real numbers.", "Identify whether fractional coefficients prevent an expression from being a polynomial.", "Determine whether sqrt(2)x^2 + 5 is a polynomial over the real numbers."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_structure_and_classification')
ON CONFLICT (id) DO NOTHING;

-- ─── polynomial_values_and_identities topics ──────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('polynomial_value_at_numeric_input', 'Polynomial value at a numeric input', 'Polynomial value at a numeric input', 'A polynomial value is found by substituting a number for the variable and applying operation order. This focuses on polynomial-specific substitution with powers and terms.', 'polynomials', '["Find the value of p(x) = x^3 - 2x + 5 when x = 2.", "Evaluate f(t) = 4t^2 - t + 1 at t = 3.", "Determine P(1) for P(x) = 7x^4 - 5x + 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_values_and_identities'),
('negative_input_polynomial_evaluation', 'Polynomial values at negative inputs', 'Polynomial values at negative inputs', 'Substituting negative inputs into polynomials requires careful treatment of powers, signs, and grouping. This targets common errors with even and odd powers.', 'polynomials', '["Find p(-2) for p(x) = x^3 - 4x^2 + 1.", "Evaluate f(-3) when f(x) = -2x^2 + 5x - 7.", "Determine whether (-2)^4 and -2^4 affect the value of a polynomial differently."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_values_and_identities'),
('fractional_decimal_input_polynomial_evaluation', 'Polynomial values at fractional or decimal inputs', 'Polynomial values at fractional or decimal inputs', 'Polynomial inputs may be fractions or decimals, requiring careful arithmetic with powers and coefficients. This is polynomial evaluation beyond integer inputs.', 'polynomials', '["Find p(1/2) for p(x) = 4x^2 - 3x + 1.", "Evaluate f(0.5) when f(x) = 2x^3 + x.", "Determine P(-1/3) for P(x) = 9x^2 + 6x + 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_values_and_identities'),
('multivariable_polynomial_evaluation', 'Multivariable polynomial evaluation', 'Multivariable polynomial evaluation', 'A multivariable polynomial value is found by substituting a value for each variable. This requires matching each input to the correct variable.', 'polynomials', '["Find the value of 3x^2y - 2y when x = 2 and y = -1.", "Evaluate a^2b + 4ab^2 when a = 3 and b = 2.", "Determine the value of x^2 + y^2 - xy at x = -1 and y = 4."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_values_and_identities'),
('polynomial_function_notation_evaluation', 'Polynomial function notation evaluation', 'Polynomial function notation evaluation', 'Polynomial function notation such as p(a) means the polynomial''s variable is replaced by the input expression a. This focuses on notation, not general function theory.', 'polynomials', '["Find f(3) when f(x) = 2x^2 - 1.", "Determine p(a + 1) for p(x) = x^2 + 4x.", "Evaluate g(-t) when g(x) = x^3 - x."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_values_and_identities'),
('equivalent_polynomial_expressions', 'Equivalent polynomial expressions', 'Equivalent polynomial expressions', 'Equivalent polynomial expressions have the same value for every input in their domain. Equivalence may result from expanding, factoring, collecting terms, or rearranging terms.', 'polynomials', '["Determine whether 3(x + 2) and 3x + 6 are equivalent polynomial expressions.", "Identify the expression equivalent to x^2 + 2x + x + 6.", "Classify x^2 - 9 and (x - 3)(x + 3) as equivalent or not equivalent."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_values_and_identities'),
('polynomial_identity_meaning', 'Polynomial identity meaning', 'Polynomial identity meaning', 'A polynomial identity is an equation between polynomial expressions that is true for every value of the variable. This differs from a polynomial equation solved for particular values.', 'polynomials', '["Classify (x + 1)^2 = x^2 + 2x + 1 as a polynomial identity.", "Determine whether x^2 = x is an identity or an equation with selected solutions.", "Identify why two expanded forms are equal for all x."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_values_and_identities'),
('coefficient_comparison_in_polynomial_identities', 'Coefficient comparison in polynomial identities', 'Coefficient comparison in polynomial identities', 'If two polynomials are identical, corresponding coefficients of like powers must match. This allows unknown coefficients to be found without testing many inputs.', 'polynomials', '["Compare coefficients in ax + 3 = 5x + b.", "Determine the missing coefficients if x^2 + ax + b = x^2 + 7x + 10.", "Identify matching coefficients in 2x^3 + cx = dx^3 - 4x."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_values_and_identities'),
('solving_unknown_coefficients_in_polynomial_identities', 'Unknown coefficients in polynomial identities', 'Unknown coefficients in polynomial identities', 'Unknown coefficients in a polynomial identity can be determined by expanding both sides and matching coefficients of corresponding powers. This is identity work, not root solving.', 'polynomials', '["Find a and b if (x + 2)(x + a) = x^2 + bx + 6.", "Determine k so 3x^2 + kx - 5 matches 3x^2 + 8x - 5.", "Identify the values of A and B in A(x - 1) + B(x + 2) = 5x + 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_values_and_identities'),
('polynomial_expression_domain_all_real', 'Polynomial expression domain over the reals', 'Polynomial expression domain over the reals', 'A polynomial expression with real coefficients is defined for every real input because it uses only addition, subtraction, multiplication, and nonnegative integer powers. This differs from rational or radical expressions.', 'polynomials', '["State the real-number domain of p(x) = x^4 - 3x + 1.", "Determine why f(x) = 2x^5 + 7 has no denominator restriction.", "Identify the domain of a polynomial expression over the real numbers."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_values_and_identities')
ON CONFLICT (id) DO NOTHING;

-- ─── polynomial_addition_and_subtraction topics ───────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('adding_polynomials_like_terms', 'Adding polynomials by like terms', 'Adding polynomials by like terms', 'Polynomial addition combines coefficients of terms with matching variables and exponents while preserving unlike terms. This extends like-term collection to full polynomial expressions.', 'polynomials', '["Add (3x^2 + 5x - 1) and (2x^2 - 7x + 4).", "Combine p(x) = x^3 - 2x and q(x) = 4x^3 + x - 9.", "Determine the sum of two polynomials by grouping like powers."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_addition_and_subtraction'),
('adding_polynomials_vertical_alignment', 'Vertical alignment for polynomial addition', 'Vertical alignment for polynomial addition', 'Polynomials can be added vertically by aligning terms with the same degree. This is especially helpful when terms are missing or out of order.', 'polynomials', '["Add x^4 - 3x + 2 and 5x^3 + x - 7 using vertical alignment.", "Align like powers before adding 2a^5 + 1 and -a^5 + 4a^2 - 6.", "Identify which terms should be placed in the same column when adding polynomials."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_addition_and_subtraction'),
('subtracting_polynomials_group_negation', 'Subtracting polynomials by group negation', 'Subtracting polynomials by group negation', 'Subtracting a polynomial requires changing the sign of every term in the polynomial being subtracted before combining like terms. This targets sign-distribution errors.', 'polynomials', '["Subtract (2x^2 - 5x + 1) from (7x^2 + x - 4).", "Rewrite (a^3 + 2a) - (4a^3 - a + 9) by changing signs.", "Determine the difference between p(x) and q(x) when q(x) has multiple terms."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_addition_and_subtraction'),
('subtracting_polynomials_vertical_alignment', 'Vertical alignment for polynomial subtraction', 'Vertical alignment for polynomial subtraction', 'Polynomial subtraction can be organized vertically by aligning like powers and subtracting corresponding coefficients. Missing terms require zero placeholders.', 'polynomials', '["Subtract x^3 - 4x + 6 from 3x^3 + 2x^2 - 1 using vertical alignment.", "Align powers before subtracting 5a^4 - a from 2a^4 + 3a^2 + 7.", "Insert zero terms to subtract polynomials with missing powers."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_addition_and_subtraction'),
('polynomial_like_terms_with_matching_exponents', 'Polynomial like terms with matching exponents', 'Polynomial like terms with matching exponents', 'Polynomial terms are like terms only when their variable parts and exponents match exactly. Coefficients may differ.', 'polynomials', '["Identify the like terms in 4x^3 - 2x^2 + 7x^3.", "Determine whether 5a^2 and -3a^2 are like polynomial terms.", "Classify x^4 and x^3 as like or unlike terms."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_addition_and_subtraction'),
('polynomial_unlike_terms_different_exponents', 'Polynomial unlike terms with different exponents', 'Polynomial unlike terms with different exponents', 'Terms with the same variable but different exponents are unlike and cannot be combined by addition or subtraction. This targets errors such as combining x^2 and x.', 'polynomials', '["Determine whether 6x^2 and 6x are like terms.", "Identify why 3a^4 + 2a^3 cannot become 5a^7.", "Classify m^5 and m^2 as like or unlike polynomial terms."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_addition_and_subtraction'),
('cancellation_creating_missing_terms', 'Cancellation creating missing polynomial terms', 'Cancellation creating missing polynomial terms', 'When like terms cancel to zero, the corresponding power disappears from the written polynomial. This can change the leading term or create missing powers.', 'polynomials', '["Add x^3 + 2x and -x^3 + 5 to identify the missing cubic term.", "Determine which term cancels in 4a^2 - 7a + 1 plus -4a^2 + 3a.", "Rewrite a polynomial sum after the leading terms cancel."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_addition_and_subtraction'),
('polynomial_additive_inverse', 'Additive inverse of a polynomial', 'Additive inverse of a polynomial', 'The additive inverse of a polynomial is formed by changing the sign of every term. Adding a polynomial and its additive inverse gives the zero polynomial.', 'polynomials', '["Find the additive inverse of 3x^2 - 5x + 7.", "Determine the polynomial that adds to x^3 + 4x - 9 to give 0.", "Identify the sign changes in the additive inverse of -2a^4 + a - 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_addition_and_subtraction'),
('closure_under_polynomial_addition_subtraction', 'Closure under polynomial addition and subtraction', 'Closure under polynomial addition and subtraction', 'The sum or difference of two polynomials is always another polynomial. This follows because like powers remain nonnegative integers after addition or subtraction.', 'polynomials', '["Determine whether adding two polynomials always gives a polynomial.", "Classify the result of subtracting one polynomial from another.", "Explain why polynomial addition does not create variable denominators."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_addition_and_subtraction'),
('polynomial_degree_after_addition_subtraction', 'Degree after polynomial addition or subtraction', 'Degree after polynomial addition or subtraction', 'The degree of a sum or difference is usually the greater degree, but it can drop if leading terms cancel. This targets degree reasoning after operations.', 'polynomials', '["Determine the degree of (x^4 + 2x) + (-x^4 + 3x^2).", "Identify when adding two cubic polynomials can produce a quadratic polynomial.", "Find the degree of a polynomial difference after leading-term cancellation."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_addition_and_subtraction')
ON CONFLICT (id) DO NOTHING;

-- ─── polynomial_multiplication_and_special_products topics ────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('monomial_times_monomial', 'Monomial times monomial', 'Monomial times monomial', 'Multiplying monomials requires multiplying coefficients and adding exponents of matching variable bases. This is the simplest polynomial product structure.', 'polynomials', '["Multiply 3x^2 by 5x^4.", "Determine the product of -2a^3b and 6ab^2.", "Rewrite 7m^5 · (-4m^2) as one monomial."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_multiplication_and_special_products'),
('monomial_times_polynomial', 'Monomial times polynomial', 'Monomial times polynomial', 'A monomial times a polynomial is expanded by distributing the monomial to every term and applying exponent rules. This includes coefficient and sign handling.', 'polynomials', '["Multiply 3x by x^2 - 4x + 5.", "Expand -2a^2(4a^3 - a + 7).", "Rewrite 5m(2m^2 + 3m - 1) as a polynomial."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_multiplication_and_special_products'),
('binomial_times_binomial', 'Binomial times binomial', 'Binomial times binomial', 'Multiplying two binomials requires distributing each term of one binomial across each term of the other. This produces up to four products before like terms are combined.', 'polynomials', '["Multiply (x + 3)(x + 5).", "Expand (2a - 1)(a + 7).", "Rewrite (m - 4)(3m + 2) as a polynomial."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_multiplication_and_special_products'),
('binomial_times_trinomial', 'Binomial times trinomial', 'Binomial times trinomial', 'Multiplying a binomial by a trinomial requires each term of the binomial to multiply each term of the trinomial. This targets complete distribution beyond FOIL.', 'polynomials', '["Multiply (x + 2)(x^2 - 3x + 4).", "Expand (a - 5)(2a^2 + a - 1).", "Rewrite (m + 1)(m^2 + 4m + 9) as a polynomial."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_multiplication_and_special_products'),
('polynomial_times_polynomial_general', 'General polynomial multiplication', 'General polynomial multiplication', 'Multiplying polynomials requires multiplying every term in one polynomial by every term in the other, then combining like terms. This covers products with more than two or three terms.', 'polynomials', '["Multiply (x^2 + x + 1)(x^2 - x + 2).", "Expand (a^3 + 2a - 4)(a^2 - 5).", "Determine the product of two multi-term polynomials."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_multiplication_and_special_products'),
('multiplying_polynomials_with_missing_terms', 'Multiplying polynomials with missing terms', 'Multiplying polynomials with missing terms', 'Polynomial multiplication can involve missing powers, so like terms must be aligned carefully after expansion. This targets products such as (x^3 + 1)(x^2 - x).', 'polynomials', '["Multiply (x^3 + 2)(x^2 - 5x + 1).", "Expand (a^4 - 1)(a^2 + a + 3).", "Identify missing power terms after multiplying sparse polynomials."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_multiplication_and_special_products'),
('polynomial_product_degree', 'Degree of a polynomial product', 'Degree of a polynomial product', 'For nonzero polynomials, the degree of a product is the sum of the degrees of the factors. This focuses on degree reasoning without fully expanding.', 'polynomials', '["Determine the degree of (x^3 + 1)(x^4 - x).", "Find the degree of the product of a quadratic and a cubic polynomial.", "Identify the degree of (2a^5 - 1)(7a^2 + 3)."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_multiplication_and_special_products'),
('square_of_binomial_sum', 'Square of a binomial sum', 'Square of a binomial sum', 'The square of a binomial sum follows (a + b)^2 = a^2 + 2ab + b^2. This targets the missing-middle-term misconception.', 'polynomials', '["Expand (x + 5)^2.", "Rewrite (2a + 3)^2 as a trinomial.", "Identify the middle term in (m + 7)^2."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_multiplication_and_special_products'),
('square_of_binomial_difference', 'Square of a binomial difference', 'Square of a binomial difference', 'The square of a binomial difference follows (a - b)^2 = a^2 - 2ab + b^2. The final term is positive because the negative term is squared.', 'polynomials', '["Expand (x - 4)^2.", "Rewrite (3a - 2)^2 as a trinomial.", "Identify the middle term in (m - 9)^2."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_multiplication_and_special_products'),
('conjugate_binomial_product', 'Conjugate binomial product', 'Conjugate binomial product', 'The product of conjugate binomials follows (a + b)(a - b) = a^2 - b^2. The middle terms cancel.', 'polynomials', '["Multiply (x + 6)(x - 6).", "Expand (3a + 2)(3a - 2).", "Identify why the product of conjugates has no middle term."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_multiplication_and_special_products'),
('cube_of_binomial_sum', 'Cube of a binomial sum', 'Cube of a binomial sum', 'The cube of a binomial sum follows (a + b)^3 = a^3 + 3a^2b + 3ab^2 + b^3. This is a special product pattern distinct from squaring.', 'polynomials', '["Expand (x + 2)^3.", "Rewrite (a + 1)^3 as a polynomial.", "Identify the coefficients in the expansion of (m + 5)^3."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_multiplication_and_special_products'),
('cube_of_binomial_difference', 'Cube of a binomial difference', 'Cube of a binomial difference', 'The cube of a binomial difference follows (a - b)^3 = a^3 - 3a^2b + 3ab^2 - b^3. This targets alternating signs in cubic expansions.', 'polynomials', '["Expand (x - 3)^3.", "Rewrite (2a - 1)^3 as a polynomial.", "Identify the sign pattern in the expansion of (m - 4)^3."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_multiplication_and_special_products'),
('product_of_sum_and_difference_of_polynomial_terms', 'Product of a sum and difference of polynomial terms', 'Product of a sum and difference of polynomial terms', 'A product of the form (A + B)(A - B) becomes A^2 - B^2 even when A or B is itself a polynomial term or expression. This generalizes conjugate products.', 'polynomials', '["Expand (x^2 + 3)(x^2 - 3).", "Rewrite (2a^3 - b)(2a^3 + b) as a difference of squares.", "Determine the product of (m + n + 1)(m + n - 1)."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_multiplication_and_special_products'),
('polynomial_multiplication_sign_management', 'Sign management in polynomial multiplication', 'Sign management in polynomial multiplication', 'Polynomial products require careful sign handling when negative coefficients, subtraction, or negative binomial terms are involved. This targets incorrect signs after distribution.', 'polynomials', '["Expand -(x - 3)(x + 5).", "Multiply (-2a + 1)(3a - 4).", "Determine the signs in the product (m - 6)(-m - 2)."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_multiplication_and_special_products'),
('closure_under_polynomial_multiplication', 'Closure under polynomial multiplication', 'Closure under polynomial multiplication', 'The product of two polynomials is always a polynomial because multiplication only creates finite sums of nonnegative integer powers. This is a structural closure property.', 'polynomials', '["Determine whether multiplying two polynomials always gives a polynomial.", "Classify the product of a binomial and a trinomial as polynomial or non-polynomial.", "Explain why polynomial multiplication does not create fractional variable exponents."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_multiplication_and_special_products')
ON CONFLICT (id) DO NOTHING;

-- ─── gcf_factoring_and_grouping topics ────────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('polynomial_factorization_meaning', 'Polynomial factorization meaning', 'Polynomial factorization meaning', 'Factoring rewrites a polynomial as a product of polynomial factors. This is the reverse of polynomial multiplication and expansion.', 'polynomials', '["Identify the factors in x^2 + 5x + 6 = (x + 2)(x + 3).", "Determine whether a polynomial is written as a sum or a product.", "Classify (x - 4)(x + 1) as factored form."]'::jsonb, 'approved', 'in_depth', 'topic', 'gcf_factoring_and_grouping'),
('polynomial_gcf_numeric_coefficients', 'GCF of polynomial numerical coefficients', 'GCF of polynomial numerical coefficients', 'The numerical part of a polynomial GCF is the greatest common factor of the term coefficients. This is one component of factoring out a monomial.', 'polynomials', '["Find the numerical GCF of 12x^3 and 18x.", "Identify the coefficient GCF in 15a^2 - 25a + 10.", "Determine the greatest common numerical factor of 8m^4, 20m^2, and 12m."]'::jsonb, 'approved', 'in_depth', 'topic', 'gcf_factoring_and_grouping'),
('polynomial_gcf_variable_powers', 'GCF of polynomial variable powers', 'GCF of polynomial variable powers', 'The variable part of a polynomial GCF uses the lowest exponent of each variable common to every term. This targets common variable-factor extraction.', 'polynomials', '["Find the variable GCF of x^5 and x^2.", "Identify the common variable factor in 6a^4b^2 and 9a^2b^5.", "Determine the GCF variable powers in 10m^6n, 15m^3n^4, and 5m^5n^2."]'::jsonb, 'approved', 'in_depth', 'topic', 'gcf_factoring_and_grouping'),
('polynomial_gcf_monomial', 'Monomial GCF of polynomial terms', 'Monomial GCF of polynomial terms', 'The monomial GCF combines the greatest common numerical factor with all common variable powers. This is the full common factor pulled from polynomial terms.', 'polynomials', '["Find the monomial GCF of 12x^4 and 18x^2.", "Identify the GCF of 8a^3b - 20a^2b^2.", "Determine the monomial GCF of 15m^5, 25m^3, and 10m^4."]'::jsonb, 'approved', 'in_depth', 'topic', 'gcf_factoring_and_grouping'),
('factoring_gcf_from_binomials', 'Factoring a GCF from binomials', 'Factoring a GCF from binomials', 'A binomial can be factored by pulling out the greatest common monomial factor shared by both terms. This is the simplest polynomial factoring move.', 'polynomials', '["Factor 6x^3 + 9x.", "Rewrite 14a^4 - 21a^2 by factoring the GCF.", "Factor -8m^5 + 12m^2."]'::jsonb, 'approved', 'in_depth', 'topic', 'gcf_factoring_and_grouping'),
('factoring_gcf_from_trinomials', 'Factoring a GCF from trinomials', 'Factoring a GCF from trinomials', 'A trinomial can have a monomial GCF shared across all three terms. The GCF must divide every term, not just two of them.', 'polynomials', '["Factor 4x^3 + 8x^2 - 12x.", "Rewrite 15a^4 - 10a^3 + 25a by factoring the GCF.", "Factor 6m^5 + 9m^3 - 3m."]'::jsonb, 'approved', 'in_depth', 'topic', 'gcf_factoring_and_grouping'),
('factoring_negative_gcf', 'Factoring out a negative GCF', 'Factoring out a negative GCF', 'A negative GCF is often factored out to make the leading term inside the parentheses positive. This requires changing the sign of every remaining term.', 'polynomials', '["Factor -3x^2 - 12x by taking out a negative GCF.", "Rewrite -5a^3 + 10a^2 - 15a with a negative GCF.", "Determine the remaining signs after factoring -2 from -2m^2 + 8m - 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'gcf_factoring_and_grouping'),
('factoring_by_grouping_four_terms', 'Factoring by grouping with four terms', 'Factoring by grouping with four terms', 'A four-term polynomial can sometimes be factored by grouping terms in pairs, factoring a GCF from each pair, and then factoring a common binomial. This targets classic grouping structure.', 'polynomials', '["Factor x^3 + 3x^2 + 2x + 6 by grouping.", "Rewrite ab + ac + db + dc as a product by grouping.", "Factor 2x^3 - 5x^2 + 6x - 15."]'::jsonb, 'approved', 'in_depth', 'topic', 'gcf_factoring_and_grouping'),
('grouping_common_binomial_factor', 'Common binomial factor after grouping', 'Common binomial factor after grouping', 'Factoring by grouping works when each group produces the same binomial factor. The common binomial can then be factored out.', 'polynomials', '["Identify the common binomial factor in x(x + 4) + 3(x + 4).", "Factor a(a - 2) - 5(a - 2).", "Determine the shared binomial in 2m(m + 1) + 7(m + 1)."]'::jsonb, 'approved', 'in_depth', 'topic', 'gcf_factoring_and_grouping'),
('grouping_after_reordering_terms', 'Factoring by grouping after reordering terms', 'Factoring by grouping after reordering terms', 'Some polynomials require terms to be rearranged before grouping creates common binomial factors. The signs of terms must move with the terms.', 'polynomials', '["Reorder and factor xy + 3y + 2x + 6.", "Factor ax + by + ay + bx by grouping after rearranging.", "Determine a grouping order for mn - 2m + 3n - 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'gcf_factoring_and_grouping'),
('factoring_common_binomial_factor', 'Factoring a common binomial factor', 'Factoring a common binomial factor', 'A polynomial expression may contain a repeated binomial factor across terms. The binomial can be treated like a common factor.', 'polynomials', '["Factor 4x(x - 1) + 7(x - 1).", "Rewrite a(2a + 3) - 5(2a + 3) as a product.", "Identify the common binomial factor in m(m + 4) + 2(m + 4)."]'::jsonb, 'approved', 'in_depth', 'topic', 'gcf_factoring_and_grouping'),
('factoring_out_fractional_gcf', 'Factoring out a fractional GCF', 'Factoring out a fractional GCF', 'A fractional common factor can be factored from polynomial terms when it is useful for rewriting or revealing structure. This requires careful coefficient division.', 'polynomials', '["Factor 1/2 from 1/2 x^2 + 3/2 x.", "Rewrite 3/4 a^2 - 9/4 a by factoring a fractional GCF.", "Determine the remaining polynomial after factoring 2/3 from 2/3 m^3 - 4/3 m."]'::jsonb, 'approved', 'in_depth', 'topic', 'gcf_factoring_and_grouping'),
('factoring_completely_over_integers', 'Factoring completely over the integers', 'Factoring completely over the integers', 'A polynomial is factored completely over the integers when no remaining factor can be factored further using integer coefficients. This depends on the allowed coefficient domain.', 'polynomials', '["Factor 2x^3 + 8x^2 + 6x completely over the integers.", "Determine whether x^2 - 9 is fully factored as (x - 3)(x + 3).", "Identify the missing factorization step in 3a(a^2 - 4)."]'::jsonb, 'approved', 'in_depth', 'topic', 'gcf_factoring_and_grouping'),
('irreducible_polynomial_over_integers', 'Irreducible polynomial over the integers', 'Irreducible polynomial over the integers', 'A polynomial is irreducible over the integers if it cannot be factored into lower-degree polynomial factors with integer coefficients. This is different from being unfactorable over all number systems.', 'polynomials', '["Determine whether x^2 + 5x + 1 factors over the integers.", "Classify x^2 + 4 as irreducible over the integers.", "Identify why x^2 - 2 is irreducible over the integers but not over the reals."]'::jsonb, 'approved', 'in_depth', 'topic', 'gcf_factoring_and_grouping'),
('verifying_factorization_by_multiplication', 'Verifying polynomial factorization by multiplication', 'Verifying polynomial factorization by multiplication', 'A proposed factorization can be checked by multiplying the factors to see whether the original polynomial is recovered. This helps detect incorrect factoring.', 'polynomials', '["Verify that (x + 2)(x + 3) equals x^2 + 5x + 6.", "Check whether 2a(a - 4) is a correct factorization of 2a^2 - 8a.", "Determine whether the proposed factors multiply to the original polynomial."]'::jsonb, 'approved', 'in_depth', 'topic', 'gcf_factoring_and_grouping')
ON CONFLICT (id) DO NOTHING;

-- ─── quadratic_and_special_form_factoring topics ──────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('factoring_monic_quadratic_trinomials', 'Factoring monic quadratic trinomials', 'Factoring monic quadratic trinomials', 'A monic quadratic trinomial x^2 + bx + c can be factored by finding two numbers whose product is c and sum is b. This targets leading coefficient 1.', 'polynomials', '["Factor x^2 + 7x + 12.", "Factor x^2 - 5x + 6.", "Rewrite x^2 + x - 20 as a product of binomials."]'::jsonb, 'approved', 'in_depth', 'topic', 'quadratic_and_special_form_factoring'),
('factoring_nonmonic_quadratic_trinomials', 'Factoring non-monic quadratic trinomials', 'Factoring non-monic quadratic trinomials', 'A non-monic quadratic trinomial ax^2 + bx + c with a not equal to 1 requires accounting for the leading coefficient when forming binomial factors.', 'polynomials', '["Factor 2x^2 + 7x + 3.", "Factor 6a^2 - 5a - 6.", "Rewrite 3m^2 + 10m + 8 as a product of binomials."]'::jsonb, 'approved', 'in_depth', 'topic', 'quadratic_and_special_form_factoring'),
('factoring_trinomials_ac_method', 'Factoring trinomials by the ac method', 'Factoring trinomials by the ac method', 'The ac method factors ax^2 + bx + c by finding numbers that multiply to ac and add to b, splitting the middle term, and factoring by grouping.', 'polynomials', '["Factor 6x^2 + 11x + 3 using the ac method.", "Split the middle term in 4a^2 - 4a - 15.", "Factor 10m^2 + 13m - 3 by grouping after splitting."]'::jsonb, 'approved', 'in_depth', 'topic', 'quadratic_and_special_form_factoring'),
('factoring_quadratic_with_negative_constant', 'Factoring quadratics with negative constant term', 'Factoring quadratics with negative constant term', 'A quadratic trinomial with a negative constant term factors into binomials with opposite-sign constants. This targets sign reasoning in factor pairs.', 'polynomials', '["Factor x^2 + 3x - 18.", "Factor 2a^2 - 7a - 15.", "Identify the sign pattern in m^2 - m - 30."]'::jsonb, 'approved', 'in_depth', 'topic', 'quadratic_and_special_form_factoring'),
('factoring_quadratic_positive_constant_negative_middle', 'Factoring quadratics with positive constant and negative middle term', 'Factoring quadratics with positive constant and negative middle term', 'A quadratic trinomial with positive constant term and negative middle coefficient factors into binomials whose constants are both negative when integer factoring is possible.', 'polynomials', '["Factor x^2 - 9x + 20.", "Factor 3a^2 - 14a + 8.", "Determine the sign pattern for m^2 - 11m + 24."]'::jsonb, 'approved', 'in_depth', 'topic', 'quadratic_and_special_form_factoring'),
('factoring_perfect_square_trinomials', 'Factoring perfect-square trinomials', 'Factoring perfect-square trinomials', 'A perfect-square trinomial has the form a^2 + 2ab + b^2 or a^2 - 2ab + b^2 and factors as a squared binomial. This targets recognition of square structure.', 'polynomials', '["Factor x^2 + 10x + 25.", "Factor 4a^2 - 12a + 9.", "Identify whether m^2 + 14m + 49 is a perfect-square trinomial."]'::jsonb, 'approved', 'in_depth', 'topic', 'quadratic_and_special_form_factoring'),
('recognizing_nonfactorable_quadratic_trinomials_over_integers', 'Recognizing quadratics not factorable over integers', 'Recognizing quadratics not factorable over integers', 'Some quadratic trinomials do not factor into binomials with integer coefficients. This topic focuses on recognizing when integer factor pairs do not exist.', 'polynomials', '["Determine whether x^2 + x + 1 factors over the integers.", "Identify why x^2 + 5x + 5 is not factorable over integers.", "Classify 2a^2 + 3a + 7 as factorable or irreducible over the integers."]'::jsonb, 'approved', 'in_depth', 'topic', 'quadratic_and_special_form_factoring'),
('factoring_quadratic_after_gcf', 'Factoring quadratics after removing a GCF', 'Factoring quadratics after removing a GCF', 'Some quadratic expressions must first have a greatest common factor removed before the remaining trinomial or binomial can be factored further.', 'polynomials', '["Factor 2x^2 + 10x + 12 completely.", "Rewrite 3a^2 - 27 as a product by first factoring the GCF.", "Factor 5m^2 - 20m + 15 completely."]'::jsonb, 'approved', 'in_depth', 'topic', 'quadratic_and_special_form_factoring'),
('factoring_difference_of_squares', 'Factoring difference of squares', 'Factoring difference of squares', 'A difference of squares has the form A^2 - B^2 and factors as (A - B)(A + B). This applies when both terms are perfect squares and subtraction separates them.', 'polynomials', '["Factor x^2 - 49.", "Factor a^4 - 16.", "Rewrite 25m^2 - 9 as a product of conjugates."]'::jsonb, 'approved', 'in_depth', 'topic', 'quadratic_and_special_form_factoring'),
('factoring_difference_of_squares_with_coefficients', 'Factoring difference of squares with coefficients', 'Factoring difference of squares with coefficients', 'Difference-of-squares factoring may involve squared coefficients, such as 9x^2 - 64. Each term must be recognized as a square.', 'polynomials', '["Factor 9x^2 - 25.", "Rewrite 16a^4 - 81 as a product.", "Factor 49m^2 - 4n^2."]'::jsonb, 'approved', 'in_depth', 'topic', 'quadratic_and_special_form_factoring'),
('factoring_difference_of_squares_multivariable', 'Factoring multivariable difference of squares', 'Factoring multivariable difference of squares', 'A difference of squares can involve multiple variables, such as x^2 - y^2 or 4a^2b^2 - 9c^2. Each squared term becomes part of conjugate factors.', 'polynomials', '["Factor x^2 - y^2.", "Factor 4a^2 - 25b^2.", "Rewrite m^4n^2 - 16 as a product."]'::jsonb, 'approved', 'in_depth', 'topic', 'quadratic_and_special_form_factoring'),
('factoring_sum_of_cubes', 'Factoring sum of cubes', 'Factoring sum of cubes', 'A sum of cubes has the form A^3 + B^3 and factors as (A + B)(A^2 - AB + B^2). This is a special cubic factoring pattern.', 'polynomials', '["Factor x^3 + 8.", "Factor 27a^3 + 64.", "Rewrite m^6 + 125 as a sum of cubes."]'::jsonb, 'approved', 'in_depth', 'topic', 'quadratic_and_special_form_factoring'),
('factoring_difference_of_cubes', 'Factoring difference of cubes', 'Factoring difference of cubes', 'A difference of cubes has the form A^3 - B^3 and factors as (A - B)(A^2 + AB + B^2). This is distinct from difference of squares.', 'polynomials', '["Factor x^3 - 27.", "Factor 8a^3 - 125.", "Rewrite m^6 - 64 as a difference of cubes."]'::jsonb, 'approved', 'in_depth', 'topic', 'quadratic_and_special_form_factoring'),
('factoring_quadratic_form_polynomials', 'Factoring polynomials in quadratic form', 'Factoring polynomials in quadratic form', 'A polynomial in quadratic form has three terms that behave like u^2 + bu + c after substituting a repeated expression or power for u. This targets structures such as x^4 + 5x^2 + 6.', 'polynomials', '["Factor x^4 + 5x^2 + 6 by treating x^2 as a variable.", "Rewrite a^6 - 7a^3 + 10 using quadratic-form factoring.", "Factor (x + 1)^2 + 5(x + 1) + 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'quadratic_and_special_form_factoring'),
('factoring_biquadratic_polynomials', 'Factoring biquadratic polynomials', 'Factoring biquadratic polynomials', 'A biquadratic polynomial contains powers such as x^4, x^2, and a constant, allowing factoring as a quadratic in x^2. This is a specific quadratic-form structure.', 'polynomials', '["Factor x^4 - 13x^2 + 36.", "Factor a^4 + 2a^2 - 15.", "Rewrite m^4 - 5m^2 + 4 as a product."]'::jsonb, 'approved', 'in_depth', 'topic', 'quadratic_and_special_form_factoring'),
('factoring_higher_degree_with_gcf_and_quadratic', 'Factoring higher-degree polynomials with GCF and quadratic factors', 'Factoring higher-degree polynomials with GCF and quadratic factors', 'Some higher-degree polynomials are factored by first removing a monomial GCF, leaving a quadratic or special-form factor. This combines GCF and quadratic factoring.', 'polynomials', '["Factor x^3 + 5x^2 + 6x completely.", "Rewrite 2a^4 - 8a^2 as a product.", "Factor 3m^5 - 27m completely."]'::jsonb, 'approved', 'in_depth', 'topic', 'quadratic_and_special_form_factoring')
ON CONFLICT (id) DO NOTHING;

-- ─── polynomial_division_and_factor_theorems topics ───────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('polynomial_division_by_monomial', 'Polynomial division by a monomial', 'Polynomial division by a monomial', 'Dividing a polynomial by a monomial is done term-by-term by dividing coefficients and subtracting exponents of matching variable bases. This requires every term in the numerator to be divided.', 'polynomials', '["Divide 6x^4 - 9x^2 by 3x.", "Rewrite (12a^5 - 8a^3 + 4a)/4a.", "Determine the quotient of 15m^6 + 10m^3 divided by 5m^2."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_division_and_factor_theorems'),
('polynomial_long_division_by_binomial', 'Polynomial long division by a binomial', 'Polynomial long division by a binomial', 'Polynomial long division by a binomial repeatedly divides leading terms, multiplies, subtracts, and brings down terms until the remainder has lower degree than the divisor.', 'polynomials', '["Divide x^3 + 2x^2 - 5x + 6 by x + 3.", "Find the quotient and remainder when 2a^3 - a + 4 is divided by a - 1.", "Use long division to divide m^4 - 1 by m + 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_division_and_factor_theorems'),
('polynomial_long_division_missing_terms', 'Polynomial long division with missing terms', 'Polynomial long division with missing terms', 'Long division requires zero placeholders for missing powers so subtraction and alignment stay consistent. This targets sparse polynomial dividends.', 'polynomials', '["Divide x^4 - 3x + 2 by x - 1 using missing-term placeholders.", "Insert zero terms before dividing a^5 + 4a^2 - 7 by a + 2.", "Use long division on m^3 + 8 with zero placeholders."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_division_and_factor_theorems'),
('polynomial_long_division_by_higher_degree_divisor', 'Polynomial long division by higher-degree divisors', 'Polynomial long division by higher-degree divisors', 'A polynomial can be divided by a divisor of degree greater than 1 using long division. The remainder must have degree less than the divisor.', 'polynomials', '["Divide x^4 + x^2 - 1 by x^2 + 1.", "Find the quotient and remainder for a^5 - a divided by a^2 - 3.", "Determine the remainder degree when dividing by a quadratic divisor."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_division_and_factor_theorems'),
('synthetic_division_by_x_minus_c', 'Synthetic division by x - c', 'Synthetic division by x - c', 'Synthetic division is a shortcut for dividing a polynomial by a monic linear divisor of the form x - c. It uses coefficients and the value c.', 'polynomials', '["Use synthetic division to divide x^3 - 4x + 1 by x - 2.", "Divide 2a^3 + 3a^2 - a + 5 by a + 1 using synthetic division.", "Identify the c-value for synthetic division by x - 7."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_division_and_factor_theorems'),
('synthetic_division_with_missing_terms', 'Synthetic division with missing terms', 'Synthetic division with missing terms', 'Synthetic division requires zero coefficients for missing powers in the dividend. Omitting them changes the quotient and remainder.', 'polynomials', '["Use synthetic division on x^4 - 5x + 6 divided by x - 2.", "Insert missing coefficients before dividing a^5 + a^2 - 1 by a + 3.", "Determine the coefficient row for m^3 + 8 divided by m + 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_division_and_factor_theorems'),
('synthetic_division_sign_of_c', 'Sign of c in synthetic division', 'Sign of c in synthetic division', 'For a divisor x - c, synthetic division uses c, so a divisor x + c uses the negative value. This targets a common sign error.', 'polynomials', '["Identify the synthetic value for division by x + 4.", "Determine the c-value for dividing by a - 6.", "Use the correct sign when dividing m^3 - 1 by m + 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_division_and_factor_theorems'),
('synthetic_division_limitations_linear_monic_divisor', 'Synthetic division limitations', 'Synthetic division limitations', 'Standard synthetic division applies directly to monic linear divisors of the form x - c. Other divisors may require adjustment or long division.', 'polynomials', '["Determine whether synthetic division applies directly to division by x^2 + 1.", "Identify why dividing by 2x - 3 is not the basic x - c form.", "Classify x + 5 as a valid divisor for standard synthetic division."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_division_and_factor_theorems'),
('quotient_remainder_form_polynomial_division', 'Quotient-remainder form of polynomial division', 'Quotient-remainder form of polynomial division', 'Polynomial division can be written as dividend = divisor · quotient + remainder, where the remainder degree is less than the divisor degree.', 'polynomials', '["Write the quotient-remainder form after dividing p(x) by x - 2.", "Identify the quotient and remainder in a polynomial division result.", "Determine whether a remainder has valid degree for a given divisor."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_division_and_factor_theorems'),
('remainder_theorem', 'Remainder Theorem', 'Remainder Theorem', 'When a polynomial p(x) is divided by x - c, the remainder is p(c). This connects polynomial evaluation to division by a linear factor.', 'polynomials', '["Use the Remainder Theorem to find the remainder when p(x) is divided by x - 3.", "Determine p(2) to find the remainder for division by x - 2.", "Identify the remainder when f(x) is divided by x + 4."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_division_and_factor_theorems'),
('factor_theorem', 'Factor Theorem', 'Factor Theorem', 'A linear expression x - c is a factor of p(x) exactly when p(c) = 0. This connects roots, zeros, and divisibility.', 'polynomials', '["Use the Factor Theorem to determine whether x - 5 is a factor of p(x).", "Check whether x + 2 is a factor by evaluating p(-2).", "Identify the factor corresponding to the zero x = 7."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_division_and_factor_theorems'),
('polynomial_factor_from_zero', 'Polynomial factor from a zero', 'Polynomial factor from a zero', 'If c is a zero of a polynomial, then x - c is a factor of the polynomial. This turns known zeros into linear factors.', 'polynomials', '["Write the factor corresponding to the zero x = -3.", "Identify the linear factor created by c = 4.", "Determine the factor of p(x) if p(6) = 0."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_division_and_factor_theorems'),
('polynomial_remainder_from_evaluation', 'Polynomial remainder from evaluation', 'Polynomial remainder from evaluation', 'Evaluating p(c) gives the remainder when p(x) is divided by x - c. This is the computational use of the Remainder Theorem.', 'polynomials', '["Find the remainder when p(x) = x^3 - 2x + 1 is divided by x - 2.", "Evaluate f(-1) to determine the remainder for division by x + 1.", "Determine the remainder without doing full polynomial division."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_division_and_factor_theorems'),
('divisor_degree_and_remainder_degree', 'Divisor degree and remainder degree', 'Divisor degree and remainder degree', 'In polynomial division, the remainder must have degree less than the divisor. This controls when the division process stops.', 'polynomials', '["Determine the maximum possible remainder degree when dividing by a quadratic.", "Identify whether 3x + 1 is a valid remainder after division by x^2 - 4.", "Classify the possible remainder when dividing by x - 5."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_division_and_factor_theorems'),
('polynomial_divisibility_by_factor', 'Polynomial divisibility by a factor', 'Polynomial divisibility by a factor', 'A polynomial is divisible by a factor when division leaves remainder 0. This can be checked by division or by evaluating the related zero.', 'polynomials', '["Determine whether x^3 - 8 is divisible by x - 2.", "Check whether a + 1 divides a^4 - 1.", "Identify whether p(x) has zero remainder when divided by x - c."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_division_and_factor_theorems')
ON CONFLICT (id) DO NOTHING;

-- ─── polynomial_equations_and_roots topics ────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('zero_product_property_polynomial_equations', 'Zero product property in polynomial equations', 'Zero product property in polynomial equations', 'If a product of factors equals zero, then at least one factor must equal zero. This is the core principle for solving factored polynomial equations.', 'polynomials', '["Use the zero product property on (x - 3)(x + 5) = 0.", "Identify the factor equations from x(x - 7)(x + 1) = 0.", "Determine why each factor is set equal to zero in a polynomial equation."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_equations_and_roots'),
('solving_factored_polynomial_equations', 'Solving factored polynomial equations', 'Solving factored polynomial equations', 'A polynomial equation written as a product equal to zero can be solved by setting each factor equal to zero. This focuses on already-factored form.', 'polynomials', '["Solve (x + 2)(x - 6) = 0.", "Find the roots of x(x - 4)(x + 3) = 0.", "Determine all solutions of (2a - 1)(a + 5) = 0."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_equations_and_roots'),
('solving_polynomial_equations_by_gcf_factoring', 'Solving polynomial equations by GCF factoring', 'Solving polynomial equations by GCF factoring', 'Some polynomial equations require factoring out a greatest common factor before the zero product property can be applied. This often reveals a zero root.', 'polynomials', '["Solve x^3 + 5x^2 = 0.", "Find all roots of 3a^4 - 12a^2 = 0.", "Determine the solutions of 2m^3 - 10m = 0."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_equations_and_roots'),
('solving_quadratic_equations_by_factoring', 'Solving quadratic equations by factoring', 'Solving quadratic equations by factoring', 'A quadratic equation can be solved by rewriting it with zero on one side, factoring the quadratic, and applying the zero product property. This is factoring-based solving only.', 'polynomials', '["Solve x^2 + 5x + 6 = 0 by factoring.", "Find the solutions of 2a^2 - 7a + 3 = 0 by factoring.", "Rewrite and solve m^2 - 9 = 0 using factoring."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_equations_and_roots'),
('solving_higher_degree_polynomial_equations_by_factoring', 'Solving higher-degree polynomial equations by factoring', 'Solving higher-degree polynomial equations by factoring', 'Higher-degree polynomial equations can sometimes be solved by factoring into lower-degree factors and applying the zero product property. This excludes numerical root approximation.', 'polynomials', '["Solve x^3 - 4x = 0 by factoring.", "Find all real roots of a^4 - 5a^2 + 4 = 0.", "Determine the solutions of m^3 + 2m^2 - 9m - 18 = 0."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_equations_and_roots'),
('solving_polynomial_equations_using_difference_of_squares', 'Solving polynomial equations using difference of squares', 'Solving polynomial equations using difference of squares', 'Polynomial equations containing a difference of squares can be factored into conjugates and solved using the zero product property.', 'polynomials', '["Solve x^2 - 25 = 0.", "Find the roots of 4a^2 - 81 = 0.", "Determine the solutions of m^4 - 16 = 0."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_equations_and_roots'),
('solving_polynomial_equations_using_sum_difference_cubes', 'Solving polynomial equations using sums or differences of cubes', 'Solving polynomial equations using sums or differences of cubes', 'Polynomial equations involving A^3 + B^3 or A^3 - B^3 can be factored using cube formulas before solving. This targets cubic special-form equations.', 'polynomials', '["Solve x^3 - 8 = 0 by factoring.", "Find the real solution of a^3 + 27 = 0.", "Determine the roots of m^6 - 64 = 0 using cube structure."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_equations_and_roots'),
('repeated_roots_in_factored_equations', 'Repeated roots in factored equations', 'Repeated roots in factored equations', 'A repeated root occurs when the same linear factor appears more than once in a factored polynomial equation. The solution value is listed once but has multiplicity.', 'polynomials', '["Identify the repeated root in (x - 2)^3(x + 1) = 0.", "Determine the roots and multiplicities of x^2(x - 5) = 0.", "Classify x = -4 as a repeated or non-repeated root in (x + 4)^2 = 0."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_equations_and_roots'),
('polynomial_equations_in_quadratic_form', 'Polynomial equations in quadratic form', 'Polynomial equations in quadratic form', 'Some polynomial equations can be solved by treating a repeated power or expression as a temporary variable, solving a quadratic-form equation, and translating back.', 'polynomials', '["Solve x^4 - 5x^2 + 4 = 0.", "Find the roots of a^6 - 7a^3 + 6 = 0.", "Determine the solutions of (x - 1)^2 - 5(x - 1) + 6 = 0."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_equations_and_roots'),
('real_solution_count_from_factored_polynomial', 'Real solution count from factored polynomial form', 'Real solution count from factored polynomial form', 'The real solutions of a factored polynomial equation can be counted from real linear factors and real roots of remaining factors. Repeated roots count as one distinct real solution unless multiplicity is requested.', 'polynomials', '["Count the distinct real solutions of x(x - 3)^2(x + 4) = 0.", "Identify the number of real roots in (x - 1)(x^2 + 4) = 0.", "Determine how many real solutions a factored polynomial equation has."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_equations_and_roots'),
('irreducible_quadratic_factor_no_real_roots', 'Irreducible quadratic factors and no real roots', 'Irreducible quadratic factors and no real roots', 'An irreducible quadratic factor over the reals contributes no real linear roots. This helps distinguish all roots from real roots in factored polynomial equations.', 'polynomials', '["Identify why x^2 + 9 gives no real roots in (x - 2)(x^2 + 9) = 0.", "Determine the real solutions of (a + 1)(a^2 + 4) = 0.", "Classify the quadratic factor x^2 + 1 as contributing real or nonreal roots."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_equations_and_roots'),
('checking_polynomial_equation_solutions', 'Checking polynomial equation solutions', 'Checking polynomial equation solutions', 'A proposed solution to a polynomial equation can be checked by substituting it into the original equation. This verifies roots found by factoring or division.', 'polynomials', '["Check whether x = 3 solves x^3 - 4x^2 + x + 6 = 0.", "Verify the roots of a factored polynomial equation.", "Determine whether m = -2 satisfies m^4 - 16 = 0."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_equations_and_roots')
ON CONFLICT (id) DO NOTHING;

-- ─── polynomial_zeros_and_graph_behavior topics ───────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('polynomial_zero_factor_relationship', 'Zero-factor relationship', 'Zero-factor relationship', 'A real number c is a zero of a polynomial function exactly when x - c is a factor of the polynomial. This connects roots, zeros, factors, and x-intercepts.', 'polynomials', '["Identify the factor corresponding to the zero x = 4.", "Determine the zero associated with the factor x + 7.", "Classify x = -2 as a zero when x + 2 is a factor."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_zeros_and_graph_behavior'),
('zeros_from_factored_form', 'Zeros from factored form', 'Zeros from factored form', 'A polynomial in factored form reveals zeros by setting each factor equal to zero. Multiplicity may also be visible from repeated factors.', 'polynomials', '["Find the zeros of f(x) = (x - 3)(x + 2).", "Identify the zeros of p(x) = x(x - 5)^2.", "Determine the zeros from f(x) = 2(x + 1)(x - 4)(x + 6)."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_zeros_and_graph_behavior'),
('y_intercept_of_polynomial_function', 'Y-intercept of a polynomial function', 'Y-intercept of a polynomial function', 'The y-intercept of a polynomial function occurs at x = 0 and equals the polynomial''s value at 0. In standard form, this is the constant term.', 'polynomials', '["Find the y-intercept of f(x) = 3x^4 - 2x + 7.", "Determine f(0) for p(x) = -5x^3 + 8x^2 - 1.", "Identify the y-intercept from the standard form of a polynomial."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_zeros_and_graph_behavior'),
('x_intercepts_from_real_zeros', 'X-intercepts from real zeros', 'X-intercepts from real zeros', 'Real zeros of a polynomial function correspond to x-intercepts on its graph. A zero x = c gives the point (c, 0).', 'polynomials', '["Write the x-intercepts of f(x) = (x - 2)(x + 5).", "Identify the graph intercepts from zeros x = -1, 0, and 4.", "Determine the x-intercepts of p(x) = x^2 - 9."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_zeros_and_graph_behavior'),
('multiplicity_even_touch_behavior', 'Even multiplicity touch behavior', 'Even multiplicity touch behavior', 'At a zero with even multiplicity, the graph of a polynomial typically touches the x-axis and turns around instead of crossing. This is general polynomial multiplicity behavior.', 'polynomials', '["Identify the behavior at x = 3 for f(x) = (x - 3)^2(x + 1).", "Determine whether a graph crosses or touches at a zero with multiplicity 4.", "Classify the x-axis behavior of a repeated even-multiplicity root."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_zeros_and_graph_behavior'),
('multiplicity_odd_cross_behavior', 'Odd multiplicity cross behavior', 'Odd multiplicity cross behavior', 'At a zero with odd multiplicity, the graph of a polynomial crosses the x-axis. Higher odd multiplicities may flatten as they cross.', 'polynomials', '["Identify the behavior at x = -2 for f(x) = (x + 2)^3.", "Determine whether a graph crosses or touches at a zero with multiplicity 5.", "Classify the x-axis behavior of a simple root."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_zeros_and_graph_behavior'),
('end_behavior_even_degree_positive_leading', 'End behavior: even degree, positive leading coefficient', 'End behavior: even degree, positive leading coefficient', 'An even-degree polynomial with positive leading coefficient rises on both ends. This follows from the leading term dominating for large positive and negative inputs.', 'polynomials', '["Determine the end behavior of f(x) = 2x^4 - 3x + 1.", "Identify the graph end directions for a positive-leading quartic.", "Classify both ends of an even-degree polynomial with positive leading coefficient."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_zeros_and_graph_behavior'),
('end_behavior_even_degree_negative_leading', 'End behavior: even degree, negative leading coefficient', 'End behavior: even degree, negative leading coefficient', 'An even-degree polynomial with negative leading coefficient falls on both ends. This is the opposite vertical behavior of positive-leading even-degree polynomials.', 'polynomials', '["Determine the end behavior of f(x) = -3x^6 + x^2 - 1.", "Identify the graph end directions for a negative-leading quartic.", "Classify both ends of an even-degree polynomial with negative leading coefficient."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_zeros_and_graph_behavior'),
('end_behavior_odd_degree_positive_leading', 'End behavior: odd degree, positive leading coefficient', 'End behavior: odd degree, positive leading coefficient', 'An odd-degree polynomial with positive leading coefficient falls to the left and rises to the right. This is the standard positive-leading odd-degree behavior.', 'polynomials', '["Determine the end behavior of f(x) = x^5 - 2x.", "Identify the graph end directions for a positive-leading cubic.", "Classify the left and right ends of an odd-degree polynomial with positive leading coefficient."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_zeros_and_graph_behavior'),
('end_behavior_odd_degree_negative_leading', 'End behavior: odd degree, negative leading coefficient', 'End behavior: odd degree, negative leading coefficient', 'An odd-degree polynomial with negative leading coefficient rises to the left and falls to the right. This is the reflected version of positive-leading odd-degree behavior.', 'polynomials', '["Determine the end behavior of f(x) = -2x^3 + 7x - 1.", "Identify the graph end directions for a negative-leading quintic.", "Classify the left and right ends of an odd-degree polynomial with negative leading coefficient."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_zeros_and_graph_behavior'),
('end_behavior_from_leading_term', 'End behavior from leading term', 'End behavior from leading term', 'The leading term of a polynomial determines its end behavior because lower-degree terms become negligible for very large input magnitude.', 'polynomials', '["Use the leading term to determine the end behavior of 4x^7 - 100x^2 + 1.", "Identify which term controls the ends of a polynomial graph.", "Determine the end behavior of a polynomial without graphing it."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_zeros_and_graph_behavior'),
('maximum_turning_points_degree_n', 'Maximum turning points from degree', 'Maximum turning points from degree', 'A polynomial of degree n has at most n - 1 turning points. This gives an upper bound, not an exact number.', 'polynomials', '["Determine the maximum number of turning points for a degree 5 polynomial.", "Identify whether a quartic can have more than 3 turning points.", "Find the largest possible number of turns for a cubic polynomial."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_zeros_and_graph_behavior'),
('polynomial_graph_smoothness_continuity', 'Polynomial graph smoothness and continuity', 'Polynomial graph smoothness and continuity', 'Polynomial graphs are continuous and smooth, with no breaks, holes, jumps, corners, or asymptotes. This distinguishes polynomial graphs from rational, radical, and piecewise graphs.', 'polynomials', '["Identify whether a graph with a vertical asymptote can represent a polynomial.", "Determine why a polynomial graph has no holes or jumps.", "Classify a smooth unbroken curve as consistent with polynomial behavior."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_zeros_and_graph_behavior'),
('degree_from_polynomial_graph_behavior', 'Degree clues from polynomial graph behavior', 'Degree clues from polynomial graph behavior', 'A polynomial graph''s end behavior and number of turns can give clues about possible degree parity and minimum degree. This is degree reasoning from graph features.', 'polynomials', '["Determine whether a polynomial graph with opposite end behavior has odd or even degree.", "Identify the minimum possible degree of a graph with 3 turning points.", "Classify possible degrees from a graph''s end behavior and turns."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_zeros_and_graph_behavior'),
('polynomial_graph_from_factored_form', 'Polynomial graph features from factored form', 'Polynomial graph features from factored form', 'Factored form reveals zeros, multiplicities, and often the y-intercept and end behavior, allowing a general polynomial graph to be sketched. This is general polynomial graphing, not quadratic vertex analysis.', 'polynomials', '["Sketch key features of f(x) = (x - 2)^2(x + 3).", "Identify zeros and multiplicities from p(x) = -x(x + 1)(x - 4)^3.", "Determine the intercept and end-behavior information from a factored polynomial."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_zeros_and_graph_behavior')
ON CONFLICT (id) DO NOTHING;

-- ─── polynomial_tables_and_finite_differences topics ──────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('constant_first_differences_linear_polynomial', 'Constant first differences and linear polynomials', 'Constant first differences and linear polynomials', 'For equally spaced inputs, constant first differences indicate a linear polynomial relationship. This is table-based polynomial recognition.', 'polynomials', '["Identify the polynomial degree from a table with constant first differences.", "Determine whether a table represents a linear polynomial using first differences.", "Classify a sequence of y-values with equal first differences."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_tables_and_finite_differences'),
('constant_second_differences_quadratic_polynomial', 'Constant second differences and quadratic polynomials', 'Constant second differences and quadratic polynomials', 'For equally spaced inputs, constant second differences indicate a quadratic polynomial relationship. This connects tables to degree 2 behavior.', 'polynomials', '["Identify a quadratic relationship from constant second differences.", "Determine whether a table could represent a degree 2 polynomial.", "Compute second differences to classify a polynomial table."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_tables_and_finite_differences'),
('constant_nth_differences_polynomial_degree', 'Constant nth differences and polynomial degree', 'Constant nth differences and polynomial degree', 'For equally spaced inputs, the first level of constant nonzero finite differences indicates the polynomial''s degree. This generalizes linear and quadratic table patterns.', 'polynomials', '["Determine the polynomial degree from constant third differences.", "Identify which difference level first becomes constant in a table.", "Classify a polynomial table using finite differences."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_tables_and_finite_differences'),
('finite_differences_require_equal_input_spacing', 'Equal input spacing for finite differences', 'Equal input spacing for finite differences', 'Finite-difference degree patterns apply directly only when input values are equally spaced. Unequal spacing can make ordinary difference patterns misleading.', 'polynomials', '["Check whether a table has equally spaced x-values before using finite differences.", "Determine why finite differences are not reliable for inputs 1, 2, 4, and 7.", "Identify whether a table is suitable for degree classification by differences."]'::jsonb, 'approved', 'in_depth', 'topic', 'polynomial_tables_and_finite_differences')
ON CONFLICT (id) DO NOTHING;
