-- Category
INSERT INTO learn_categories (id, name, description, order_index)
VALUES ('representations', 'Representations', 'The format or medium in which a problem presents mathematical content — symbolic, verbal, contextual, graphical, tabular, diagrammatic, or by answer form.', 100)
ON CONFLICT (id) DO NOTHING;

-- ─── Representation keywords ──────────────────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('symbolic', 'Symbolic', 'Symbolic', 'The problem is represented mainly with mathematical symbols, such as expressions, equations, inequalities, formulas, functions, systems, or notation.', 'representations', '["Solve 3x - 7 = 14.", "Simplify 4x + 7x - 3.", "Factor x^2 + 7x + 12."]'::jsonb, 'approved', 'in_depth', 'topic', NULL),
('verbal', 'Verbal', 'Verbal', 'The problem is represented mainly in words rather than symbols. Use this for math phrases, descriptions, definitions, or worded relationships.', 'representations', '["Write an expression for five less than twice a number.", "A number is increased by 7 and then doubled.", "The sum of two consecutive integers is 41."]'::jsonb, 'approved', 'in_depth', 'topic', NULL),
('contextual', 'Contextual', 'Contextual', 'The problem is represented through a real or realistic situation with quantities, units, constraints, or interpretation. Use this when context affects setup, meaning, domain, or reasonableness.', 'representations', '["A ticket costs 12 dollars plus a 5 dollar service fee.", "A ball is launched from a height of 6 feet.", "A store discounts an item by 20%."]'::jsonb, 'approved', 'in_depth', 'topic', NULL),
('graphical', 'Graphical', 'Graphical', 'The problem uses a graph, coordinate plane, curve, line, number line, shaded region, or plotted visual as part of the mathematical representation.', 'representations', '["Identify the x-intercepts from the graph.", "Graph x <= 3 on a number line.", "Sketch the parabola y = (x - 2)^2 + 1."]'::jsonb, 'approved', 'in_depth', 'topic', NULL),
('tabular', 'Tabular', 'Tabular', 'The problem uses values organized in a table, input-output chart, frequency table, two-way table, or finite-difference table.', 'representations', '["Determine whether the table represents a linear relationship.", "Find f(4) from the input-output table.", "Use the frequency table to find a probability."]'::jsonb, 'approved', 'in_depth', 'topic', NULL),
('diagram', 'Diagram', 'Diagram', 'The problem uses a non-graph visual such as a geometric figure, labeled shape, tree diagram, flowchart, measurement diagram, or visual layout.', 'representations', '["Find the missing side length from the diagram.", "Use the tree diagram to find the probability.", "Determine the area of the shaded figure."]'::jsonb, 'approved', 'in_depth', 'topic', NULL),
('exact_form', 'Exact form', 'Exact form', 'The expected mathematical representation keeps values exact using fractions, radicals, pi, logarithms, or symbolic expressions rather than rounded decimals.', 'representations', '["Find the exact value of sin(pi/3).", "Solve x^2 - 2 = 0 exactly.", "Give the answer in simplest radical form."]'::jsonb, 'approved', 'in_depth', 'topic', NULL),
('approximate_form', 'Approximate form', 'Approximate form', 'The expected mathematical representation is rounded, estimated, or given as a decimal approximation rather than left in exact symbolic form.', 'representations', '["Approximate the solution to the nearest tenth.", "Round the answer to two decimal places.", "Estimate sqrt(47)."]'::jsonb, 'approved', 'in_depth', 'topic', NULL)
ON CONFLICT (id) DO NOTHING;
