-- Category
INSERT INTO learn_categories (id, name, description, order_index)
VALUES ('exponents_and_radicals', 'Exponents and Radicals', 'Exponent laws, radical notation, rational exponents, and equations involving powers and roots.', 5)
ON CONFLICT (id) DO NOTHING;

-- ─── Umbrella keywords ────────────────────────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('exponent_notation_and_structure', 'Exponent Notation and Structure', 'Exponent Notation and Structure', 'Meaning and structure of powers, including bases, exponents, repeated multiplication, powers of products, powers of quotients, and how grouping affects the base.', 'exponents_and_radicals', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('integer_exponent_laws', 'Integer Exponent Laws', 'Integer Exponent Laws', 'Rules for rewriting powers with integer exponents, including products, quotients, powers of powers, powers of products, and powers of quotients.', 'exponents_and_radicals', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('zero_and_negative_exponent_structure', 'Zero and Negative Exponent Structure', 'Zero and Negative Exponent Structure', 'Meaning and rewriting of zero and negative exponents, including reciprocal forms, undefined cases, and positive-exponent conventions.', 'exponents_and_radicals', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('scientific_notation_with_powers_of_ten', 'Scientific Notation with Powers of Ten', 'Scientific Notation with Powers of Ten', 'Operations and comparisons involving scientific notation using exponent laws and powers of ten.', 'exponents_and_radicals', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('rational_exponent_structure', 'Rational Exponent Structure', 'Rational Exponent Structure', 'Meaning and manipulation of fractional exponents, including roots, powers, reciprocals, and equivalence between radical and exponent notation.', 'exponents_and_radicals', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('radical_notation_and_root_structure', 'Radical Notation and Root Structure', 'Radical Notation and Root Structure', 'Meaning of radicals, root indices, radicands, principal roots, even and odd roots, and real-valued restrictions.', 'exponents_and_radicals', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('radical_factor_structure_and_rewriting', 'Radical Factor Structure and Rewriting', 'Radical Factor Structure and Rewriting', 'Using perfect powers, root indices, and factor structure to rewrite radical expressions in equivalent forms.', 'exponents_and_radicals', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('radical_operations_and_like_radicals', 'Radical Operations and Like Radicals', 'Radical Operations and Like Radicals', 'Adding, subtracting, multiplying, dividing, and expanding radical expressions using like-radical structure and radical properties.', 'exponents_and_radicals', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('rationalizing_and_radical_denominators', 'Rationalizing and Radical Denominators', 'Rationalizing and Radical Denominators', 'Rewriting fractions so radicals are removed from denominators using radical factors or conjugates.', 'exponents_and_radicals', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL),
('radical_equations_and_rational_exponent_equations', 'Radical Equations and Rational-Exponent Equations', 'Radical Equations and Rational-Exponent Equations', 'Equations involving radicals or rational exponents, including isolating radical terms, using powers to remove radicals, and checking for extraneous solutions.', 'exponents_and_radicals', '[]'::jsonb, 'approved', 'umbrella', 'umbrella', NULL)
ON CONFLICT (id) DO NOTHING;

-- ─── exponent_notation_and_structure topics ───────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('base_and_exponent_identification', 'Base and exponent identification', 'Base and exponent identification', 'A power has a base being repeatedly used as a factor and an exponent indicating how many times the base appears. This focuses on reading exponent notation before applying any exponent law.', 'exponents_and_radicals', '["Identify the base and exponent in 7^4.", "Determine the base in (-3)^5.", "Identify the exponent in x^8."]'::jsonb, 'approved', 'in_depth', 'topic', 'exponent_notation_and_structure'),
('positive_integer_exponents_as_repeated_multiplication', 'Positive integer exponents as repeated multiplication', 'Positive integer exponents as repeated multiplication', 'A positive integer exponent represents repeated multiplication of the same base. This excludes zero, negative, and rational exponents.', 'exponents_and_radicals', '["Rewrite 5^3 as repeated multiplication.", "Express x^4 as a product of repeated factors.", "Determine which repeated product matches a^6."]'::jsonb, 'approved', 'in_depth', 'topic', 'exponent_notation_and_structure'),
('power_notation_for_variable_bases', 'Power notation with variable bases', 'Power notation with variable bases', 'Variable bases can be written with exponents to represent repeated multiplication of the same variable quantity. This focuses on forms like x^n and a^n.', 'exponents_and_radicals', '["Rewrite x · x · x · x using exponent notation.", "Express m · m · m as a power.", "Identify the power form of a repeated variable product."]'::jsonb, 'approved', 'in_depth', 'topic', 'exponent_notation_and_structure'),
('power_notation_for_multi_variable_bases', 'Power notation with multi-variable bases', 'Power notation with multi-variable bases', 'A grouped multi-variable product can be raised to a power when the entire product is the base. This distinguishes (xy)^n from x y^n.', 'exponents_and_radicals', '["Identify the base in (xy)^4.", "Rewrite (ab)^3 as repeated multiplication of the grouped base.", "Determine whether xy^2 and (xy)^2 have the same base."]'::jsonb, 'approved', 'in_depth', 'topic', 'exponent_notation_and_structure'),
('parenthesized_base_vs_unparenthesized_base', 'Parenthesized versus unparenthesized bases', 'Parenthesized versus unparenthesized bases', 'Parentheses determine whether an exponent applies to an entire quantity or only to the immediately preceding base. This targets forms such as (-x)^2 versus -x^2.', 'exponents_and_radicals', '["Compare the base in -4^2 and (-4)^2.", "Identify whether the exponent applies to all of 3x in (3x)^2.", "Determine the base of the power in -a^3."]'::jsonb, 'approved', 'in_depth', 'topic', 'exponent_notation_and_structure'),
('coefficient_not_in_base_without_parentheses', 'Coefficient not in base without parentheses', 'Coefficient not in base without parentheses', 'In a term like 4x^2, the exponent applies to x only, not to the coefficient 4. This distinguishes 4x^2 from (4x)^2.', 'exponents_and_radicals', '["Identify whether 3 is part of the base in 3x^2.", "Compare 5a^2 and (5a)^2.", "Determine which expression squares both the coefficient and the variable."]'::jsonb, 'approved', 'in_depth', 'topic', 'exponent_notation_and_structure'),
('exponent_applied_to_grouped_sum_or_difference', 'Powers of grouped sums and differences', 'Powers of grouped sums and differences', 'An exponent outside parentheses applies to the entire grouped sum or difference. This is structural recognition, not expansion of binomial powers.', 'exponents_and_radicals', '["Identify the base in (x + 3)^2.", "Rewrite (a - b)^3 as repeated multiplication.", "Determine whether (m + 5)^2 means m^2 + 5^2."]'::jsonb, 'approved', 'in_depth', 'topic', 'exponent_notation_and_structure'),
('powers_do_not_distribute_over_addition', 'Powers do not distribute over addition', 'Powers do not distribute over addition', 'A power of a sum is not found by applying the exponent separately to each addend. This targets the misconception that (a + b)^n equals a^n + b^n.', 'exponents_and_radicals', '["Identify the error in writing (x + 4)^2 as x^2 + 16.", "Determine whether (a + b)^3 equals a^3 + b^3.", "Correct the mistaken rewrite of (m + 2)^2."]'::jsonb, 'approved', 'in_depth', 'topic', 'exponent_notation_and_structure'),
('powers_do_not_distribute_over_subtraction', 'Powers do not distribute over subtraction', 'Powers do not distribute over subtraction', 'A power of a difference is not found by applying the exponent separately to each term. This targets errors such as (a - b)^2 = a^2 - b^2.', 'exponents_and_radicals', '["Identify the error in writing (x - 5)^2 as x^2 - 25.", "Determine whether (a - b)^2 equals a^2 - b^2.", "Correct the mistaken rewrite of (m - 3)^2."]'::jsonb, 'approved', 'in_depth', 'topic', 'exponent_notation_and_structure'),
('exponent_precedence_over_multiplication', 'Exponent precedence over multiplication', 'Exponent precedence over multiplication', 'Exponents are applied before multiplication unless grouping symbols change the structure. This focuses on exponent placement inside terms.', 'exponents_and_radicals', '["Determine whether 2x^3 means 2 times x^3 or (2x)^3.", "Identify the first operation in 4a^2.", "Evaluate 3x^2 when x = 2 using the correct exponent placement."]'::jsonb, 'approved', 'in_depth', 'topic', 'exponent_notation_and_structure'),
('exponent_precedence_over_addition', 'Exponent precedence over addition', 'Exponent precedence over addition', 'Exponents are applied before addition or subtraction unless grouping symbols change the structure. This targets expressions such as x^2 + 5.', 'exponents_and_radicals', '["Identify the first operation in x^2 + 7.", "Evaluate a^2 - 4 when a = 5.", "Determine whether x + 3^2 squares the 3 or the sum x + 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'exponent_notation_and_structure'),
('power_of_one', 'Power of one', 'Power of one', 'Any power with exponent 1 is equal to its base. This focuses on the structure a^1 = a.', 'exponents_and_radicals', '["Rewrite x^1 without the exponent.", "Determine the value of 17^1.", "Identify which expression is equivalent to (a + b)^1."]'::jsonb, 'approved', 'in_depth', 'topic', 'exponent_notation_and_structure'),
('one_as_base', 'One as a base', 'One as a base', 'The base 1 raised to any exponent remains 1. This is different from an exponent of 1.', 'exponents_and_radicals', '["Determine the value of 1^8.", "Identify the result of 1^n for a positive integer n.", "Compare 1^5 and 5^1."]'::jsonb, 'approved', 'in_depth', 'topic', 'exponent_notation_and_structure')
ON CONFLICT (id) DO NOTHING;

-- ─── integer_exponent_laws topics ─────────────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('product_rule_same_base_single_variable', 'Product rule with same single-variable base', 'Product rule with same single-variable base', 'When multiplying powers with the same variable base, the exponents are added while the base stays the same. This applies only when the bases match exactly.', 'exponents_and_radicals', '["Rewrite x^3 · x^5 as one power.", "Determine the exponent in a^4 · a^7.", "Identify the correct single-power form of m · m^6."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('product_rule_same_numeric_base', 'Product rule with same numeric base', 'Product rule with same numeric base', 'When multiplying powers with the same numeric base, the exponents are added while the base stays unchanged. This targets numeric powers such as 2^a · 2^b.', 'exponents_and_radicals', '["Rewrite 3^4 · 3^2 as one power.", "Determine the single-power form of 10^5 · 10^7.", "Identify the exponent in 2^8 · 2^3."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('product_rule_multiple_factors_same_base', 'Product rule with more than two same-base factors', 'Product rule with more than two same-base factors', 'The product rule can combine three or more powers with the same base by adding all exponents. This targets longer same-base products.', 'exponents_and_radicals', '["Rewrite x^2 · x^5 · x^7 as one power.", "Determine the exponent in a · a^3 · a^4.", "Express m^6 · m^2 · m · m^8 as one power."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('product_rule_requires_matching_bases', 'Product rule requires matching bases', 'Product rule requires matching bases', 'Exponents are added only when the multiplied powers have the same base. This prevents combining unlike bases such as x^2y^3 into one base.', 'exponents_and_radicals', '["Determine whether x^3 · y^3 can use the same-base product rule.", "Identify why 2^4 · 3^4 is not combined by adding exponents.", "Classify which factors in x^2 · x^5 · y^5 have matching bases."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('quotient_rule_same_base_single_variable', 'Quotient rule with same single-variable base', 'Quotient rule with same single-variable base', 'When dividing powers with the same variable base, the denominator exponent is subtracted from the numerator exponent. This applies only when the bases match exactly.', 'exponents_and_radicals', '["Rewrite x^8/x^3 as one power.", "Determine the exponent in a^10/a^4.", "Identify the single-power form of m^7 divided by m."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('quotient_rule_same_numeric_base', 'Quotient rule with same numeric base', 'Quotient rule with same numeric base', 'When dividing powers with the same numeric base, the exponents are subtracted while the base stays the same. This targets powers of numbers such as 5^a/5^b.', 'exponents_and_radicals', '["Rewrite 2^9/2^4 as one power.", "Determine the single-power form of 10^8/10^3.", "Identify the exponent in 7^6 divided by 7^2."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('quotient_rule_negative_exponent_result', 'Quotient rule producing a negative exponent', 'Quotient rule producing a negative exponent', 'When the denominator exponent is larger, the quotient rule produces a negative exponent. This connects quotient structure to reciprocal form.', 'exponents_and_radicals', '["Rewrite x^3/x^8 as one power.", "Determine the exponent in a^2/a^9.", "Express m^4/m^10 using a negative exponent."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('quotient_rule_zero_exponent_result', 'Quotient rule producing a zero exponent', 'Quotient rule producing a zero exponent', 'When matching powers with equal exponents are divided, the exponent difference is zero. This connects quotient structure to the zero-exponent rule.', 'exponents_and_radicals', '["Rewrite x^5/x^5 as one power.", "Determine why a^7/a^7 becomes a^0.", "Identify the value of 9^3/9^3 using exponent structure."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('power_of_power_rule', 'Power of a power rule', 'Power of a power rule', 'When a power is raised to another power, the exponents are multiplied. This targets structures like (x^a)^b.', 'exponents_and_radicals', '["Rewrite (x^3)^4 as one power.", "Determine the exponent in (a^5)^2.", "Identify the single-power form of (m^7)^3."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('power_of_power_with_negative_exponents', 'Power of a power with negative exponents', 'Power of a power with negative exponents', 'The power-of-a-power rule also applies when one or both exponents are negative. The resulting exponent is the product of the exponents.', 'exponents_and_radicals', '["Rewrite (x^-3)^4 as one power.", "Determine the exponent in (a^5)^-2.", "Identify the single-power form of (m^-6)^-3."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('power_of_power_vs_product_rule', 'Power of a power versus product rule', 'Power of a power versus product rule', 'Powers of powers multiply exponents, while products of same-base powers add exponents. This distinguishes two commonly confused exponent laws.', 'exponents_and_radicals', '["Determine whether x^3 · x^4 or (x^3)^4 uses exponent multiplication.", "Identify the difference between a^2 · a^5 and (a^2)^5.", "Classify each expression as a product rule or power-of-power rule case."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('power_of_product_rule', 'Power of a product rule', 'Power of a product rule', 'A power applied to a product applies to each factor in the product. This targets forms like (ab)^n = a^n b^n.', 'exponents_and_radicals', '["Rewrite (xy)^4 without parentheses.", "Determine the expanded power form of (3a)^2.", "Express (-2mn)^3 by applying the exponent to each factor."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('power_of_product_with_coefficients', 'Power of a product with coefficients', 'Power of a product with coefficients', 'When a product with a numerical coefficient is raised to a power, the coefficient and each variable factor are raised to that power. This targets forms like (3x)^2.', 'exponents_and_radicals', '["Rewrite (4x)^2 without parentheses.", "Determine the result of applying the exponent in (-2a)^3.", "Identify the coefficient in (5m)^2 after applying the power."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('power_of_product_multiple_variables', 'Power of a product with multiple variables', 'Power of a product with multiple variables', 'When a product with several variable factors is raised to a power, the exponent applies to each factor. This targets expressions like (xyz)^n.', 'exponents_and_radicals', '["Rewrite (abc)^3 without parentheses.", "Determine the power form of (x^2y)^4.", "Express (mn^3p)^2 by applying the power to each factor."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('power_of_quotient_rule', 'Power of a quotient rule', 'Power of a quotient rule', 'A power applied to a quotient applies to both the numerator and denominator. This targets forms like (a/b)^n.', 'exponents_and_radicals', '["Rewrite (x/y)^3 without parentheses.", "Determine the expanded power form of (2a/5)^2.", "Express (m^2/n)^4 using powers in the numerator and denominator."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('power_of_quotient_with_negative_exponents', 'Power of a quotient with negative exponents', 'Power of a quotient with negative exponents', 'A quotient raised to a negative power can be rewritten using reciprocal structure and positive exponents. This targets forms like (a/b)^-n.', 'exponents_and_radicals', '["Rewrite (x/y)^-2 using positive exponents.", "Determine the reciprocal form of (3/5)^-4.", "Express (a/b)^-3 without a negative exponent."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('same_exponent_different_bases_product', 'Same exponent with different bases in a product', 'Same exponent with different bases in a product', 'A product of powers with the same exponent can be rewritten as one grouped product raised to that exponent. This targets forms like a^n b^n = (ab)^n.', 'exponents_and_radicals', '["Rewrite x^3y^3 as a single power of a product.", "Determine whether 2^5 · 7^5 can be written as 14^5.", "Express a^4b^4c^4 as one power."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws'),
('same_exponent_different_bases_quotient', 'Same exponent with different bases in a quotient', 'Same exponent with different bases in a quotient', 'A quotient of powers with the same exponent can be rewritten as one quotient raised to that exponent. This targets forms like a^n/b^n = (a/b)^n.', 'exponents_and_radicals', '["Rewrite x^4/y^4 as a single power.", "Determine whether 12^3/4^3 can be written as 3^3.", "Express a^5/b^5 using one exponent."]'::jsonb, 'approved', 'in_depth', 'topic', 'integer_exponent_laws')
ON CONFLICT (id) DO NOTHING;

-- ─── zero_and_negative_exponent_structure topics ──────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('zero_exponent_nonzero_base', 'Zero exponent with nonzero base', 'Zero exponent with nonzero base', 'Any nonzero base raised to the zero power equals 1. The nonzero-base condition is essential.', 'exponents_and_radicals', '["Determine the value of x^0 for x ≠ 0.", "Rewrite 13^0.", "Identify the value of (a + 2)^0 when a ≠ -2."]'::jsonb, 'approved', 'in_depth', 'topic', 'zero_and_negative_exponent_structure'),
('zero_exponent_variable_base_restriction', 'Variable-base restriction for zero exponents', 'Variable-base restriction for zero exponents', 'A variable base raised to the zero power equals 1 only when the base is not zero. This targets hidden restrictions in forms like x^0.', 'exponents_and_radicals', '["State the restriction for x^0 = 1.", "Identify the excluded value in (x - 4)^0.", "Determine when (2a + 1)^0 is defined."]'::jsonb, 'approved', 'in_depth', 'topic', 'zero_and_negative_exponent_structure'),
('zero_to_zero_power_indeterminate', 'Zero to the zero power', 'Zero to the zero power', 'The expression 0^0 is treated as indeterminate or undefined in standard precalculus contexts. This distinguishes it from ordinary zero-exponent cases.', 'exponents_and_radicals', '["Classify 0^0 as a standard zero-exponent case or an exception.", "Determine why the rule a^0 = 1 requires a nonzero base.", "Identify which expression is not covered by the zero-exponent rule."]'::jsonb, 'approved', 'in_depth', 'topic', 'zero_and_negative_exponent_structure'),
('negative_exponent_as_reciprocal', 'Negative exponent as reciprocal', 'Negative exponent as reciprocal', 'A negative exponent indicates the reciprocal of the corresponding positive-exponent power. This targets forms like a^-n = 1/a^n.', 'exponents_and_radicals', '["Rewrite x^-4 using a positive exponent.", "Express 5^-2 as a reciprocal.", "Determine the positive-exponent form of a^-7."]'::jsonb, 'approved', 'in_depth', 'topic', 'zero_and_negative_exponent_structure'),
('negative_exponent_on_denominator_factor', 'Negative exponent on denominator factor', 'Negative exponent on denominator factor', 'A factor with a negative exponent in the denominator moves to the numerator with a positive exponent. This targets reciprocal movement in fractions.', 'exponents_and_radicals', '["Rewrite 1/x^-3 using positive exponents.", "Express a^2/b^-4 without negative exponents.", "Determine where y^-5 moves in 3/(xy^-5)."]'::jsonb, 'approved', 'in_depth', 'topic', 'zero_and_negative_exponent_structure'),
('negative_exponent_on_numerator_factor', 'Negative exponent on numerator factor', 'Negative exponent on numerator factor', 'A factor with a negative exponent in the numerator moves to the denominator with a positive exponent. This targets reciprocal movement from the numerator.', 'exponents_and_radicals', '["Rewrite x^-3/5 using positive exponents.", "Express a^-2b^4 without negative exponents.", "Determine where m^-6 moves in m^-6n."]'::jsonb, 'approved', 'in_depth', 'topic', 'zero_and_negative_exponent_structure'),
('negative_exponent_on_grouped_quantity', 'Negative exponent on a grouped quantity', 'Negative exponent on a grouped quantity', 'A negative exponent on a grouped expression makes the entire grouped base reciprocal. This differs from moving only one term inside the group.', 'exponents_and_radicals', '["Rewrite (x + 2)^-1 using a positive exponent.", "Express (ab)^-3 as a reciprocal.", "Determine the positive-exponent form of (m - n)^-2."]'::jsonb, 'approved', 'in_depth', 'topic', 'zero_and_negative_exponent_structure'),
('negative_exponent_on_fraction', 'Negative exponent on a fraction', 'Negative exponent on a fraction', 'A fraction raised to a negative exponent is rewritten by taking the reciprocal and using the positive exponent. This targets forms like (a/b)^-n.', 'exponents_and_radicals', '["Rewrite (2/3)^-4 using a positive exponent.", "Express (x/y)^-2 without negative exponents.", "Determine the reciprocal form of (a + 1)/b raised to -3."]'::jsonb, 'approved', 'in_depth', 'topic', 'zero_and_negative_exponent_structure'),
('negative_exponent_vs_negative_number', 'Negative exponent versus negative number', 'Negative exponent versus negative number', 'A negative exponent does not make the value negative; it creates a reciprocal. This distinguishes sign from reciprocal structure.', 'exponents_and_radicals', '["Explain why 2^-3 is positive.", "Compare -2^3 and 2^-3.", "Determine whether x^-2 means a negative value or a reciprocal."]'::jsonb, 'approved', 'in_depth', 'topic', 'zero_and_negative_exponent_structure'),
('positive_exponent_convention', 'Positive-exponent convention', 'Positive-exponent convention', 'Many algebraic answers are conventionally written without negative exponents by moving factors across a fraction bar. This is a form convention, not a change in value.', 'exponents_and_radicals', '["Rewrite a^-3b^2 using only positive exponents.", "Express x^4/y^-2 without negative exponents.", "Determine the positive-exponent form of m^-1n^-5."]'::jsonb, 'approved', 'in_depth', 'topic', 'zero_and_negative_exponent_structure'),
('zero_base_negative_exponent_undefined', 'Zero base with negative exponent', 'Zero base with negative exponent', 'A zero base raised to a negative exponent is undefined because it requires division by zero. This targets expressions like 0^-2.', 'exponents_and_radicals', '["Determine whether 0^-3 is defined.", "Explain why x^-2 is undefined when x = 0.", "Identify the excluded value in (x - 5)^-1."]'::jsonb, 'approved', 'in_depth', 'topic', 'zero_and_negative_exponent_structure'),
('variable_restrictions_from_negative_exponents', 'Variable restrictions from negative exponents', 'Variable restrictions from negative exponents', 'Negative exponents create denominator factors in reciprocal form, so any base moved to the denominator cannot be zero. This focuses on restrictions created by exponent rewriting.', 'exponents_and_radicals', '["State the restriction for x^-4.", "Identify the excluded value in (a + 3)^-2.", "Determine the variable restriction in 5m^-1."]'::jsonb, 'approved', 'in_depth', 'topic', 'zero_and_negative_exponent_structure'),
('mixed_positive_zero_negative_exponents', 'Mixed positive, zero, and negative exponents', 'Mixed positive, zero, and negative exponents', 'Expressions may contain positive, zero, and negative exponents at once, requiring each exponent type to be interpreted correctly.', 'exponents_and_radicals', '["Rewrite x^3y^0z^-2 using positive exponents.", "Determine the value of 4^0 · 4^-2.", "Express a^-1b^5c^0 without zero or negative exponents."]'::jsonb, 'approved', 'in_depth', 'topic', 'zero_and_negative_exponent_structure'),
('negative_exponents_after_quotient_rule', 'Negative exponents produced by quotient rules', 'Negative exponents produced by quotient rules', 'Applying the quotient rule may produce negative exponents that can then be rewritten as reciprocal factors. This connects two exponent-law steps.', 'exponents_and_radicals', '["Rewrite x^2/x^7 using positive exponents.", "Determine the positive-exponent form of a^4/a^9.", "Express m^3n^5/(m^8n^2) using positive exponents."]'::jsonb, 'approved', 'in_depth', 'topic', 'zero_and_negative_exponent_structure')
ON CONFLICT (id) DO NOTHING;

-- ─── scientific_notation_with_powers_of_ten topics ────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('multiplication_scientific_notation', 'Multiplication in scientific notation', 'Multiplication in scientific notation', 'Numbers in scientific notation are multiplied by multiplying coefficients and adding powers of 10. The coefficient may need to be adjusted to scientific notation form.', 'exponents_and_radicals', '["Multiply (3 × 10^4)(2 × 10^5).", "Rewrite (6.5 × 10^-3)(4 × 10^7) in scientific notation.", "Determine the product of 1.2 × 10^6 and 5 × 10^-2."]'::jsonb, 'approved', 'in_depth', 'topic', 'scientific_notation_with_powers_of_ten'),
('division_scientific_notation', 'Division in scientific notation', 'Division in scientific notation', 'Numbers in scientific notation are divided by dividing coefficients and subtracting powers of 10. The result may need coefficient adjustment.', 'exponents_and_radicals', '["Divide 8 × 10^9 by 2 × 10^3.", "Rewrite (4.5 × 10^-2)/(1.5 × 10^4) in scientific notation.", "Determine the quotient of 6 × 10^7 and 3 × 10^-5."]'::jsonb, 'approved', 'in_depth', 'topic', 'scientific_notation_with_powers_of_ten'),
('addition_scientific_notation_same_power', 'Addition in scientific notation with same power', 'Addition in scientific notation with same power', 'Scientific-notation values with the same power of 10 can be added by combining coefficients and keeping the common power. This differs from multiplication rules.', 'exponents_and_radicals', '["Add 3 × 10^5 and 4 × 10^5.", "Determine the sum of 7.2 × 10^3 and 1.8 × 10^3.", "Rewrite 5 × 10^-4 + 2 × 10^-4 in scientific notation."]'::jsonb, 'approved', 'in_depth', 'topic', 'scientific_notation_with_powers_of_ten'),
('addition_scientific_notation_different_powers', 'Addition in scientific notation with different powers', 'Addition in scientific notation with different powers', 'Scientific-notation values with different powers of 10 must be rewritten with a common power before coefficients can be combined.', 'exponents_and_radicals', '["Add 3 × 10^4 and 2 × 10^3.", "Rewrite 5.6 × 10^7 + 4 × 10^6 in scientific notation.", "Determine the sum of 8 × 10^-2 and 3 × 10^-3."]'::jsonb, 'approved', 'in_depth', 'topic', 'scientific_notation_with_powers_of_ten'),
('subtraction_scientific_notation', 'Subtraction in scientific notation', 'Subtraction in scientific notation', 'Scientific-notation subtraction requires matching powers of 10 before subtracting coefficients. This targets sign and place-value issues.', 'exponents_and_radicals', '["Subtract 2 × 10^4 from 7 × 10^4.", "Rewrite 6.3 × 10^5 - 4 × 10^4 in scientific notation.", "Determine the difference between 9 × 10^-3 and 2 × 10^-4."]'::jsonb, 'approved', 'in_depth', 'topic', 'scientific_notation_with_powers_of_ten'),
('scientific_notation_coefficient_adjustment', 'Scientific-notation coefficient adjustment', 'Scientific-notation coefficient adjustment', 'After an operation, the coefficient must satisfy 1 ≤ |a| < 10, with the power of 10 adjusted accordingly. This focuses on normalizing scientific notation.', 'exponents_and_radicals', '["Rewrite 24 × 10^5 in proper scientific notation.", "Convert 0.63 × 10^8 to scientific notation.", "Adjust 12.5 × 10^-4 so the coefficient is between 1 and 10."]'::jsonb, 'approved', 'in_depth', 'topic', 'scientific_notation_with_powers_of_ten'),
('scientific_notation_comparison', 'Scientific-notation comparison', 'Scientific-notation comparison', 'Scientific-notation values can be compared using powers of 10 first and coefficients when powers match. This focuses on magnitude comparison.', 'exponents_and_radicals', '["Compare 4.2 × 10^6 and 9.1 × 10^5.", "Order 3 × 10^-4, 7 × 10^-3, and 1 × 10^-5.", "Identify the larger value between 8.5 × 10^2 and 1.2 × 10^3."]'::jsonb, 'approved', 'in_depth', 'topic', 'scientific_notation_with_powers_of_ten'),
('scientific_notation_with_negative_powers', 'Scientific notation with negative powers of ten', 'Scientific notation with negative powers of ten', 'Negative powers of 10 represent small decimal quantities. This targets operations and interpretation involving values less than 1.', 'exponents_and_radicals', '["Rewrite 3.4 × 10^-5 in standard decimal form.", "Multiply 2 × 10^-3 by 5 × 10^-4.", "Compare 6 × 10^-7 and 2 × 10^-6."]'::jsonb, 'approved', 'in_depth', 'topic', 'scientific_notation_with_powers_of_ten')
ON CONFLICT (id) DO NOTHING;

-- ─── rational_exponent_structure topics ───────────────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('unit_fraction_exponents_as_roots', 'Unit fraction exponents as roots', 'Unit fraction exponents as roots', 'An exponent of 1/n represents an nth root. This connects forms like x^(1/2) to square roots and x^(1/3) to cube roots.', 'exponents_and_radicals', '["Rewrite x^(1/2) using radical notation.", "Express 27^(1/3) as a root.", "Identify the root represented by a^(1/5)."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_exponent_structure'),
('rational_exponent_denominator_as_root_index', 'Denominator of rational exponent as root index', 'Denominator of rational exponent as root index', 'In a rational exponent m/n, the denominator n gives the root index. This focuses on interpreting the root part of the exponent.', 'exponents_and_radicals', '["Identify the root index in x^(3/4).", "Rewrite a^(5/2) using a square root.", "Determine the radical index represented by m^(7/3)."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_exponent_structure'),
('rational_exponent_numerator_as_power', 'Numerator of rational exponent as power', 'Numerator of rational exponent as power', 'In a rational exponent m/n, the numerator m gives the power applied to the base or root. This focuses on interpreting the power part of the exponent.', 'exponents_and_radicals', '["Identify the power in x^(3/5).", "Rewrite a^(4/3) using a cube root and fourth power.", "Determine the exponent applied after taking the root in m^(5/2)."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_exponent_structure'),
('rational_exponent_radical_equivalence', 'Rational exponent and radical equivalence', 'Rational exponent and radical equivalence', 'Expressions with rational exponents can be written equivalently using radical notation, and radical expressions can be written using rational exponents.', 'exponents_and_radicals', '["Rewrite x^(2/3) in radical form.", "Express the cube root of a^5 using a rational exponent.", "Convert sqrt(x^7) to rational-exponent notation."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_exponent_structure'),
('root_then_power_vs_power_then_root', 'Root-then-power versus power-then-root', 'Root-then-power versus power-then-root', 'For suitable real-valued expressions, x^(m/n) can be interpreted as taking the nth root and then the mth power, or taking the mth power and then the nth root. This focuses on equivalent rational-exponent structures.', 'exponents_and_radicals', '["Rewrite x^(2/3) as both cube root of x squared and cube root of x^2.", "Identify two radical forms of a^(3/2).", "Determine which radical forms are equivalent to m^(5/4)."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_exponent_structure'),
('negative_rational_exponents', 'Negative rational exponents', 'Negative rational exponents', 'A negative rational exponent combines reciprocal structure with root and power structure. This targets forms like x^(-m/n).', 'exponents_and_radicals', '["Rewrite x^(-2/3) using positive exponents.", "Express a^(-1/2) in radical form.", "Determine the reciprocal form of m^(-5/4)."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_exponent_structure'),
('rational_exponent_product_rule', 'Product rule with rational exponents', 'Product rule with rational exponents', 'Powers with matching bases and rational exponents are multiplied by adding the rational exponents. This extends the product rule beyond integer exponents.', 'exponents_and_radicals', '["Rewrite x^(1/2) · x^(3/2) as one power.", "Determine the exponent in a^(2/3) · a^(5/3).", "Express m^(1/4)m^(7/4) as a single power."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_exponent_structure'),
('rational_exponent_quotient_rule', 'Quotient rule with rational exponents', 'Quotient rule with rational exponents', 'Powers with matching bases and rational exponents are divided by subtracting the denominator exponent from the numerator exponent.', 'exponents_and_radicals', '["Rewrite x^(5/2)/x^(1/2) as one power.", "Determine the exponent in a^(7/3)/a^(2/3).", "Express m^(3/4)/m^(5/4) as a single power."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_exponent_structure'),
('rational_exponent_power_rule', 'Power of a power with rational exponents', 'Power of a power with rational exponents', 'When a power with a rational exponent is raised to another power, the exponents are multiplied. This targets forms like (x^(m/n))^p.', 'exponents_and_radicals', '["Rewrite (x^(1/2))^6 as one power.", "Determine the exponent in (a^(2/3))^3.", "Express (m^(3/4))^2 using one exponent."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_exponent_structure'),
('rational_exponents_on_perfect_powers', 'Rational exponents on perfect powers', 'Rational exponents on perfect powers', 'Rational exponents often produce integer results when the base is a perfect power matching the root index. This connects exponent notation to known roots.', 'exponents_and_radicals', '["Determine the value of 16^(1/2).", "Evaluate 27^(2/3).", "Identify the value of 81^(3/4)."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_exponent_structure'),
('even_denominator_rational_exponents_real_domain', 'Even-denominator rational exponents and real domain', 'Even-denominator rational exponents and real domain', 'A rational exponent with an even denominator involves an even root, so the base must be nonnegative for real-valued results in standard precalculus.', 'exponents_and_radicals', '["State the real-valued restriction for x^(1/2).", "Determine when (x - 3)^(1/4) is real.", "Identify why (-16)^(1/2) is not real."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_exponent_structure'),
('odd_denominator_rational_exponents_negative_bases', 'Odd-denominator rational exponents with negative bases', 'Odd-denominator rational exponents with negative bases', 'Rational exponents with odd denominators can represent real odd roots of negative bases when written in appropriate reduced form. This differs from even-root restrictions.', 'exponents_and_radicals', '["Determine the real value of (-8)^(1/3).", "Rewrite (-27)^(2/3) using cube-root structure.", "Identify why a cube root can accept a negative radicand."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_exponent_structure'),
('rational_exponents_in_lowest_terms', 'Rational exponents in lowest terms', 'Rational exponents in lowest terms', 'The real interpretation of rational exponents can depend on the exponent being considered in lowest terms, especially for negative bases. This targets ambiguity in forms such as (-1)^(2/4).', 'exponents_and_radicals', '["Reduce the exponent in x^(2/4) before interpreting the root.", "Compare (-16)^(1/2) and (-16)^(2/4).", "Identify why rational exponents should be written in lowest terms before domain reasoning."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_exponent_structure'),
('rational_exponent_expression_restrictions', 'Variable restrictions from rational exponents', 'Variable restrictions from rational exponents', 'Variable expressions with rational exponents may require nonnegative bases or nonzero bases depending on even roots and negative exponents. This focuses on restrictions created by the exponent form.', 'exponents_and_radicals', '["State the restrictions for (x - 5)^(1/2).", "Identify the excluded values for x^(-1/3).", "Determine the real-domain restriction for (2a + 1)^(-3/4)."]'::jsonb, 'approved', 'in_depth', 'topic', 'rational_exponent_structure')
ON CONFLICT (id) DO NOTHING;

-- ─── radical_notation_and_root_structure topics ───────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('radicand_identification', 'Radicand identification', 'Radicand identification', 'The radicand is the expression inside a radical symbol. This focuses on reading radical notation and distinguishing the radicand from the index or coefficient.', 'exponents_and_radicals', '["Identify the radicand in sqrt(x + 5).", "Determine the radicand in the cube root of 2a - 1.", "Identify what expression is inside the radical in 4sqrt(3x)."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_notation_and_root_structure'),
('root_index_identification', 'Root index identification', 'Root index identification', 'The index of a radical indicates which root is being taken. A square root has an implied index of 2.', 'exponents_and_radicals', '["Identify the index of the cube root of x.", "Determine the implied index in sqrt(17).", "Classify the root index in the fourth root of a + 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_notation_and_root_structure'),
('square_root_structure', 'Square root structure', 'Square root structure', 'A square root asks for a principal value whose square gives the radicand. This focuses on square-root meaning before simplification or equation solving.', 'exponents_and_radicals', '["Identify the square root structure in sqrt(49).", "Determine what value squared gives 81.", "Classify sqrt(x) as a square-root expression."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_notation_and_root_structure'),
('cube_root_structure', 'Cube root structure', 'Cube root structure', 'A cube root asks for a value whose cube gives the radicand. Cube roots can produce real values for negative radicands.', 'exponents_and_radicals', '["Identify the cube root structure in cbrt(27).", "Determine what value cubed gives -64.", "Classify cbrt(x - 2) as a cube-root expression."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_notation_and_root_structure'),
('nth_root_structure', 'Nth-root structure', 'Nth-root structure', 'An nth root asks for a value that raised to the nth power gives the radicand. This includes square, cube, fourth, fifth, and higher roots.', 'exponents_and_radicals', '["Identify the index in the fifth root of x.", "Determine what the fourth root of 81 means.", "Classify the seventh root of a as an nth-root expression."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_notation_and_root_structure'),
('principal_square_root', 'Principal square root', 'Principal square root', 'The radical symbol sqrt(x) represents the nonnegative principal square root. This distinguishes sqrt(9) from the two solutions of x^2 = 9.', 'exponents_and_radicals', '["Determine the value of sqrt(25).", "Explain why sqrt(16) is 4 rather than ±4.", "Identify the principal square root of 81."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_notation_and_root_structure'),
('even_roots_of_positive_numbers', 'Even roots of positive numbers', 'Even roots of positive numbers', 'Even roots of positive numbers have positive principal values in radical notation. This focuses on real radical values with positive radicands.', 'exponents_and_radicals', '["Determine the fourth root of 16.", "Identify the principal sixth root of 64.", "Evaluate the square root of 121."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_notation_and_root_structure'),
('even_roots_of_zero', 'Even roots of zero', 'Even roots of zero', 'Any even root of zero equals zero. This is a defined boundary case for even-root expressions.', 'exponents_and_radicals', '["Determine the square root of 0.", "Identify the fourth root of 0.", "Classify zero as an allowed radicand for an even root."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_notation_and_root_structure'),
('even_roots_of_negative_numbers_nonreal', 'Even roots of negative numbers are nonreal', 'Even roots of negative numbers are nonreal', 'Even roots of negative numbers are not real numbers in standard real-valued precalculus settings. This targets restrictions on square roots and other even roots.', 'exponents_and_radicals', '["Determine whether sqrt(-9) is real.", "Identify why the fourth root of -16 is not real.", "Classify sqrt(x - 3) as real only when the radicand is nonnegative."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_notation_and_root_structure'),
('odd_roots_of_negative_numbers', 'Odd roots of negative numbers', 'Odd roots of negative numbers', 'Odd roots of negative numbers are real and negative. This distinguishes cube roots and fifth roots from square roots.', 'exponents_and_radicals', '["Determine the cube root of -27.", "Identify the real fifth root of -32.", "Classify cbrt(-8) as real or nonreal."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_notation_and_root_structure'),
('even_root_domain_condition', 'Even-root radicand condition', 'Even-root radicand condition', 'For real-valued even-root expressions, the radicand must be greater than or equal to zero. This applies to square roots, fourth roots, sixth roots, and other even-index radicals.', 'exponents_and_radicals', '["State the condition for sqrt(x + 4) to be real.", "Determine the allowed x-values for the fourth root of x - 2.", "Identify the radicand inequality for sqrt(3x - 9)."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_notation_and_root_structure'),
('odd_root_no_nonnegative_restriction', 'Odd-root radicands allow all real values', 'Odd-root radicands allow all real values', 'Odd-root expressions are real for positive, zero, and negative radicands. This differs from even-root restrictions.', 'exponents_and_radicals', '["Determine whether cbrt(x - 5) has a nonnegative-radicand restriction.", "Identify the real-domain condition for the fifth root of 2x + 1.", "Classify cbrt(-100) as real or nonreal."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_notation_and_root_structure'),
('radical_coefficient_structure', 'Coefficient outside a radical', 'Coefficient outside a radical', 'A number or expression outside a radical multiplies the radical expression. This distinguishes 3sqrt(x) from sqrt(3x).', 'exponents_and_radicals', '["Identify the coefficient in 5sqrt(7).", "Compare 2sqrt(x) and sqrt(2x).", "Determine whether 4 is inside or outside the radical in 4sqrt(a)."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_notation_and_root_structure'),
('nested_radical_structure', 'Nested radical structure', 'Nested radical structure', 'A nested radical contains one radical expression inside another. This focuses on recognizing layered root structure.', 'exponents_and_radicals', '["Identify the inner radical in sqrt(3 + sqrt(5)).", "Classify sqrt(cbrt(x)) as a nested radical.", "Determine which radical is evaluated first in sqrt(1 + sqrt(8))."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_notation_and_root_structure')
ON CONFLICT (id) DO NOTHING;

-- ─── radical_factor_structure_and_rewriting topics ────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('perfect_square_factors_in_square_roots', 'Perfect-square factors in square roots', 'Perfect-square factors in square roots', 'A square-root radicand can be analyzed for perfect-square factors, which can be pulled outside the radical. This targets square-root factor structure.', 'exponents_and_radicals', '["Identify the largest perfect-square factor of 72.", "Rewrite sqrt(50) using a perfect-square factor.", "Determine which factor of 108 can come out of a square root."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_factor_structure_and_rewriting'),
('perfect_cube_factors_in_cube_roots', 'Perfect-cube factors in cube roots', 'Perfect-cube factors in cube roots', 'A cube-root radicand can be analyzed for perfect-cube factors, which can be pulled outside the radical. This targets cube-root factor structure.', 'exponents_and_radicals', '["Identify the largest perfect-cube factor of 54.", "Rewrite cbrt(250) using a perfect-cube factor.", "Determine which factor of 128 can come out of a cube root."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_factor_structure_and_rewriting'),
('perfect_nth_power_factors', 'Perfect nth-power factors', 'Perfect nth-power factors', 'An nth-root radicand can be analyzed for factors that are perfect nth powers. This generalizes square-root and cube-root factor structure.', 'exponents_and_radicals', '["Identify a perfect fourth-power factor of 162.", "Rewrite the fourth root of 80 using a perfect fourth-power factor.", "Determine which factor can come out of the fifth root of 96."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_factor_structure_and_rewriting'),
('prime_factorization_in_radicals', 'Prime factorization in radicals', 'Prime factorization in radicals', 'Prime factorization can reveal groups of factors that match the radical index. This is useful when perfect-power factors are not obvious.', 'exponents_and_radicals', '["Use prime factors to rewrite sqrt(180).", "Determine groups of three factors inside cbrt(432).", "Identify pairs of prime factors inside sqrt(288)."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_factor_structure_and_rewriting'),
('square_root_of_variable_even_power', 'Square root of a variable even power', 'Square root of a variable even power', 'The square root of a variable raised to an even power can be rewritten using half the exponent, with absolute value needed when variables are unrestricted and the resulting power has odd exponent.', 'exponents_and_radicals', '["Rewrite sqrt(x^6) for real x.", "Determine the equivalent form of sqrt(a^8).", "Identify why sqrt(x^2) equals |x| for real x."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_factor_structure_and_rewriting'),
('square_root_of_variable_odd_power', 'Square root of a variable odd power', 'Square root of a variable odd power', 'A square root of an odd variable power can be separated into an outside variable power and one remaining variable factor inside the radical. This targets forms like sqrt(x^5).', 'exponents_and_radicals', '["Rewrite sqrt(x^5) using an outside factor and a remaining radical.", "Determine the outside power in sqrt(a^7).", "Express sqrt(m^9) with one factor of m remaining inside the radical."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_factor_structure_and_rewriting'),
('nth_root_of_variable_power_by_exponent_division', 'Nth root of variable powers by exponent division', 'Nth root of variable powers by exponent division', 'For an nth root of a variable power, the exponent can be divided by the root index to determine outside and leftover factors. This targets quotient-and-remainder exponent reasoning.', 'exponents_and_radicals', '["Rewrite the cube root of x^8 using outside and inside factors.", "Determine the outside power in the fourth root of a^10.", "Express the fifth root of m^13 using exponent division."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_factor_structure_and_rewriting'),
('absolute_value_from_even_roots', 'Absolute value from even roots', 'Absolute value from even roots', 'Even roots of even powers can require absolute value to keep the principal root nonnegative. This is a common variable-radical subtlety.', 'exponents_and_radicals', '["Rewrite sqrt(x^2) for real x.", "Determine why the fourth root of a^4 is |a|.", "Identify whether sqrt(m^6) needs absolute value around m^3."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_factor_structure_and_rewriting'),
('odd_roots_of_variable_powers', 'Odd roots of variable powers', 'Odd roots of variable powers', 'Odd roots of variable powers do not require absolute value because odd roots preserve sign. This distinguishes cube-root rewriting from square-root rewriting.', 'exponents_and_radicals', '["Rewrite cbrt(x^6).", "Determine the equivalent form of the fifth root of a^10.", "Identify why cbrt(m^3) equals m rather than |m|."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_factor_structure_and_rewriting'),
('radical_product_property', 'Radical product property', 'Radical product property', 'For real-valued radicals under appropriate conditions, a root of a product can be written as a product of roots. This supports splitting radicands into factor parts.', 'exponents_and_radicals', '["Rewrite sqrt(36x) as a product of radicals.", "Express cbrt(8a) using separate cube roots.", "Determine whether sqrt(ab) can be split into sqrt(a)sqrt(b) under nonnegative conditions."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_factor_structure_and_rewriting'),
('radical_quotient_property', 'Radical quotient property', 'Radical quotient property', 'For real-valued radicals under appropriate conditions, a root of a quotient can be written as a quotient of roots. This supports separating numerator and denominator radicands.', 'exponents_and_radicals', '["Rewrite sqrt(25/49) as a quotient of square roots.", "Express cbrt(a/b) as a quotient of cube roots.", "Determine the separated radical form of sqrt(x/9)."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_factor_structure_and_rewriting'),
('combining_radicals_into_single_radical', 'Combining factors into a single radical', 'Combining factors into a single radical', 'Products or quotients of radicals with the same index can sometimes be combined into one radical. This is the reverse direction of product and quotient properties.', 'exponents_and_radicals', '["Rewrite sqrt(3)sqrt(12) as one radical.", "Express cbrt(2)cbrt(9) as a single cube root.", "Combine sqrt(x)/sqrt(5) into one radical under appropriate conditions."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_factor_structure_and_rewriting'),
('radical_index_must_match_for_combining', 'Matching radical indices for combining', 'Matching radical indices for combining', 'Radicals can be combined by product or quotient properties only when their root indices match. This prevents combining square roots with cube roots incorrectly.', 'exponents_and_radicals', '["Determine whether sqrt(2)cbrt(3) can be combined as one radical.", "Identify why the fourth root of x and square root of y have different indices.", "Classify which radical products have matching indices."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_factor_structure_and_rewriting'),
('radical_in_lowest_terms', 'Radical in lowest terms', 'Radical in lowest terms', 'A radical is in lowest terms when no perfect-power factor matching the index remains inside, no fraction remains inside when avoidable, and no radical remains in the denominator under common conventions.', 'exponents_and_radicals', '["Determine whether sqrt(48) is in lowest terms.", "Identify why cbrt(24) is in lowest terms but cbrt(54) is not.", "Classify sqrt(3)/2 and 1/sqrt(3) by common radical-form conventions."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_factor_structure_and_rewriting'),
('radical_rewriting_with_numeric_and_variable_factors', 'Radical rewriting with numeric and variable factors', 'Radical rewriting with numeric and variable factors', 'Radical expressions may contain both numerical perfect-power factors and variable-power factors that can be moved outside. This combines numeric and algebraic radical structure.', 'exponents_and_radicals', '["Rewrite sqrt(72x^5).", "Express cbrt(54a^7b^3) using outside factors.", "Determine the outside factors in the fourth root of 80m^9."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_factor_structure_and_rewriting'),
('radicals_with_coefficients_and_factor_extraction', 'Radicals with existing outside coefficients', 'Radicals with existing outside coefficients', 'When a radical already has an outside coefficient, extracted factors multiply that coefficient. This targets forms such as 3sqrt(50).', 'exponents_and_radicals', '["Rewrite 2sqrt(72) after extracting perfect-square factors.", "Determine the new outside coefficient in -3sqrt(18).", "Express 5cbrt(16x^4) after extracting cube factors."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_factor_structure_and_rewriting')
ON CONFLICT (id) DO NOTHING;

-- ─── radical_operations_and_like_radicals topics ──────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('like_radicals_same_index_and_radicand', 'Like radicals with same index and radicand', 'Like radicals with same index and radicand', 'Like radicals have the same root index and the same radicand after rewriting. Only their outside coefficients may differ.', 'exponents_and_radicals', '["Identify whether 3sqrt(5) and 7sqrt(5) are like radicals.", "Determine whether 2cbrt(x) and -4cbrt(x) can combine.", "Classify sqrt(12) and sqrt(3) as like radicals after rewriting."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_operations_and_like_radicals'),
('unlike_radicals_different_radicands', 'Unlike radicals with different radicands', 'Unlike radicals with different radicands', 'Radicals with different radicands are unlike unless they can be rewritten to have the same radicand. This prevents adding unlike radicals directly.', 'exponents_and_radicals', '["Determine whether sqrt(2) and sqrt(3) are like radicals.", "Identify why 4sqrt(7) + 5sqrt(11) cannot combine.", "Classify sqrt(8) and sqrt(18) after rewriting their radicands."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_operations_and_like_radicals'),
('unlike_radicals_different_indices', 'Unlike radicals with different indices', 'Unlike radicals with different indices', 'Radicals with different root indices are unlike even if their radicands match. This targets errors such as combining square roots and cube roots.', 'exponents_and_radicals', '["Determine whether sqrt(5) and cbrt(5) are like radicals.", "Identify why 2sqrt(x) and 3cbrt(x) cannot combine.", "Classify the fourth root of 7 and square root of 7 as like or unlike radicals."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_operations_and_like_radicals'),
('adding_like_square_roots', 'Adding like square roots', 'Adding like square roots', 'Like square-root terms are added by combining outside coefficients while keeping the radical part unchanged.', 'exponents_and_radicals', '["Add 3sqrt(2) and 5sqrt(2).", "Determine the result of sqrt(7) + 4sqrt(7).", "Rewrite -2sqrt(5) + 9sqrt(5) as one radical term."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_operations_and_like_radicals'),
('subtracting_like_square_roots', 'Subtracting like square roots', 'Subtracting like square roots', 'Like square-root terms are subtracted by subtracting outside coefficients while keeping the radical part unchanged.', 'exponents_and_radicals', '["Subtract 4sqrt(3) from 9sqrt(3).", "Determine the result of 6sqrt(11) - sqrt(11).", "Rewrite -2sqrt(5) - 7sqrt(5) as one radical term."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_operations_and_like_radicals'),
('adding_and_subtracting_like_nth_roots', 'Adding and subtracting like nth roots', 'Adding and subtracting like nth roots', 'Like radicals of any matching index can be added or subtracted by combining outside coefficients. The index and radicand stay unchanged.', 'exponents_and_radicals', '["Add 2cbrt(4) and 5cbrt(4).", "Subtract the fourth root of x from 6 times the fourth root of x.", "Rewrite 7cbrt(a) - 3cbrt(a) as one radical term."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_operations_and_like_radicals'),
('combining_radicals_after_rewriting', 'Combining radicals after rewriting', 'Combining radicals after rewriting', 'Radicals that initially look unlike may become like radicals after perfect-power factors are extracted. This targets forms such as sqrt(8) + sqrt(18).', 'exponents_and_radicals', '["Combine sqrt(8) + sqrt(18) after rewriting each radical.", "Determine whether sqrt(12) + sqrt(27) has like radical parts after rewriting.", "Rewrite 2sqrt(50) - 3sqrt(8) using like radicals."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_operations_and_like_radicals'),
('radical_addition_does_not_combine_radicands', 'Radical addition does not combine radicands', 'Radical addition does not combine radicands', 'A sum of radicals is not found by adding radicands under one radical. This targets the misconception sqrt(a) + sqrt(b) = sqrt(a + b).', 'exponents_and_radicals', '["Identify the error in writing sqrt(9) + sqrt(16) = sqrt(25).", "Determine whether sqrt(3) + sqrt(5) equals sqrt(8).", "Correct the mistaken rewrite of sqrt(x) + sqrt(y)."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_operations_and_like_radicals'),
('radical_subtraction_does_not_combine_radicands', 'Radical subtraction does not combine radicands', 'Radical subtraction does not combine radicands', 'A difference of radicals is not found by subtracting radicands under one radical. This targets the misconception sqrt(a) - sqrt(b) = sqrt(a - b).', 'exponents_and_radicals', '["Identify the error in writing sqrt(25) - sqrt(9) = sqrt(16).", "Determine whether sqrt(7) - sqrt(2) equals sqrt(5).", "Correct the mistaken rewrite of sqrt(x) - sqrt(y)."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_operations_and_like_radicals'),
('multiplying_square_roots', 'Multiplying square roots', 'Multiplying square roots', 'Square roots can be multiplied by multiplying radicands, with outside coefficients multiplied separately. This uses the radical product property.', 'exponents_and_radicals', '["Multiply sqrt(3) by sqrt(12).", "Determine the product of 2sqrt(5) and 4sqrt(10).", "Rewrite sqrt(x)sqrt(7x) as one radical expression under appropriate conditions."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_operations_and_like_radicals'),
('multiplying_nth_roots_same_index', 'Multiplying nth roots with the same index', 'Multiplying nth roots with the same index', 'Radicals with the same index can be multiplied by multiplying their radicands. This applies beyond square roots.', 'exponents_and_radicals', '["Multiply cbrt(4) by cbrt(16).", "Determine the product of the fourth root of 2 and the fourth root of 8.", "Rewrite cbrt(x)cbrt(9x) as one cube-root expression."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_operations_and_like_radicals'),
('dividing_radicals_same_index', 'Dividing radicals with the same index', 'Dividing radicals with the same index', 'Radicals with the same index can be divided by forming a radical quotient, when the denominator is valid. This uses the radical quotient property.', 'exponents_and_radicals', '["Divide sqrt(45) by sqrt(5).", "Determine the quotient cbrt(54)/cbrt(2).", "Rewrite sqrt(x^2)/sqrt(3) as one radical quotient under appropriate conditions."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_operations_and_like_radicals'),
('multiplying_binomial_radical_expressions', 'Multiplying binomial radical expressions', 'Multiplying binomial radical expressions', 'Products involving binomials with radicals require distribution, with radical products rewritten when possible. This targets expressions like (a + sqrt(b))(c + sqrt(d)).', 'exponents_and_radicals', '["Multiply (3 + sqrt(2))(5 + sqrt(2)).", "Expand (x + sqrt(5))(x - 2sqrt(5)).", "Determine the product of (sqrt(3) + 1)(sqrt(3) - 4)."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_operations_and_like_radicals'),
('squaring_binomial_radical_expressions', 'Squaring binomial radical expressions', 'Squaring binomial radical expressions', 'A binomial containing radicals must be squared using binomial multiplication, not by squaring each term alone. This targets forms like (a + sqrt(b))^2.', 'exponents_and_radicals', '["Expand (2 + sqrt(3))^2.", "Determine the square of (sqrt(5) - 1).", "Identify the missing middle term in (x + sqrt(7))^2."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_operations_and_like_radicals'),
('conjugate_product_radical_difference_of_squares', 'Conjugate products with radicals', 'Conjugate products with radicals', 'A product of radical conjugates creates a difference of squares that removes the radical from the middle terms. This supports rationalizing and radical expression multiplication.', 'exponents_and_radicals', '["Multiply (3 + sqrt(5))(3 - sqrt(5)).", "Determine the product of (sqrt(7) + 2)(sqrt(7) - 2).", "Identify why conjugate radical binomials produce no radical middle term."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_operations_and_like_radicals')
ON CONFLICT (id) DO NOTHING;

-- ─── rationalizing_and_radical_denominators topics ────────────────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('radical_denominator_convention', 'Radical denominator convention', 'Radical denominator convention', 'Many algebraic forms are conventionally rewritten so radicals do not remain in denominators. This is a form convention based on equivalent fractions.', 'exponents_and_radicals', '["Identify why 1/sqrt(5) is often rewritten.", "Determine whether sqrt(3)/2 has a radical in the denominator.", "Classify 4/sqrt(7) as having a radical denominator."]'::jsonb, 'approved', 'in_depth', 'topic', 'rationalizing_and_radical_denominators'),
('rationalizing_single_square_root_denominator', 'Single square-root denominator', 'Single square-root denominator', 'A denominator containing one square root can be rationalized by multiplying numerator and denominator by the same square root.', 'exponents_and_radicals', '["Rewrite 1/sqrt(3) without a radical denominator.", "Rationalize 5/sqrt(2).", "Determine the equivalent form of 7/sqrt(x) with no square-root denominator."]'::jsonb, 'approved', 'in_depth', 'topic', 'rationalizing_and_radical_denominators'),
('rationalizing_square_root_with_coefficient_denominator', 'Square-root denominator with coefficient', 'Square-root denominator with coefficient', 'A denominator such as a sqrt(b) can be rationalized by multiplying by sqrt(b), while keeping track of the numerical coefficient.', 'exponents_and_radicals', '["Rewrite 3/(2sqrt(5)) without a radical denominator.", "Rationalize 8/(4sqrt(2)).", "Determine the denominator after multiplying 1/(6sqrt(7)) by sqrt(7)/sqrt(7)."]'::jsonb, 'approved', 'in_depth', 'topic', 'rationalizing_and_radical_denominators'),
('rationalizing_nth_root_denominator', 'Nth-root denominator', 'Nth-root denominator', 'An nth-root denominator can be rationalized by multiplying by a radical factor that completes a perfect nth power. This generalizes rationalizing square-root denominators.', 'exponents_and_radicals', '["Rewrite 1/cbrt(2) without a cube-root denominator.", "Rationalize 5/cbrt(9).", "Determine what factor completes cbrt(4) to a perfect cube."]'::jsonb, 'approved', 'in_depth', 'topic', 'rationalizing_and_radical_denominators'),
('rationalizing_variable_radical_denominator', 'Variable radical denominator', 'Variable radical denominator', 'Radical denominators containing variables require multiplying by factors that remove the radical while respecting variable restrictions. This targets forms like 1/sqrt(x).', 'exponents_and_radicals', '["Rewrite 1/sqrt(x) without a radical denominator.", "Rationalize 3/sqrt(2a).", "Determine the restrictions when rationalizing 5/sqrt(x - 1)."]'::jsonb, 'approved', 'in_depth', 'topic', 'rationalizing_and_radical_denominators'),
('rationalizing_binomial_square_root_denominator', 'Binomial square-root denominator', 'Binomial square-root denominator', 'A denominator containing a binomial with a square root is rationalized by multiplying by its conjugate. This removes the radical through a difference of squares.', 'exponents_and_radicals', '["Rewrite 1/(3 + sqrt(2)) without a radical denominator.", "Rationalize 5/(sqrt(7) - 2).", "Determine the conjugate of 4 + sqrt(3) for rationalizing."]'::jsonb, 'approved', 'in_depth', 'topic', 'rationalizing_and_radical_denominators'),
('conjugate_selection_for_rationalizing', 'Conjugate selection for rationalizing', 'Conjugate selection for rationalizing', 'The conjugate of a binomial changes the sign between the two terms while keeping the terms themselves. This is the key multiplier for binomial radical denominators.', 'exponents_and_radicals', '["Identify the conjugate of 5 - sqrt(6).", "Determine the conjugate needed for sqrt(x) + 3.", "Select the correct multiplier for rationalizing 1/(2 - sqrt(5))."]'::jsonb, 'approved', 'in_depth', 'topic', 'rationalizing_and_radical_denominators'),
('rationalizing_denominator_with_two_radicals', 'Denominator with two radical terms', 'Denominator with two radical terms', 'A denominator containing two square-root terms can often be rationalized by multiplying by the conjugate. This targets forms like 1/(sqrt(a) + sqrt(b)).', 'exponents_and_radicals', '["Rewrite 1/(sqrt(5) + sqrt(2)) without a radical denominator.", "Rationalize 3/(sqrt(7) - sqrt(3)).", "Determine the conjugate of sqrt(x) + sqrt(y)."]'::jsonb, 'approved', 'in_depth', 'topic', 'rationalizing_and_radical_denominators'),
('rationalizing_numerator', 'Rationalizing a numerator', 'Rationalizing a numerator', 'Sometimes a radical numerator is rationalized, especially in equivalent-expression work. This uses the same conjugate or radical-factor logic but targets the numerator.', 'exponents_and_radicals', '["Rewrite (sqrt(x) - 2)/(x - 4) by multiplying by a conjugate.", "Rationalize the numerator of (sqrt(a + h) - sqrt(a))/h.", "Determine the conjugate needed to rationalize sqrt(t) - 3."]'::jsonb, 'approved', 'in_depth', 'topic', 'rationalizing_and_radical_denominators'),
('extraneous_domain_restrictions_from_rationalizing', 'Restrictions when rationalizing', 'Restrictions when rationalizing', 'Rationalizing preserves value only when multiplied factors are defined and nonzero in the denominator. This focuses on restrictions that must not be lost during rewriting.', 'exponents_and_radicals', '["State the restriction when rationalizing 1/sqrt(x - 4).", "Identify when the conjugate multiplier for 1/(sqrt(x) - 2) creates a zero denominator.", "Determine the excluded values in a rationalized radical fraction."]'::jsonb, 'approved', 'in_depth', 'topic', 'rationalizing_and_radical_denominators')
ON CONFLICT (id) DO NOTHING;

-- ─── radical_equations_and_rational_exponent_equations topics ─────────────────
INSERT INTO learn_keywords (id, name, label, description, category_id, examples, status, tier, keyword_type, parent_keyword_id) VALUES
('radical_equation_structure', 'Radical equation structure', 'Radical equation structure', 'A radical equation contains a variable inside a radical expression. This distinguishes radical equations from equations that merely contain radical constants.', 'exponents_and_radicals', '["Classify sqrt(x + 5) = 9 as a radical equation.", "Identify which equation has a variable inside a radical.", "Determine whether x + sqrt(3) = 7 is a radical equation."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_equations_and_rational_exponent_equations'),
('isolated_square_root_equations', 'Isolated square-root equations', 'Isolated square-root equations', 'A square-root equation with one isolated radical can be solved by squaring both sides after the radical is isolated. This is the basic radical equation structure.', 'exponents_and_radicals', '["Solve sqrt(x + 4) = 7.", "Determine the solution of sqrt(2x - 1) = 5.", "Find x when sqrt(x - 3) = 0."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_equations_and_rational_exponent_equations'),
('nonisolated_square_root_equations', 'Non-isolated square-root equations', 'Non-isolated square-root equations', 'A radical term must be isolated before both sides are squared. This targets equations where constants or other terms are attached to the radical.', 'exponents_and_radicals', '["Solve sqrt(x + 1) + 3 = 8.", "Determine the first step for 2sqrt(x - 4) - 5 = 7.", "Find x in 4 - sqrt(3x) = 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_equations_and_rational_exponent_equations'),
('square_root_equations_with_linear_radicands', 'Square-root equations with linear radicands', 'Square-root equations with linear radicands', 'A square-root equation may contain a linear expression inside the radicand, producing a linear equation after squaring. This targets forms like sqrt(ax + b) = c.', 'exponents_and_radicals', '["Solve sqrt(3x - 2) = 4.", "Determine x in sqrt(5 - 2x) = 3.", "Find the solution of sqrt(7x + 1) = 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_equations_and_rational_exponent_equations'),
('square_root_equations_leading_to_quadratics', 'Square-root equations leading to quadratics', 'Square-root equations leading to quadratics', 'Some square-root equations produce quadratic equations after squaring, especially when a variable expression remains outside the radical. This connects radical equations to quadratic solving.', 'exponents_and_radicals', '["Solve sqrt(x + 5) = x - 1.", "Determine the quadratic equation formed from sqrt(2x + 3) = x.", "Find possible solutions of sqrt(x + 6) = x - 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_equations_and_rational_exponent_equations'),
('radical_equations_with_radicals_on_both_sides', 'Radical equations with radicals on both sides', 'Radical equations with radicals on both sides', 'When radicals appear on both sides, squaring may remove both radicals or may need to be repeated. This targets equations such as sqrt(A) = sqrt(B).', 'exponents_and_radicals', '["Solve sqrt(x + 6) = sqrt(3x - 2).", "Determine the equation formed by squaring sqrt(2a + 1) = sqrt(a + 9).", "Find x when sqrt(x^2 + 3) = sqrt(4x + 7)."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_equations_and_rational_exponent_equations'),
('radical_equations_requiring_two_squaring_steps', 'Radical equations requiring two squaring steps', 'Radical equations requiring two squaring steps', 'Some equations with multiple radicals require isolating one radical, squaring, then isolating and squaring again. This targets layered radical-equation solving.', 'exponents_and_radicals', '["Solve sqrt(x + 5) + sqrt(x - 1) = 4.", "Determine the next step after squaring sqrt(a + 3) = 2 - sqrt(a).", "Find candidate solutions for sqrt(2x + 1) - sqrt(x - 2) = 1."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_equations_and_rational_exponent_equations'),
('cube_root_equations', 'Cube-root equations', 'Cube-root equations', 'A cube-root equation can be solved by cubing both sides after the cube-root expression is isolated. Cube roots allow negative radicands in real-number settings.', 'exponents_and_radicals', '["Solve cbrt(x - 2) = 3.", "Determine x in cbrt(2x + 5) = -1.", "Find the solution of 4 + cbrt(x) = 6."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_equations_and_rational_exponent_equations'),
('nth_root_equations', 'Nth-root equations', 'Nth-root equations', 'An nth-root equation can be solved by raising both sides to the nth power after isolating the radical. Even-index roots require attention to real-valued restrictions.', 'exponents_and_radicals', '["Solve the fourth root of x + 1 equals 3.", "Determine x in the fifth root of 2x - 7 equals 1.", "Find the solution of the sixth root of x equals 2."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_equations_and_rational_exponent_equations'),
('rational_exponent_equations', 'Rational-exponent equations', 'Rational-exponent equations', 'Equations involving rational exponents can often be rewritten in radical form or solved by raising both sides to reciprocal powers. This focuses on exponent-root equation structure.', 'exponents_and_radicals', '["Solve x^(1/2) = 6.", "Determine x in (x - 1)^(1/3) = 4.", "Find the solution of (2x + 3)^(2/3) = 9."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_equations_and_rational_exponent_equations'),
('reciprocal_power_in_rational_exponent_equations', 'Reciprocal powers in rational-exponent equations', 'Reciprocal powers in rational-exponent equations', 'To undo a rational exponent m/n, both sides may be raised to the reciprocal power n/m, with domain and extraneous-solution checks as needed.', 'exponents_and_radicals', '["Solve x^(3/2) = 8 by using a reciprocal power.", "Determine the reciprocal power needed for (a + 1)^(2/5) = 4.", "Find x in (x - 2)^(4/3) = 16."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_equations_and_rational_exponent_equations'),
('extraneous_solutions_from_squaring', 'Extraneous solutions from squaring', 'Extraneous solutions from squaring', 'Squaring both sides of an equation can introduce solutions that do not satisfy the original radical equation. Every candidate must be checked.', 'exponents_and_radicals', '["Check candidate solutions for sqrt(x + 5) = x - 1.", "Identify the extraneous solution in a squared radical equation.", "Determine why x = 0 fails the original equation after squaring."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_equations_and_rational_exponent_equations'),
('radical_equation_domain_restrictions', 'Domain restrictions in radical equations', 'Domain restrictions in radical equations', 'Radical equations with even-index roots require radicands to be nonnegative and isolated radical values to match principal-root behavior. These restrictions guide possible solutions.', 'exponents_and_radicals', '["State the radicand restriction for sqrt(2x - 5) = x.", "Identify possible x-values before solving sqrt(7 - x) = x - 1.", "Determine why a negative right side may make sqrt(x + 4) = -3 impossible."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_equations_and_rational_exponent_equations'),
('no_solution_radical_equations', 'Radical equations with no real solution', 'Radical equations with no real solution', 'A radical equation may have no real solution because of domain restrictions, principal-root restrictions, or extraneous candidates after solving.', 'exponents_and_radicals', '["Determine why sqrt(x + 2) = -5 has no real solution.", "Solve sqrt(x - 1) = x - 3 and check whether any candidates remain.", "Classify a radical equation as no solution after all candidates fail."]'::jsonb, 'approved', 'in_depth', 'topic', 'radical_equations_and_rational_exponent_equations')
ON CONFLICT (id) DO NOTHING;
